### ISSUE TITLE
Test Pilot keeps asking me for feedback

### ISSUE THREAD

**Issue by Digivonity** [mozilla/testpilot#1024]
I gave feedback on Vertical Tabs two times now (with different answers for sure ;) Since the feedback form seems rather final, my feedback should be flagged as given. Is it depending on cookies? Then maybe Ghostery is the wrong doer.

Firefox 47 on Ubuntu 16.04

**Comment by johngruen** [comment]
@digivonity, how far apart were these feedback events?

**Comment by meandavejustice** [comment]
Hey @Digivonity We've just addressed this issue in a recent commit https://github.com/mozilla/testpilot/commit/782239e2922787b01bfe58bdec057dccae5d3d51 It should be deployed soon, sorry for the inconvenience.

I'll leave this issue open until the fix is officially deployed in case more people wanna report this issue.
