### ISSUE TITLE
Make the ideatown website session cookie last forever, by default

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#103]
Long-lasting sessions will make it easy for the addon to send lifecycle events to the server, even if the user only rarely visits the site.

**Comment by lmorchard** [comment]
Hmm, this seems like a good idea. Though, we should also ensure that the add-on can cope with the cookie disappearing / going invalid. 

We might even want to consider [using JSON web tokens](https://github.com/GetBlimp/django-rest-framework-jwt) at some point and issue one specifically for the add-on with some flow for reauth when it expires. Maybe even show a browser notification / door hanger like "it's been awhile since you've been back to idea town... want to come back, or do you want to uninstall & be done with us?"
