### ISSUE TITLE
Blank page is randomly displayed when redirected after add-on instalation or experiment page opened in a new tab

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1101]
[Affected versions]:
- Nightly 50.0a1
- Add-on v0.8.0-tag-2016-07-15-1

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Steps to reproduce]:
1. Go to https://testpilot.firefox.com/ and install the Test Pilot add-on.
2. Observe where you are redirected after installation.
3. Click the "Test Pilot" icon from toolbar and click on any of the available experiments.

[Expected result]:
2. The user is redirected to the experiments page.
3. Experiment description page is opened in a new tab. 

[Actual result]:
2. The user is randomly redirected to a blank page even if the link in address bar seems correct.
3. New tab opened and user is randomly redirected to a blank page even if the link in address bar seems correct.

[Notes]:
- Added a screenshot with the browser console errors. The web console does not display almost any errors except "waitForMessage timeout: sync-installed".
- Tried with a new profile and cache cleared but same issue occurs.
- The page only loads after multiple refreshes
  ![console errors](https://cloud.githubusercontent.com/assets/17258026/16957368/bb051f74-4de4-11e6-8663-99344459a437.png)
  .

**Comment by lmorchard** [comment]
The previous issue like this was #1075 on installation - but this seems to be on post-installation page load. 

I can't reproduce this issue after a dozen or so tries. But, I think the error [comes from this code that messages the add-on on page initialization](https://github.com/mozilla/testpilot/blob/master/testpilot/frontend/static-src/app/main.js#L46). Seems like another race condition since we dropped the HTTP request for `/api/me`. Going to try harder to reproduce this, but I may just try bullet proofing this add-on communication more thoroughly.

**Comment by ckprice** [comment]
Found a pretty reliable STR.

After clicking install, you'll see the `Installing...` spinner AND the toolbar icon appear at the same time. During this interval (and before the page redirects) if you click on the icon then an experiment you'll get the error.

**Comment by lmorchard** [comment]
> Found a pretty reliable STR.

@ckprice That sounds like a different issue (maybe still #1075?) - this is happening when you just load a page after the add-on has already been installed.

This would actually load a second page it seems like, so it might be exercising the same error.

But, I can't actually manage to click the toolbar icon & a listed experiment before the spinner stops spinning - so maybe part of why I can repro is because my machine is too fast and this is a race condition?
