### ISSUE TITLE
"Please Rate the Test Pilot experiment undefined"

### ISSUE THREAD

**Issue by ckarlof** [mozilla/testpilot#1142]
On Firefox Nightly 50 this morning:

<img width="1913" alt="screenshot 2016-07-27 09 17 15" src="https://cloud.githubusercontent.com/assets/2365255/17183160/2ce1ec70-53db-11e6-966c-1786640a3be6.png">

Also, I'm only using Activity Stream and I've already rated it many times.

**Comment by johngruen** [comment]
@meandavejustice still seeing this in the wild...can you take a look ASAP

**Comment by jaredhirsch** [comment]
@meandavejustice Stealing this bug. Feel free to steal back if you're actively working on it ^_^

**Comment by johngruen** [comment]
@clouserw @6a68 is working on this one now, let's see if he can get it in before we tag

**Comment by jaredhirsch** [comment]
I've been working on this, on and off, for a couple of weeks. I can't reproduce this bug.

I'll try to reproduce in an older Nightly or older version of the add-on today; perhaps the bug's been fixed by an unrelated change.

Bug reporters (@ckarlof @ashughes1 @bnjbvr @past @mythmon), if you've seen this bug again in the last 1-2 weeks, please drop a comment in this bug with your OS info, Firefox version, Test Pilot add-on version, and what add-ons you've got installed. Thx!

**Comment by jaredhirsch** [comment]
I rolled back to commit `9e41e92`, from around the time this bug was opened by ckarlof.

I applied this set of changes to the addon code to toggle a survey notification every second: https://gist.github.com/6a68/4a80e1b53730ba84c9a93091033d7f14

I'm able to reproduce this bug as of the old commit, and I'm not able to reproduce in today's master.

I'm not going to git bisect to the exact commit that fixed the bug, but we have good and bad commits, so it would be possible.

Closing.
