### ISSUE TITLE
Use a manually-set preference to change Test Pilot add-on environment

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#1196]
The main add-on has two things for dev & testing convenience that are most likely causing problems:
- [The environment selector in `about:addons` settings](https://github.com/mozilla/testpilot/blob/master/addon/package.json#L44) - general users have found it and gotten into unexpected situations.
- [The code that inspects browser history on installation and auto-selects an environment based on the last Test Pilot environment you visited](https://github.com/mozilla/testpilot/blob/master/addon/index.js#L118) - this seems to be changing the environment at undesirable times.

We should replace both of these with a single manually-set pref - either in `about:config` or in a `user.js` file. It could be set before add-on installation and would allow the "Install" button to work properly on respective environments.

**Comment by chuckharmston** [comment]
From @clouserw in #1198:

---

When Test Pilot starts, there is some code that attempts to look into your history and see the most recently visited test pilot site, and then set the Test Pilot add-on to work with that site (dev/stage/prod/local).  That code might be causing some weird issues (like the hard-to-reproduce white pages on load) but it definitely affects things like #1162.  

Instead of that code, let's do a simpler check:  On startup and each time the Test Pilot menu button is clicked, look for a pref called `extensions.testpilot-addon.developermenu` and if it exists add a quick-change option to our menu button.  Like so, only, you know, prettier:

![devmenu](https://cloud.githubusercontent.com/assets/16946141/17448263/41a3d34c-5b08-11e6-9b14-89e72f5609a6.png)

Then everyone installs like normal from wherever, and if they need the menu they go to about:config and add the pref.  If you were feeling fancy, you could even put a little local/dev/stage badge on the icon, but that might be too much. :)

Thoughts?

**Comment by jaredhirsch** [comment]
> We should replace both of these with a single manually-set pref - either in about:config or in a user.js file. It could be set before add-on installation and would allow the "Install" button to work properly on respective environments.

:+1: to this, much simpler than adding doorhanger UI, etc.

**Comment by johngruen** [comment]
Yeah, config flag seems massively easier.

**Comment by ghost** [comment]
bah :) 🌾
