### ISSUE TITLE
NoMore404s page tells me that it requires Firefox 48+, even though I have 51 installed

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1208]
I was initially confused because I was rocking The Nightly. Not sure if we want to hide the "No More 404s requires Firefox 48 or later" message box if the user is using Firefox >=48.

![firefox_test_pilot_-_no_more_404s](https://cloud.githubusercontent.com/assets/557895/17488593/e764bc04-5d4e-11e6-8458-faa90241800d.png)

**Comment by ckprice** [comment]
Looks like this was added to the `Introduction` block in admin so it's shown to everyone. This could be pretty distracting for up-to-date users.

GA sessions says that since Aug 3, we're at ~60% < 48, and 40% >= 48. The percentages get more up-to-date the further you get from the 48 release date (Aug 2).

**Comment by johngruen** [comment]
@pdehaan @ckprice yeah, added this as a mitigation on friday when 48 was still rolling out.

**Comment by pdehaan** [comment]
@johngruen Are we planning on removing it when 48 is mainstream, or adding a version sniffer script which dynamically removes that `<div>` if the user's Firefoxen version is >=48?

**Comment by gaby2300** [comment]
I am still having this issue even though my Nightly is up to date.

Best regards,
Gabriela
QA Mozilla Hispano Team Responsible

**Comment by ghost** [comment]
@pdehaan the latest version has a strict_min_version of 48 in its manifest.  Could you try installing with a version before 48 and see what happens?  If that message is nice enough, we might be able to drop this one sooner.

**Comment by SoftVision-PaulOiegas** [comment]
Tested with a release 44 and Nightly 46 and got the same message on the page. Even managed to enable NoMore404s experiment on it. Do I sniff a bug here ?

**Comment by ghost** [comment]
Getting the message on the page is expected.  It shows up for everyone.

However, I would expect Firefox to refuse to install an add-on with a higher minimum version than it has.  I don't know what that UI or behavior looks like though.

**Comment by SoftVision-PaulOiegas** [comment]
Yeah, my thought too but it seams that Firefox installs them first and after disables them. At least it does that for Activity Stream and Universal Search. 
The other ones seem to be installed but they don't work. At least Blok is not blocking a known page for tracking and NoMore404s displays me a 404 for an archived page. Probably that's why both of them don't have the icons displayed in "Extensions" tab.

So the bottom line is that nothing blocks you to install them trough Test Pilot but the ones that are not compatible with Fx version are either not working, either disabled by the browser. 

![test pilot experiments on fx 44 0](https://cloud.githubusercontent.com/assets/17258026/17559188/f44e375a-5f25-11e6-838b-dea8f4bcb34c.png)

**Comment by jaredhirsch** [comment]
We could really easily check `navigator.userAgent` and disable the button if the version number is too low.

**Comment by johngruen** [comment]
![details page - min-version 2x](https://cloud.githubusercontent.com/assets/3323249/17669712/b7a2ab8c-62dc-11e6-97fd-2e567d3551b6.png)

### It should:
- [ ] Display if the user's version of Firefox is < the designated minimum version specified by the add-on
- [ ] Only display if the user has Test Pilot installed
- [ ] Link to this page: https://support.mozilla.org/lt/kb/find-what-version-firefox-you-are-using

**Comment by ckprice** [comment]
Let's wait on this until we finish backend migration.

**Comment by johngruen** [comment]
@lmorchard assuming we ship the backend migration this train, I can pick this issue up.
