### ISSUE TITLE
experiment-detail page: back button broken

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#124]
Seems like the history / pushState behavior needs some work.

STR:
1. Load an experiment detail page
2. Hit the 'back' button
3. The 'home' route is shown in the urlbar, but the 'home' page doesn't load

**Comment by lmorchard** [comment]
@meandavejustice Was this fixed by PR #142?

**Comment by meandavejustice** [comment]
Need to do some heavier testing here, I have a hunch it may be an issue with ampersand's router in firefox.

**Comment by meandavejustice** [comment]
This actually seems to be a difference in the interpretation of the pushstate spec in firefox vs blink. 

Here are some bugs:
https://bugzilla.mozilla.org/show_bug.cgi?id=1185420
https://bugzilla.mozilla.org/show_bug.cgi?id=976020
https://bugzilla.mozilla.org/show_bug.cgi?id=1059382

**Comment by lmorchard** [comment]
Hmm, this bug is weird. 

If I hit /home, click on an experiment, then hit back - it seems to work as expected. I can click back & forth as much as I want.

But, if I hit /home, click on an experiment, **focus on the URL bar & hit return** (not quite a reload), then hit back - things break such that /home never appears despite URL bar changes.

**Comment by meandavejustice** [comment]
Right, that's what I'm experiencing too :(

**Comment by lmorchard** [comment]
Trying this as an upstream fix to Ampersand, just for the sake of completeness

https://github.com/AmpersandJS/ampersand-router/pull/49
