### ISSUE TITLE
Replace most of the django-derived experiment data

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#1250]
I've started to rough out a [template](https://github.com/mozilla/testpilot-meta/blob/master/src/template/data.hjson) for experiment details using [hjson](http://hjson.org/) and gulp. Let's take this further by migrating it into the repo and replacing as much of the django API as we can for experiments.

**Comment by johngruen** [comment]
@lmorchard just to be clear, my little experiment in the meta repo is not meant to be proscriptive. If it helps, please use it, but feel free to ignore it!

**Comment by lmorchard** [comment]
Got some initial progress, playing with YAML instead of HJSON. We could possibly move things pretty easily to Jekyll someday if we start with YAML now, and it doesn't look much different than HJSON. 

Using a gulp task to import & massage content from the existing prod API, that results in experiment content files like this:

https://github.com/lmorchard/testpilot/blob/02395866a9681f3d3e6b045a4d1e2d9c26a512f1/content-src/experiments/activity-stream.yaml

Then, another gulp task builds a static version of `/api/experiments` that seems to work seamlessly with the frontend app and the add-on without changes.

Still need to do something about pulling images and things into the repo, so that will come next.

**Comment by pdehaan** [comment]
+1 to YAML.

Also, you can probably remove a bunch of the optional single/double quotes. May also be easier to use multiline string format for some of the HTML blocks (like `measurements` which has escaped quotes-n-stuff):

http://stackoverflow.com/questions/3790454/in-yaml-how-do-i-break-a-string-over-multiple-lines

**Comment by lmorchard** [comment]
Well, this is just whatever the YAML serializer is doing, so i can get a quick import. But for manual edits, we can do whatever is valid yaml

**Comment by lmorchard** [comment]
b56aaf3244e5c532fc6c66c095478d2706644bc4
