### ISSUE TITLE
Add more detail to ADDON-ENVIRONMENT.md docs

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1262]
We recently changed the way we switch environments. The section in [the docs](https://github.com/mozilla/testpilot/blob/master/docs/ADDON-ENVIRONMENT.md#how-to-change-your-add-on-environment) doesn't seem to be sufficient for properly changing environments to make the site and add-on sync up.

There's some knowledge spread out over [IRC](http://logs.glob.uno/?c=mozilla%23testpilot&s=17+Aug+2016&e=17+Aug+2016&h=environment#c20666) and in [PRs](https://github.com/mozilla/testpilot/pull/1225#issuecomment-240489277). This bug is opened to consolidate this information and update the docs.

**Comment by lmorchard** [comment]
FWIW, that bit in the IRC log is just me tl;dr'ing [what's already in ADDON-ENVIRONMENT.md](https://github.com/mozilla/testpilot/blob/master/docs/ADDON-ENVIRONMENT.md#aboutconfig-method) - is there something more that needs adding there? (probably, since I stare at this thing every day and forget what I know most times)

The comment in the PR is probably an edit that should happen [here in the addon/README.md](https://github.com/mozilla/testpilot/blob/master/addon/README.md#distributing) about `npm run package` vs `npm run sign` for when you don't have AMO credentials.

**Comment by ckprice** [comment]
These are the two steps in the document:

```
1. Go to `about:config`
2. Edit the preference `testpilot.env` to one of these values 
```

Doing just these two things hasn't worked for me. Some other things
- There are times that the `testpilot.env` config isn't in the list, so sometimes you'll have to create it.
- If I have the add-on installed already, switching the config has no effect (e.g. dev site still doesn't think that the add-on is installed).
- The IRC log mentions setting the config before installing, which the doc does not.

I was eventually able to get the two in sync after a series of restarts, uninstalls, config changes, and `npm runonce`. I don't currently have reliable steps to set the environment.

/edit a lot of my angst is coming from testing functionality on Install/Uninstall. It seems to work alright if I already have it installed and just want to bounce between environments.
