### ISSUE TITLE
Setting the environment pref after Test Pilot installation on new profile will always display a NoMore404s push notification

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1296]
[Affected versions]:
- Nightly 51.0a1

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- A new profile was created.

[Steps to reproduce]:
1. Open Firefox with the newly created profile.
2. Go to https://testpilot.stage.mozaws.net page and choose to "Install the Test Pilot Add-on".
3. When prompted by the browser, choose to "Allow" the installation. 
4. After download is complete click the "install" button.
5. Add the "testpilot.env" string pref in "about:config" page with "stage" value.
6. After the installation redirect occurs, observe the bottom right side of the browser (Windows & Linux) / top left part of the browser (Mac OS).

[Expected result]:
- Nothing appears on the right side of the browser after installation.

[Actual result]:
- A push notification about NoMore404s experiment is displayed.

[Notes]:
- This issue always occurs when installing on a new profile.
- This issue does not occurs if the environment pref is added in "about:addons" page before installing Test Pilot add-on.
- Also, on Mac OS Nightly builds, the push notification is not dismissed by clicking on it. Not reproducible on release or other OS.

![nomore404 notification](https://cloud.githubusercontent.com/assets/17258026/18014459/b76e9642-6bcb-11e6-990c-c76abf7b27f2.png)

**Comment by dannycoates** [comment]
This looks like a side effect of different data on prod and stage.

Production has a notification no-more-404s:

``` json
{
          "id": 1,
          "title": "Tired of 404s?",
          "text": "Check out our latest experiment!",
          "notify_after": "2016-08-21T20:15:45Z"
}
```

This gets ignored by the addon since it's a fresh install.

Then the env changes so it loads the data from stage which has a different set of notifications:

``` json
        {
          "id": 6,
          "title": "Tried No More 404s?",
          "text": "Check it out today in Test Pilot!",
          "notify_after": "2016-08-16T20:47:14Z"
        },
        {
          "id": 7,
          "title": "Tired or 404s?",
          "text": "Check out this new experiment!",
          "notify_after": "2016-08-16T20:51:18Z"
        },
        {
          "id": 8,
          "title": "Tired of 404s?",
          "text": "Check out this new experiment!",
          "notify_after": "2016-08-21T20:05:45Z"
        },
        {
          "id": 9,
          "title": "Tired of 404s?",
          "text": "Check out our latest experiment!",
          "notify_after": "2016-08-21T20:11:24Z"
        }
```

Now the addon will see these as new notifications and show the alert(s). Does it show multiple notifications? If it doesn't I wonder if the browser is deduping them.

**Comment by lmorchard** [comment]
Oh! Yeah that totally makes sense - the add-on only ignores the first batch of notifications it sees, regardless of environment. So, if you change environment, that looks like a second new batch to the code because it doesn't keep track of those by environment. 

I wonder if maybe we should keep them separated? Kind of a corner case that only affects us weirdos who change environments all the time, but might also be a bit of noise that's really confusing during testing.

> Does it show multiple notifications? If it doesn't I wonder if the browser is deduping them.

And de-duping is expected too: When a new batch of multiple notifications is seen for an experiment, the add-on [marks the whole batch as "seen"](https://github.com/mozilla/testpilot/blob/master/addon/lib/experiment-notifications.js#L98) and then [picks one at random to display](https://github.com/mozilla/testpilot/blob/master/addon/lib/experiment-notifications.js#L102). This lets us send out a bunch of variants and then measure which message performed the best.

**Comment by chuckharmston** [comment]
> I wonder if maybe we should keep them separated? Kind of a corner case that only affects us weirdos who change environments all the time, but might also be a bit of noise that's really confusing during testing.

For what it's worth, I've been keeping disparate profiles for each environment, rather than switching prefs. It's been clean and simple, and avoids issues like this entirely.
