### ISSUE TITLE
Error page displayed if "F5" key is held for about 2 seconds on any Test Pilot page

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#1299]
[Affected versions]:
- Nightly 51.0a1

[Affected Platforms]:
- All Windows

[Steps to reproduce]:
1. Open the browser and navigate to "https://testpilot.stage.mozaws.net".
2. Hold down for ~2 seconds the "F5" key.
3. Observe the page behavior.

[Expected result]:
- The page is correctly refreshed no matter how long or how many times the "F5" key is pressed.

[Actual result]:
- An error page is displayed.

[Notes]:
- When the error page is displayed the URL is changed in "https://testpilot.stage.mozaws.net/error" and another refresh will not display the previously refreshed page. The user has to manually navigate to another page in order to get rid of the error.  
- The issue is also reproducible on each experiment page.
- Added a screen recording with the issue http://goo.gl/JEywIp.

**Comment by lmorchard** [comment]
I'd guess 2 things are happening here:
1. One of the refreshes interrupts the requests to fetch experiment content JSON, which results in an error and a redirect to our error page
2. Our error page is at a different URL, so subsequent refreshes just stay on that error page.

We should probably figure out a way to more gracefully handle 1. And for 2, we should probably not bounce to a different URL on error so that a refresh will result in another attempt at the page that threw an error.

**Comment by ghost** [comment]
This isn't something we're prioritizing right now. thanks
