### ISSUE TITLE
No restriction notification is displayed for users that are trying to instal Test Pilot on incompatible Fx version

### ISSUE THREAD

**Issue by parag9d** [mozilla/testpilot#1310]
"Install the Test Pilot add-on" CTA shows installation in progress even after installation is complete
- Operating system: OS X 10.11.6
- Firefox build 38.0.5

<img width="1680" alt="screen shot 2016-08-30 at 12 51 03 pm" src="https://cloud.githubusercontent.com/assets/6411097/18082930/8be2f09a-6ebe-11e6-9533-3dfd7ee5da18.png">

**Comment by parag9d** [comment]
That is a firefox build issue. Installed nightly, no issues on nightly.

**Comment by SoftVision-PaulOiegas** [comment]
Hey parag9d, thanks for your report ! This issue occurs because Test Pilot is not working on builds older than Fx 45.x. That's why you don't see this on Nightly builds. Please update your browser before installing Test Pilot.

However, I do agree that we should have some kind of notification for the users to inform them about this. I'll modify your issue title to reflect this.

**Comment by parag9d** [comment]
@SoftVision-PaulOiegas Thanks for the modification. I agree that it will better to give the user some visual cues that his/her current version doesn't support test pilot 👍

**Comment by sevaan** [comment]
Proposed UX: https://mozilla.invisionapp.com/share/Q77S1H6ZC#/188648739_Old_Firefox_Warning

Instead of just telling a user their Firefox is out of date and leaving them hanging, let's replace the TP installation button with an Upgrade Firefox message/button. Basically this is re-using our Non-FX browser landing page and changing the text.

**Comment by johngruen** [comment]
This is ready to go! Thanks @sevaan
