### ISSUE TITLE
Don't require users to discretely install Test Pilot extension.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1331]
Problem: it’s sort of conceptually illogical that users need a Test Pilot extension before installing any experiments.

Once a fix for #1223 lands, we'll be able to install the Test Pilot add-on without a prompt. This is pretty swell, and will let us seamlessly remove that requirement. Instead, we could quietly install the Test Pilot extension whenever the user attempts to enable an experiment, if the Test Pilot prerequisite isn't already installed. This would drastically simplify the UX: we could remove the CTAs on the homepage and experiment pages and should put a stronger focus on the experiments. I'd expect it to have a pretty positive impact on conversion rates.

**Comment by johngruen** [comment]
@chuckharmston yeah, i'd like to see this as well. Now that we've got the experiment pages viewable regardless of add-on install, I think this is the way to go.

Also, I feel like this issue exists somewhere, but I'm finding it.
- Adding a needs product and large flag

**Comment by sevaan** [comment]
A simple/quick way to approach this is to keep the CTA areas, which are pretty eye-catching, and on experiment sub-pages just change the button text:

<img width="1239" alt="screen shot 2016-09-14 at 1 50 04 pm" src="https://cloud.githubusercontent.com/assets/473531/18523424/29c41090-7a82-11e6-88ca-851d02f5703d.png">

Here is what it looks like if we don't have that area and just replace the Enable experiment button:

<img width="1235" alt="image" src="https://cloud.githubusercontent.com/assets/473531/18523464/53b98100-7a82-11e6-92cf-8b931596ac66.png">

**Comment by sevaan** [comment]
The button could change to an "installing" state once clicked on, we'd go through the installation flow, and the page would refresh to display the TP-enabled details page and the experiment tour.

Would have to figure out how email collection fits in there though.

**Comment by chuckharmston** [comment]
Two immediate thoughts:
- I'm not sure we even need to say "with Test Pilot". Do users need to know about that bit of sausage-making.
- I think it might make more sense to examine the flow from even farther out. What's our homepage like, if not a CTA to install the Test Pilot add-on?

**Comment by SoftVision-PaulOiegas** [comment]
@chuckharmston I think the users should know that they get two add-ons instead of one when doing this. Otherwise some of them could end up removing Test Pilot and all the other installed experiments together with it. This is the current behavior when removing Test Pilot from "about:addons" page and you have other experiments installed too.

@sevaan What happens if the user enables one of the experiments with Test Pilot, and after lands on a second experiment page ? The UI should be different after Test Pilot is installed with the first enabled experiment.

In regards to the email collection. Maybe we could add the newsletter text field on the experiment activation pop up ? I know that we will display that field & text each time an experiment is enabled but since it's not mandatory. I don't think it will affect users. 
If not, maybe a timed push with a dialog after a while from installation ?

**Comment by johngruen** [comment]
@sevaan @chuckharmston yeah, following @SoftVision-PaulOiegas I'm not convinced its as simple as changing a button. I think at the very least we'd need a tour to explain what the user just did and what it means.

**Comment by johngruen** [comment]
http://i.sevaan.com/1m0w1I2L0r2x

**Comment by fzzzy** [comment]
This is fixed by https://github.com/mozilla/testpilot/compare/b4f21d3dc4ff...f8cf62329d02
