### ISSUE TITLE
Write tests for add-on installation

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1334]
Installation of the Test Pilot add-on is probably the most important code we have, but best I can tell, there are no client tests for it. We should try to write some.

**Comment by jaredhirsch** [comment]
We should be able to do this using marionette / webdriver, I think

**Comment by lmorchard** [comment]
FWIW, we have [an integration test](https://github.com/mozilla/testpilot/blob/master/integration/test_installation.py#L35) using marionette + firefox puppetter to drive a Firefox instance through the install & on-boarding process. That's an outside-in test at the user leve.

Would be great to find a way to find a harness that can mock up the browser APIs and do this more from the unit testing side of things for inside-out testing at the code level. You _can_ inject JS into chrome from marionette - so maybe that's a starting point for shoving a harness & mocks into the browser? I wonder how the mozAddonManager API itself is tested in Firefox?

**Comment by ghost** [comment]
@6a68 for researching this on Monday

**Comment by jaredhirsch** [comment]
OK, I did a little digging into integration / unit testing and `navigator.mozAddonManager`. Here's what I've got so far. Comments / questions very welcome.

### what is a `mozAddonManager`, anyway?

It [looks like](https://dxr.mozilla.org/mozilla-central/source/dom/webidl/AddonManager.webidl#59) the `navigator.mozAddonManager` WebIDL just exposes a subset of the existing `AddonManager` API to whitelisted websites. Side note, [this C++ code](https://dxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/AddonManagerWebAPI.cpp) seems to make the decision about whether to expose the API or not; notice test pilot is whitelisted in there.

### integration tests using `mozAddonManager`

Since `mozAddonManager` is just a layer exposing an existing API to web content, our current integration test, which calls the `AddonManager` API via the `marionette_driver.addons` module, still tests the right behavior, it just calls the API at one level lower than websites would.

[Here](https://dxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/test/browser/browser_webapi_install.js#40) is a Firefox test that actually reaches over into the content process and calls `mozAddonManager` directly; I bet we could do something similar to update our integration test.

### unit testing `mozAddonManager` from regular (non-addon) JS

I think it should be pretty straightforward to mock out `navigator.mozAddonManager` for unit testing our non-addon JS. We'll just need to cover the [AddonManager.webidl](https://dxr.mozilla.org/mozilla-central/source/dom/webidl/AddonManager.webidl) API, and use promises (or sinon's fake timers) to simulate its async behavior. Sinon should be up to the task.

### unit testing `mozAddonManager` from addon JS

Any addon code that needs test calls to `mozAddonManager` can load (or mock) `resource://gre/modules/AddonManager.jsm` directly, I think.

### porting the integration tests from Python to JS:

Since test pilot is now wholly written in JS, and since the other tests are in JS, it might be nice to have integration tests also written in JS.

I looked into the JS Marionette client, but it's been abandoned, along with much of the other FxOS-era tooling.

However, it turns out there's a thing called [geckodriver](https://github.com/mozilla/geckodriver/), which can run regular selenium webdriver tests, and supports privileged Gecko calls by proxying the calls to the chrome process. It's written in Rust, which isn't supported by CircleCI, but if we can download a binary, [this example](https://github.com/SeleniumHQ/selenium/blob/master/.travis.yml#L86) shows how we could fetch a prebuilt geckodriver to run our integration tests. This is relevant because there is a JS webdriver API ([see the API docs](http://seleniumhq.github.io/selenium/docs/api/javascript/)), available via `npm install selenium-webdriver`. Thus, if we wanted to move the integration tests to JS, we could do it using the `selenium-webdriver` and `geckodriver`. I'm not sure if this is worth it or not.

### next steps

Here's a sketch of next steps:
- update our Python integration test to call `mozAddonManager` instead of `AddonManager`
- add unit tests for addon installation for both the addon and React code
- ask the team for input on JS vs Py for integration tests

Once we reach consensus about whether to go Python or JS for integration tests, I'll add another integration test for experiment page installs (#1257).

**Comment by dannycoates** [comment]
Awesome comment @6a68!

I really _want_ to take the js route in the long run. It seems like the riskier path though. As someone who's never used marionette I have no idea what to expect either way, but python seems to be the more well worn path.

Ultimately I want to use the thing that requires the least maintenance because maintaining integration tests is like my third least favorite thing to do 🌵

**Comment by jaredhirsch** [comment]
Thanks for the feedback, @dannycoates. I'm rapidly running out of time, so it'll be Python for now ;-)

To Les's original question, we should be able to mock out browser APIs by assigning stuff (like `navigator.mozAddonManager` to the jsdom window. And we should be able to mock out addon-browser message passing by firing / listening for CustomEvents.

**Comment by lmorchard** [comment]
Well, my question was about mocking up for unit tests - I'd still like to see us use the real APIs for integration testing. We've had some unexpected interactions at times when tests passed, but the tests missed some quirk of the real API. Might be overkill, but I'm super paranoid about things not working the way we thought they did, at this point.

Maybe for add-on installation we can get away with inside-out unit tests with mocks, versus outside-in integration tests that drive the browser? Kind of want both as a belt-and-suspenders thing though, but maybe my notion of integration tests is made redundant by our human QA folks?

**Comment by jaredhirsch** [comment]
Sorry, I could have been clearer in my comment above. I actually _was_ thinking unit tests (really big unit tests) when I mentioned adding navigator.mozAddonManager to the window object created by jsdom.

For example, if we want to unit test how the React app handles addon install failures, we'd create a fake CustomEvent('from-addon-to-web') with the install failure message inside. After mozAddonManager gets called, fire that fake event on the DOM, and check that the React app's state is updated to an addon install error state. We could also get more granular and just test the code that listens for those events and updates the state machine.

**Comment by ghost** [comment]
Related to #2275.  @6a68 is this still needs:discussion?

**Comment by chuckharmston** [comment]
We have a nice suite of integration tests, closing this.
