### ISSUE TITLE
Figure out L10n for YAML flat file content

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#1340]
Moving to flat files & static site generation, we have content in YAML that we want localized. What do?

Here's an idea:
- Take the filename and property names in YAML as L10N string ID prefixes
- Hash the string content, use that as L10N string ID suffix
- Generate an en-us .ftl file from the YAML content files using those L10N string IDs
- Use those L10N string IDs in HTML page content, both in client-side React and static site generation.

So, for example:
- `content-src/experiments/activity-stream.yaml` has a `title` property with content "Activity Stream"
- the L10N string ID for that could be `activity-stream-title-bc6494e4f9589713c63fc6671e19ecd2`
- generate `.ftl` using that string ID
- include that string ID in `data-l10n-id` in markup (not sure how)

The idea here is that we have L10N IDs that naturally change when content changes, so that localizers using Pontoon see when there are new strings that need translation. That is, say the title changes to "Activity Stream is Awesome" - the L10N ID changes to `activity-stream-title-4a490ec33f2887a662f7c31ab29edec7`

Better ideas are totally welcome!

**Comment by chuckharmston** [comment]
> The idea here is that we have L10N IDs that naturally change when content changes

There may be times when we may want to change the `en-US` wording, but the meaning doesn't significantly change. If we do automated hashing of the content, we lose the ability to be judicious about when we do and do not need changes in localization, and if we're localized across a bunch of languages, there's a significant penalty to that, especially since it's community work we'd be invalidating. I think I'd prefer us to manually exercise judgement.

**Comment by lmorchard** [comment]
> I think I'd prefer us to manually exercise judgement.

Definitely a good point. What would that look like, technically speaking? I'm hoping to find some way of coming up with IDs that doesn't involve manually handcrafting them for every string in every experiment.

Off the top of my head, I have this terrible idea: Every YAML string can also be an array - `[1, "String"]` where the `1` is a manually chosen unique ID and `"String"` is the string. Plain strings use a content hash as ID, arrays use the manual ID. 

Maybe we copy/paste the old content hash and use that in the array when we want to tweak wording without signifying a change in meaning? Or, we punt on hashing altogether, and all plain strings just use a "0" as revision and we have to manually bump for _every_ string edit.

Not sure I like this idea much - is there something better?

**Comment by chuckharmston** [comment]
> What would that look like, technically speaking?

We update the l10n IDs manually when we feel that the meaning changes sufficiently to warrant a relocalization, rather than relying on the hash to doing it for us.

I'm not sure how applicable this is to what you're considering, but in my early attempts at this problem, I generated the l10n IDs from a unique identifier for the page (e.g. [data definition](https://github.com/chuckharmston/testpilot-flatfiles/blob/master/source/_experiments/tab-center.html#L2), [markup](https://github.com/chuckharmston/testpilot-flatfiles/blob/master/source/_layouts/experiment.html#L5)).

**Comment by lmorchard** [comment]
Also, it occurs to me if tweak wording without changing meaning is the most common case, we could do something more like this:

``` yaml
title: "Activity Stream"
```

That yields an l10n-id of `activity-stream-title` by default. Later, we change it to this:

``` yaml
title: "Doing Stuff Centre"
title_l10n_id: "2016-09-12"
```

Which yields an l10n-id of `activity-stream-title-2016-09-12` with the manual suffix. The date isn't significant, it could be `branding-change-centre` or whatever.

**Comment by chuckharmston** [comment]
# r+ :shipit:

**Comment by chuckharmston** [comment]
Added this to [TXP-15](https://github.com/mozilla/testpilot/projects/9), am taking it and will try to finish it this sprint.

**Comment by chuckharmston** [comment]
Adding `needs:qa`, since there's a pretty large regression risk here.

SV team: all the English-language experiment content is now coming from a [generated localization file](https://testpilot.dev.mozaws.net/static/locales/en-US/experiments.ftl), rather than directly from the YAML. If there are any misgenerated IDs, the expected text content will by replaced with a string that looks something like `universalsearchContributors0Title`. Please make sure that this doesn't happen. Thanks!
