### ISSUE TITLE
Use mozAddonManager in more places.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1344]
Now that #1223 has been closed, we should investigate other ways we can use `mozAddonManager` to improve our UX and simplify our code. Some ideas:
- Remove the need to discretely install the Test Pilot add-on (#1331).
- Uninstall the Test Pilot add-on from the website.
- Installing and uninstalling experiments.
- Detect incompatible or conflicting add-ons (#944)

Ultimately, this should allow us to wholly replace the `WebChannel` that allows our add-on to talk to our website.

**Comment by johngruen** [comment]
In a holding pattern until #1347 is resolved

**Comment by chuckharmston** [comment]
- Detect when the add-on is disabled, and prompt the user to enable it.

**Comment by ghost** [comment]
Related to #2275

**Comment by ghost** [comment]
Marking this as needs:product in triage although it sounds very close to ready.  #2275 will tell us if we can just go ahead and enable this everywhere (and it sounds like we can from our talk).

**Comment by fzzzy** [comment]
Most of the bullet points in this issue are now closed. The test pilot add-on and an experiment can now be installed with one click, it is possible to uninstall test pilot from the website now, we use mozAddonManager for installing and uninstalling experiments now, and I think we have the capability to detect conflicting add-ons now. Also due to the mozAddonManager branch https://github.com/mozilla/testpilot/pull/2360 if an experiment is disabled in the add-on manager, the normal "enable" button will be shown and will just work to enable the experiment.

There is still an outstanding bug when test pilot is disabled in the add-on manager and we try to install the test pilot add-on: https://github.com/mozilla/testpilot/issues/2331

There's also a bug to inform the user that they need to do something to use mozAddonManager that needs to land before we fully remove the `WebChannel` path: https://github.com/mozilla/testpilot/issues/2364
