### ISSUE TITLE
Remove pontoon.js from production instance

### ISSUE THREAD

**Issue by mathjazz** [mozilla/testpilot#1356]
The [pontoon.js](https://developer.mozilla.org/en-US/docs/Implementing_Pontoon_Mozilla) script is required to allow in-page localization of Test Pilot with [Pontoon](https://pontoon.mozilla.org/).

It only has to be loaded in the environment that is used for in-page localization, e.g. staging server. You can remove it from the production instance.

**Comment by lmorchard** [comment]
Hmm, we might have to look into how to do that - we don't have separate dev / stage / prod builds, they're all the same except for maybe a few per-environment configuration settings

**Comment by chuckharmston** [comment]
@lmorchard Webpack will let us do that :)

**Comment by lmorchard** [comment]
Well, so can gulp, if we want to make per-environment builds. It's just that we intentionally don't do that - in part to be sure there are no differences between environments, because differences mean surprises. In part, that's also an artifact of the single Docker image we build & test & ship around. We could probably do this differently post-static-deployment
