### ISSUE TITLE
Consider separating containers from components

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1364]
It's a common practice for React apps to separate components into two directories: `containers` for anything handed off to a `Route`, and `components` for everything else. We should consider doing this.

**Comment by lmorchard** [comment]
We have containers for a few components in the router - do you mean that _all_ the "pages" should be container components? I skipped a bunch, because they're basically just stateless content. But that is admittedly inconsistent.

I was also trying to figure out if maybe we could do it in the _other_ direction - that is, one App container wrapping the router that passes all the store selector & dispatch props down to page components. Haven't been able to figure that one out though, maybe it's not a good practice?
