### ISSUE TITLE
Use constants for action names

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1371]
Rather than use magic string names for action names, we should use and exports constants, e.g.

```
 export default createActions(
   {},
   'setHasAddon', 'setInstalled', 'setClientUuid',
 ); 
```

vs

```
export const ADDON_SET_INSTALL_STATUS = 'setHasAddon';
export const ADDON_SET_INSTALLED = 'setInstalled';
export const ADDON_SET_CLIENT_UUID = 'setclientUuid

export default createActions(
  {},
  ADDON_SET_INSTALL_STATUS, ADDON_SET_INSTALLED, ADDON_SET_CLIENT_UUID
);
```

**Comment by lmorchard** [comment]
I was kind of torn on using constants. It seemed like redundant boilerplate, because the action names can also just be the names of the <strike>action creator</strike> reducer functions. 

That said, `createActions` will automagically turn snake-case constants to camel-case names - `ADDON_SET_INSTALL_STATUS` can become `addonSetInstallStatus`. Neat, but I didn't like the implied magic.

**Comment by ckprice** [comment]
Closing.
