### ISSUE TITLE
Insturment the restart-required flows when using mozAddonManager

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1375]
Breaking out of #1360.

My suggestion from that thread:

> - Event: user sees CTA
>   - Dimension: is user on homepage or experiment detail page?
>   - Dimension: can user use `mozAddonManager`?
> - Event: user clicks install button
>   - Dimension: is restart required?
> - Event: user shown "must restart" modal.
> - Event: add-on opens homepage after restart
>   - We'd want `utm_`s for this.
> 
> This should let us segment different pathways as they're fed into existing funnels to measure the effect on conversion rates. Plus, we would have absolute numbers to pair with the conversion rates to serve as a basis for speculation of how many users we lost in each step.

CC @ckprice

**Comment by ckprice** [comment]
I think we are okay with adding/updating 3 pings here. (/cc @garethcull)

## ~~Indicate if a user will require a restart after he or she installs Test Pilot.~~

~~If we set [a custom dimension with the `pageview`](https://github.com/mozilla/testpilot/blob/master/docs/metrics/ga.md#custom-dimensions), it will remain with the user for their entire session and we can link back to it on any subsequent events.~~

~~If possible, can we send `dimension7: {0,1}` to  be sent with the pageview on either the home page or experiment detail pages? I know that `pageview` sends aren't in place yet (#1346).~~

## When a clicks on the "Install add-on" button, indicate if the user will require a restart.

**Note**: this will only be needed if we cannot instrument `pageview` sends. If we go this route, I will update #1346 with a cleanup note.

This is what [the current event](https://github.com/mozilla/testpilot/blob/74875824b9c4e4f20da810bda588196c8cdb8452/frontend/src/app/lib/addon.js#L42) looks like.

```
const gaEvent = {
    eventCategory: eventCategory,
    eventAction: 'button click',
    eventLabel: 'Install the Add-on'
};
```

There's a few options here, we could 1) add [`eventValue`](https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#eventValue) to the ping and send a 0 or 1 to indicate if a restart is required ~~(requires a small addition to the ga event)~~. 2) move _Install the Add-on_ to the `eventAction` and indicate in the label if a restart is required. 3) update `eventLabel` to read _Install the Add-on (restart required)_ if a restart is required.

~~Unless there are objections, I would go with 3 as it will require the least amount of work to update dashboards downstream (/cc @garethcull), while still giving us the information we need.~~
/edit looking at the event again, since we wouldn't really need to change any code, I think we should go with Option 1, and send the 0 or 1 through the `eventValue` field.

New event

```
const gaEvent = {
    eventCategory: eventCategory,
    eventAction: 'button click',
    eventLabel: 'Install the Add-on',
    eventValue: {0,1} //0=restart is not required, 1=restart required
};
```

## Create an event when a user views the `must restart` modal.

I'm assuming this isn't considered a 'page' or else we'd use a `pageview` hit type instead of `event`.

```
const gaEvent = {
    eventCategory: 'PostInstall Interactions',
    eventAction: 'view modal',
    eventLabel: 'restart required'
};
```

## If a user has restarted because of installing Test Pilot, make sure we are able to measure the traffic back to the homepage after the add-on automatically sends.

Referencing our [Table of Tags](https://github.com/mozilla/testpilot/blob/master/docs/metrics/ga.md#table-of-tags).

| Description | utm_source | utm_medium | utm_campaign | utm_content |
| --- | --- | --- | --- | --- |
| User hits home page after being sent by the add-on after installation. | testpilot-addon | firefox-browser | restart-required |  |

Please update the docs.

**Comment by chuckharmston** [comment]
> If possible, can we send dimension7: {0,1} to be sent with the pageview on either the home page or experiment detail pages?

Unfortunately, that's not possible. We can only know this after the install has finished.

**Comment by chuckharmston** [comment]
Implemented the `utm_` tags for the opened tab here: https://github.com/mozilla/testpilot/pull/1379
