### ISSUE TITLE
Addon panel not fully visible on lower res screens

### ISSUE THREAD

**Issue by dannycoates** [mozilla/testpilot#1412]
<img width="1024" alt="screen shot 2016-09-22 at 6 14 48 pm" src="https://cloud.githubusercontent.com/assets/87619/18771086/d391777e-80f0-11e6-8839-436dfbdce5ee.png">

At 1024x640 "View All Experiments" isn't visible and there's no scrolling.

**Comment by dannycoates** [comment]
I added some scrolling...
![foo](https://cloud.githubusercontent.com/assets/87619/18774112/a11b48be-810a-11e6-99b3-5d2c2a1b2694.gif)

**Comment by sevaan** [comment]
Looks great, Danny! +r

On Fri, Sep 23, 2016 at 12:23 AM Danny Coates

<
mailto:Danny Coates notifications@github.com

> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

I added some scrolling...
https://cloud.githubusercontent.com/assets/87619/18774112/a11b48be-810a-11e6-99b3-5d2c2a1b2694.gif

—

You are receiving this because you were assigned.

Reply to this email directly,
https://github.com/mozilla/testpilot/issues/1412#issuecomment-249099759
, or
