### ISSUE TITLE
Unable to enable either Universal Search or Activity Stream

### ISSUE THREAD

**Issue by sillyess** [mozilla/testpilot#1459]
I have been using Test Pilot for almost two months now. I have The Tab Center enabled and I love it. I have tried repeatedly to enable both Universal Search and Activity Stream but I keep getting a message that they are unable to be enabled and to try again later. Literally thousands of people have begun using each of these features since I began to experience this problem. What can be done to let me enable both of these features?
I use Windows 10. I'm not sure what Firefox build I'm currently using.

Please respond as soon as possible. My email address is suemeyer50@gmail.com. Thank you.

**Comment by chuckharmston** [comment]
@sillyess Sorry to hear that you're having trouble!

We've had a few different reports of this, and each time it's been resolved by disabling firewalls or antivirus software. It's hard to provide more specific advice, since the behavior of those things can vary pretty drastically from one place to another, but that would be a good place to start.

I'm going to close this bug, but if you need more technical support, our Discourse forums would be a great place to start: https://discourse.mozilla-community.org/c/test-pilot

Thanks for the report!
