### ISSUE TITLE
Send the `clientUUID` in the URL to SurveyGizmo

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1461]
Request from rrayborn

> While I wasn't actively involved with the discussion, it's my understanding that there was talk of passing the user's UUID into SG earlier on in the TxP project for later correlations.
> 
> My team is still interested in this and it would be a good test for potential similar experiments in Firefox desktop.  Would this be something that we could try?  Is there an existing bug that I'm not aware of?

**Comment by lmorchard** [comment]
I thought in earlier discussions we decided that we absolutely didn't want to send the Test Pilot clientUUID out for privacy reasons. In fact, we want to get rid of that clientUUID generation altogether - we were only using it to count unique install/uninstall in the Django API that we just recently switched away from.

Instead we wanted to send things to Telemetry with the existing survey ID in that system in #949. Telemetry has its own private client ID that we never see or access, but that gets used in correlations there.

**Comment by ckprice** [comment]
#949 has a couple suggestions, one is incorporating the "unique response ID that is generated at the time of creation" (not the static survey ID) to Telemetry (is implementing this reasonable?). The other is sending a UUID to the survey URL (which is this bug, and rrayborn's follow-up request).

FWIW we're already sending the `clientUUID` in #1359.

**Comment by chuckharmston** [comment]
We are also using `clientUUID` to ensure that users are consistently placed in the same group [in variant tests](https://github.com/mozilla/testpilot/blob/master/addon/lib/metrics.js#L43).

**Comment by MattGrimes** [comment]
Any progress on this? This is a critical component in understanding our users.

**Comment by chuckharmston** [comment]
@johngruen we'll need a product call on moving forward with `clientUUID` here; this will more-or-less make us all-in on using it.

**Comment by johngruen** [comment]
@MattGrimes could you spell out a specific use case here. Since we're already sending UUIDs to GA, I see no reason why we can't do the same to another service already vetted by our legal team  (/edit by ckprice -- this was approved by legal).

That having been said, I'd like to have more concrete examples of the types of correlations @rrayborn is referring to above.

**Comment by ckprice** [comment]
This was approved by legal via email last week.

**Comment by ckprice** [comment]
Looks like a pretty [simple addition to here](https://github.com/mozilla/testpilot/blob/e118f485bcc60a5ccbb16b49714c3a6b0ed439cf/addon/lib/survey.js#L122). Will take this.

**Comment by MattGrimes** [comment]
Sure. 
- For upcoming studies like Page Shot, we could look at users that say they derive more utility out of Firefox because of Page Shot to find out if that correlates to an increase in usage hours. 
- As we incorporate more experiments with partners we can look at brand effects to find out if that correlates with a drop in usage hours or retention. 
- Tab Center users that say they are using more tabs now than before may only FEEL like they are. If they feel like they are using more tabs, but that equals increased usage hours, that might be a good thing. 
- Tracking Protection may make users report they feel safer online which might correlate to increased usage hours. Reporting that tracking breaks websites x,y,z might do the opposite.

@rjweiss has a list as well

**Comment by chuckharmston** [comment]
(We wouldn't not do this bug if we chose not to use `clientUUID`; we'd just generate a GUID or something like that instead.)

**Comment by MattGrimes** [comment]
I am fine with whatever implementation you choose. It's the outcomes we care about. You folks are the experts.

**Comment by ckprice** [comment]
Yeah, not sure why we'd create a new variable. As noted above the use of `clientUUID` has been approved by legal, and we're already sending it to GA via the measurement protocol. I'm going to proceed using it.
