### ISSUE TITLE
Experiments in door-hanger should be sorted by Enabled > New > rest

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1472]
![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/18926036/0d61b508-856b-11e6-9a85-a9308efebe7a.png)

Currently my door-hanger looks like this:

![firefox_test_pilot_-_universal_search_and_penicillin_-_wikipedia__the_free_encyclopedia_and_in_yaml__how_do_i_break_a_string_over_multiple_lines__-_stack_overflow](https://cloud.githubusercontent.com/assets/557895/18926006/f3114d94-856a-11e6-848c-d60adb1106af.png)

What you _can't_ see is that I also have Universal Search installed.
I think it'd be super duper if my doorhanger add-ons were maybe listed by:
- Things I currently have installed.
- Things that are new/updated (but not installed).
- Everything else (alphabetically?).

**Comment by lmorchard** [comment]
We do have sorting, here: https://github.com/mozilla/testpilot/blob/master/addon/lib/toolbar-button.js#L72

Basically, it goes new first and then everything else in reverse last-modified order. We wanted new first, in order to get attention. But, enabled / disabled state doesn't currently figure into in the sort

**Comment by johngruen** [comment]
Doorhanger's gone, @pdehaan
