### ISSUE TITLE
Check if /onboarding is already open in a tab before opening a new one?

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#1475]
Every time the add-on is re-installed, a new tab with /onboarding is opened. This is annoying during development where installation issues are involved. 

We should check and see if /onboarding for the current env is open in any tab, and skip opening a new one if so.

**Comment by SoftVision-PaulOiegas** [comment]
I've talked with you guys about this a while ago because it s always displayed no matter how many times you install TP. But the discussion result was that we don't keep any info on the user PC to know that TP was previously installed.
I don't think that if we check that one is already open will help to much. The users won't install the add-on as many times as us and probably they close the onboarding page as soon as it's opened. 
Can't we do something more general for this ?

**Comment by lmorchard** [comment]
I filed this issue specifically as a dev papercut - just for annoying things during development. Not meant to be a more general issue. We _can_ detect if a tab is currently open, which happens often in development after many cycles of install/uninstall. 

We can't detect previous installations if we delete all our data on uninstall. But I think that's something we _should_ do, because we _should_ completely clean up after ourselves on uninstall. So, we can't solve for that more general case.

**Comment by johngruen** [comment]
I think we can close this b/c we killed the onboarding tab.
