### ISSUE TITLE
Consider adding install buttons for individal experiments @ https://testpilot.firefox.com/experiments/

### ISSUE THREAD

**Issue by krupa** [mozilla/testpilot#1489]
## steps to reproduce:
1. Load https://testpilot.firefox.com/experiments/
2. Notice all the experiments listed. Note that you have to navigate to the individual experiment's details page to enable it.
## expected behavior:

The number of clicks required for the user to install a new feature is kept to a minimum. User should still be able to navigate to the details page but should also be provided an option to install it without having to navigate to another page (basically a tl;dr install option)
## actual behavior:

The user has to navigate to the details page to install the feature.

**Comment by pdehaan** [comment]
Possibly related #1525

**Comment by johngruen** [comment]
@chenmorpheus and I will dust this off

**Comment by ChenMorpheus** [comment]
From UX perspective, I would like to share some of my thoughts. Long story short, my conclusion tends not to provide the install button in experiment card. Here are my reasons:

1. Test Pilot collects data from users. As a result, we should allow users have the chance to access the privacy section.

2. AMO provides various extensions, which means users can easily find alternatives. That causes the high demand to decrease the clicks as many as possible to install an extension. Test Pilot seems like AMO, a platform of many extensions. However, we control the number of experiments to assure we get enough resources to test and improve. That's why I don't want users to enable the experiment without knowing what we do.

3. Too much information in a small card might be too overwhelming. Since there is too much information to elaborate an experiment, I would suggest providing the crucial information on the card and introduce further details on the detail page.

I'm happy to hear other thoughts.

**Comment by johngruen** [comment]
We have this now with feature experiments
