### ISSUE TITLE
Uh oh. ⁨Min Vid⁩ could not be enabled. Try again later.

### ISSUE THREAD

**Issue by Jokubasdk** [mozilla/testpilot#1527]
I am trying to enable the new addons but i keep getting this error: "Uh oh. ⁨Min Vid⁩ could not be enabled. Try again later." (I get this error for Page Shot, Min Vid, Tracking Protection and No More 404s. The others seem to work fine)
Does anyone now how to solve this?

**Comment by SoftVision-PaulOiegas** [comment]
@Jokubasdk  Hi and thanks for the report. Can you tell me from "about:addons" page what version of Test Pilot add-on do you have installed ? This could be due to an older version that was having troubles with new experiments installation,

Also, we are having some issues with some antivirus clients that are currently under investigation. Are you using any ? If yes, as a temporary workaround, you could try to temporarily disable it and after install the Min Vid experiment.  

Please let me know if one of the above was the cause and if the antivirus is causing this, what client are you using so we can debug this.

**Comment by ghost** [comment]
tracking this at #1474
