### ISSUE TITLE
Share function

### ISSUE THREAD

**Issue by jerry550** [mozilla/testpilot#1561]
The Yahoo Mail form in the Share function doesn't send. Macbook Pro Macos Sierra.

Thank you for contributing to Test Pilot!

Please use this form to report Test Pilot specific issues. If you think you've found an issue with one of the experiment add-ons, please file an issue in the appropriate repo below:
- Activity Stream:      https://github.com/mozilla/activity-stream/issues/new
- Tab Center:           https://github.com/bwinton/VerticalTabs/issues/new
- Universal Search:     https://github.com/mozilla/universal-search/issues/new
- No More 404s:         https://github.com/internetarchive/FirefoxNoMore404s/issues
- Page Shot:            https://github.com/mozilla-services/pageshot/issues/new
- Min Vid:              https://github.com/meandavejustice/min-vid/issues/new
- Tracking Protection:  https://github.com/mozilla/blok/issues/new

**Comment by SoftVision-CosminMuntean** [comment]
Hi @jerry550 , thanks for reporting this.

I can confirm this issue but it seams this a general Firefox issue not a Test Pilot one. Managed to reproduce it using both the Yahoo Mail service from "Share this page" Firefox functionality and also from the Activity Stream "Share" functionality. And this is reproducible from any page you attempt to share trough Yahoo service. 
However, this issue is already logged in Bugzilla, here is the link: https://goo.gl/ztRpld. You can follow the progress there so I'm closing this.

**Comment by jerry550** [comment]
Thank you.
