### ISSUE TITLE
Private Window Issue

### ISSUE THREAD

**Issue by KronicSeattle** [mozilla/testpilot#1607]
After installing test pilot with "tab" add-on installed...

If I try to open a new private window using context menu, Window opens, begins to load and then freezes.
This is true each time UNLESS I have a normal window open first.

[PC HardwareDtls.txt](https://github.com/mozilla/testpilot/files/527966/PC.HardwareDtls.txt)

**Comment by SoftVision-PaulOiegas** [comment]
Hi @KronicSeattle , Thanks for reporting this, but can you please detail exactly what steps you are performing (maybe add a screen recording) ? I'm trying to reproduce this. 
You just close the normal window after you open a private one, and this reproduces after you open a second link in a private window from context menu ? 
Or you are starting the browser directly in private window (-private-window command) and after you install Test Pilot and Tab Center ?

I'm asking this because I haven't managed to reproduce it with closing the normal window before opening a link in another private one from context menu. And if I start the browser in private window directly, the Tab Center add-on just crashes right after install. Which might be a known issue since most of the experiments shouldn't work in private windows...

**Comment by KronicSeattle** [comment]
Open windows desktop
Right click on mozilla icon in taskbar
Select new private window

Window opens but never fully loads.

Bryan

**Comment by SoftVision-PaulOiegas** [comment]
Yep, I thought so that this was the problem. Tab Center and almost all experiments are not compatible with Private Window. At least not for the moment. So, not sure what we can do here, maybe just find a way to disable Tab Center while in Private Window mode.
However, you can follow the issue progress here https://github.com/bwinton/TabCenter/issues/675. I already launched a question there for your issue.

@wresuolc I'm not sure I should close this yet, can we do something on our side or it's entirely a Tab Center issue ?

**Comment by ghost** [comment]
I think it should be up to the experiments.  Thanks for filing.
