### ISSUE TITLE
Session Restore issue

### ISSUE THREAD

**Issue by JohnA-S** [mozilla/testpilot#1623]
Nearly every time I close Firefox (correctly), it reopens with a "restore session" option tab. I haven't lost my tabs yet, but I'm concerned I will. Now, I do have nearly a hundred tabs open. :)

Windows 10
Firefox Pilot

**Comment by chuckharmston** [comment]
Thanks for the report, @JohnA-S!

Why do you think Test Pilot is responsible for this one? As far as I know, neither Test PIlot nor any of its experiments do anything with session restore.

**Comment by JohnA-S** [comment]
Thank you for your response, @chuckharmston. 

I'm not sure it's an issue with system restore necessarily. It seems to me it's an issue with handling tabs at shutdown. I believe this is an issue with Test Pilot because it began happening immediately after switching to Test Pilot. Naturally, system restore has come up in the past but only a few times in the years I've used Firefox but now it's happening every day.

**Comment by SoftVision-PaulOiegas** [comment]
If you have any other experiments installed beside Test Pilot, you could try to navigate to "about:addons" page at extensions section and disable them one by one. And after each disable restart the browser to see if it still occurs. Maybe one of the experiments messes this up. If the experiments are not the problem, then try to disable Test Pilot. 

Also you could try this with a new Firefox profile. Maybe some of the add-ons / custom settings you have, enter in conflict with Test Pilot or experiments from it. Then we would like to now which one and see if we can correct this.

**Comment by ghost** [comment]
@matt_g is this a SHIELD thing?

**Comment by chuckharmston** [comment]
@mattgrimes

**Comment by MattGrimes** [comment]
We have not deployed any Shield Studies that manipulate session restore. There was talk about that a few months ago, but nothing has materialized.

**Comment by jaredhirsch** [comment]
@JohnA-S Hey, could you let us know what other addons you have installed? That way we can try to reproduce the bug.

**Comment by JohnA-S** [comment]
Thank you all for being so on top of this issue. I've systematically gone through and disabled addons to see if any one particular one makes a difference. No single one stood out strongly. By the time Firefox Pilot was the only addon running, I was having less crashes/system restore issues but the browser became progressively slower and struggled more with any request. This was definitely the browser as all other programs would be working fine. When I finally disabled Pilot, the browser became practically unusable for nearly two hours. Or at least that's how long it took to get it shut down. I've been restarting after disabling addons. With everything disabled, the browser is back to normal. Also, without any addons, the browser completely shuts down in a couple seconds. Before removing Pilot and other addons, the browser was taking a lot longer to shutdown in the background after the visible windows disappeared. How would you recommend I move forward in a way that would give you the best info? Should I start re-enabling addons? If so, start with Pilot? Attached is an image showing the addons I've used. Most of them were enabled at the install of Pilot. 
![firefoxaddons10-31-16](https://cloud.githubusercontent.com/assets/6799550/19861470/e496e5fa-9f49-11e6-8c89-3a4fed419e80.jpg)

**Comment by SoftVision-PaulOiegas** [comment]
Hmmm... lots of add-ons, let's change a bit the approach. I would recommend you to create a new Firefox profile and after try installing the Test Pilot add-on and other experiments. Maybe you have some profile settings altered by the installed add-ons that make even your normal browsing experience crappy. Since you said that even with all disabled you were having problems. 
If Test Pilot and experiments will run ok after this, then probably some custom settings you have on the current profile or one of the add-ons you have is messing things up.
Here is a guide for creating a new profile, if needed -  https://goo.gl/PNe90E

**Comment by ghost** [comment]
This is likely a conflict between add-ons.  (Off the top I see Tab Groups and Tab Center installed -- tab center doesn't work well with other Tab add-ons for the most part).  As Paul suggested, I'd trim back to only the add-ons you really need and enable them one at a time.

Since it's a couple months old with no reply (and no one else reproducing) I'm going to close this.  Thanks.
