### ISSUE TITLE
Document elastic beanstalk prod instructions

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#165]
The cool EB stuff in pull #143 could use some documentation.

Would be great to either put docs in README.md or maybe a DEPLOYMENT.md (if it's a lot of context).

**Comment by lmorchard** [comment]
No documentation yet, because we don't know exactly how it's going to work yet and will probably change :) #143 is a start, but needs refinement after contact with ops machinery.

But, I should have had a quick HOWTO in PR #143. Goes something like this:

```
# Change env var settings in 00-environment.config 
cp .ebextensions/00-environment.config-dist .ebextensions/00-environment.config
vim .ebextensions/00-environment.config

# Ensure you're locally auth'd to Docker Hub
docker login

# Build the server Docker image, upload it to Docker Hub, create an EB app bundle
./bin/build-prod.sh docker.io/YOUR_DOCKER_HUB_USERNAME_HERE/idea-town:latest
```

This will leave you with a fresh server image uploaded to Docker Hub, and a new Elastic Beanstalk .zip app bundle under `build/`. 

The rest happens via the AWS web console:
- Click on [Elastic Beanstalk](https://us-west-2.console.aws.amazon.com/elasticbeanstalk/home?region=us-west-2#/applications?applicationNameFilter=)
- Click "[Create New Application](https://us-west-2.console.aws.amazon.com/elasticbeanstalk/home?region=us-west-2#/newApplication)" in upper right
- Fill out a unique name & description, click next.
- Click "Create web server" button
- On Environment Type, pick predefined configuration "Docker" & environment type "Single instance". Click next.
- On Application Version, pick "Upload Your Own" and select the latest .zip file under `build/` in your project directory. Click next.
- On Environment Information, fill out a unique name & URL. The defaults are probably fine. Click next.
- On Additional Resources, _be sure to check "Create an RDS DB Instance with this environment"_. Click next.
- On Configuration Details, the defaults are fine. _You'll want to have an EC2 key pair available & selected if you want to ssh into the box later._
- On Environment Tags, just click next.
- On RDS configuration, pick DB engine "postgres" and use the default version (9.4.4). Fill in a unique username & password - you'll need them yourself for accessing the DB later, but [the Django will get configured via env vars as long as there's an `RDS_DATABASE_TYPE` set to `postgres` in `00-environment.config`](https://github.com/mozilla/idea-town/blob/master/idea_town/settings.py#L141). Click next.
- On Permissions, just click next.
- On Review, click Launch.
- Wait a long while & watch the events as things are automagically set up. EB will pull the image down from Docker Hub and create the EC2 instance & RDS database & all the rest.

To deploy updates, you can run `bin/build-prod.sh` again and upload the new .zip bundle from the front page of your application. You won't need to run through the whole EB wizard again.

For real deployment, all the manual steps in the web console will be automated. Also, I'm guessing many of the defaults I picked will need tuning.

**Comment by lmorchard** [comment]
Closing this, since we're moving away from production elastic beanstalk
