### ISSUE TITLE
Privately submit to AMO

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#172]
<a href="https://github.com/6a68"><img src="https://avatars.githubusercontent.com/u/96396?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [6a68](https://github.com/6a68)**
_Thursday Sep 10, 2015 at 18:35 GMT_
_Originally opened as https://github.com/mozilla/idea-town-addon/issues/19_

---
- Ensure addon passes auto-signing checks
- Get a real install link for testing

**Comment by meandavejustice** [comment]
<a href="https://github.com/meandavejustice"><img src="https://avatars.githubusercontent.com/u/1844554?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [meandavejustice](https://github.com/meandavejustice)**
_Thursday Sep 10, 2015 at 19:03 GMT_

---

Submitted, awaiting review.

**Comment by meandavejustice** [comment]
<a href="https://github.com/6a68"><img src="https://avatars.githubusercontent.com/u/96396?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [6a68](https://github.com/6a68)**
_Tuesday Sep 15, 2015 at 21:52 GMT_

---

I submitted this to AMO today and got around 200 warnings (due mostly to `setTimeout` and `setInterval` calls inside node_modules), and the addon did not qualify for auto-signing.

I'm not sure what, if anything, can be done about the automatic code scanner looking through all the dependencies. We need to look into this, and figure out a release, rollback, update process that works within the review constraints (which could mean 6 weeks between updates).

**Comment by meandavejustice** [comment]
<a href="https://github.com/6a68"><img src="https://avatars.githubusercontent.com/u/96396?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [6a68](https://github.com/6a68)**
_Tuesday Sep 15, 2015 at 21:54 GMT_

---

I'll look into what the go-faster folks are planning to do about addon signing, maybe that could be an option.

**Comment by meandavejustice** [comment]
<a href="https://github.com/6a68"><img src="https://avatars.githubusercontent.com/u/96396?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [6a68](https://github.com/6a68)**
_Tuesday Sep 15, 2015 at 22:22 GMT_

---

Aha, the addon does qualify for auto-signing. The underlying problem was the `.jpmignore` configuration, see this issue: https://github.com/mozilla-jetpack/jpm/issues/298

I'll open a PR with the `.jpmignore` changes.

**Comment by meandavejustice** [comment]
<a href="https://github.com/6a68"><img src="https://avatars.githubusercontent.com/u/96396?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [6a68](https://github.com/6a68)**
_Tuesday Sep 15, 2015 at 23:16 GMT_

---

https://github.com/mozilla/idea-town-addon/pull/22 is the PR, should make auto-signing work for now, and we can probably close this bug when it lands.

We might want to open a followup bug closer to the launch date, and make sure nothing's changed as far as autosigning.

**Comment by meandavejustice** [comment]
@6a68 Can we talk about what needs to happen for this sometime this week? It's still not very clear to me. Also cc/ @lmorchard

**Comment by jaredhirsch** [comment]
@meandavejustice Sure! The basic goal here is to get the addon signed with the AMO key, so that it works in future versions of FF which require extensions be signed. I don't know if we want to try to hack the reviewer process to be able to serve the addon from AMO, maybe @lmorchard has thoughts here.

Assuming you want AMO to sign, but not host, the addon, here's how to do it:

Log into AMO and submit the addon, being sure to check the "Do not list my add-on on this site (beta)" check box:

![screenshot 2015-11-04 16 40 50](https://github-cloud.s3.amazonaws.com/assets%2F96396%2F10956748%2Fdce4e662-8312-11e5-8939-5c0903448390.png)

If the addon submission doesn't throw any errors, then it's passed the auto-signing routine. You can then download the signed XPI by going to https://addons.mozilla.org/en-US/developers/addon, clicking on the name of the addon, then clicking on 'manage status & versions' in the left nav. That'll get you to a screen like this:

![screenshot 2015-11-04 16 47 45](https://github-cloud.s3.amazonaws.com/assets%2F96396%2F10956862%2Ff957ec08-8313-11e5-858b-a239cb579f62.png)

Click on the version number, and you'll finally be able to download the signed XPI:

![screenshot 2015-11-04 16 51 14](https://github-cloud.s3.amazonaws.com/assets%2F96396%2F10956903%2F4e85a346-8314-11e5-8fce-34010df1b0a7.png)

The procedure is similar for adding new versions of an existing add-on.

Hope this clarifies things a bit, please ask more questions if not :-)

**Comment by lmorchard** [comment]
This issue seems tied in with #92

**Comment by meandavejustice** [comment]
closed for #92
