### ISSUE TITLE
Audit list of localized fields

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1732]
It's come to my attention that we don't want to localize experiment names.

@johngruen can you please check this list for comprehensiveness?

https://github.com/mozilla/testpilot/blob/master/frontend/tasks/util.js#L1-L11

**Comment by johngruen** [comment]
@chuckharmston thanks for filing...confirming with Winston.

**Comment by chuckharmston** [comment]
@johngruen make sure you cross-reference with [the template](https://github.com/mozilla/testpilot/blob/master/docs/experiments/experiment-content/template.yaml), since not all the fields are currently in use by each experiment.

**Comment by johngruen** [comment]
@chuckharmston In the mean time, I'm a little torn about the subtitle field. We're only using it for No More 404s an there's a definite non-localizable brand name in there, but the first half of the string is fine. We could either: 
1. divide the string in two which is bad practice.
2. not localize it for now since it's not massively used.
3. maybe there's some dark arts where a non-localized substring can be passed fluidly into a localized string to account for the vicissitudes of sentence construction across languages?

I'm leaning toward 2, but maybe 3 is a (a) a thing and (b) isn't bend over backward hard?

**Comment by ghost** [comment]
3 is possible, but you're asking for trouble (easy example: embedding an LTR name in an RTL language and the nightmare that makes for punctuation, etc.).  Is there a reason you wouldn't just treat it as a normal field?  Localizers are smart - they can work around brands (especially with a good L10n comment!)

**Comment by johngruen** [comment]
Let's do Option 1 then. We'll also need to remove the Title from localization for now.

**Comment by johngruen** [comment]
@chuckharmston so 
- let's take out the title
- add the subtitle

**Comment by johngruen** [comment]
Too much navel gazing on my part. The subtitle is fine as it is. Let's just take out the title.
