### ISSUE TITLE
 [release] 2016-11-03 on stage

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#1756]
Please QA stage. Let's use this issue to track deployment status to production.

Verification documentation: https://github.com/mozilla/testpilot/blob/master/docs/development/verification.md
Release notes: https://github.com/mozilla/testpilot/releases

http://testpilot.stage.mozaws.net/

/cc @SoftVision-PaulOiegas @SoftVision-CosminMuntean

**Comment by SoftVision-PaulOiegas** [comment]
Stage deploy looks good, here are our test results - https://goo.gl/OdUvLy (TestRail page)
Two new issues were found:
1. Activity Stream XPI hash out-of-date - https://github.com/mozilla/testpilot/issues/1760 (Fixed by Wil)
2. Windows 10 Edge browser is wrongly rendering some website items - https://github.com/mozilla/testpilot/issues/1761

We also tested with Firefox builds for FR, DE, ES, AZ, RO localization. The message is correctly displayed for the tested languages on Universal Search page.

**Comment by ghost** [comment]
As part of this deploy we need @relud to turn ON query parameter pass through on production.  Let's remember that on Tuesday :)

**Comment by ghost** [comment]
Also for tuesday:  turn on http/2 in production

**Comment by ghost** [comment]
all this happened.  thanks @relud & @SoftVision-PaulOiegas
