### ISSUE TITLE
Localization Capability for Legal + About pages

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#1768]
We need to localize the ToS, PN and About Pages. We could move these to the legal docs repo, but it's not required (and the About page isn't a legal page).

**Comment by johngruen** [comment]
Related to  #738

**Comment by lmorchard** [comment]
Hmm, this is different than just localizing strings in the common UI. Maybe we need to create markdown & generate whole new separate HTML pages with the locale in the path? That is, you hit `/terms/` and get bounced to `/de/terms`? And that's generated from `compiled-templates/de/terms-of-use.md`?

**Comment by lmorchard** [comment]
Also: are these legal docs meant to be localized via Pontoon? Or will we need a different way to localize them?

**Comment by ghost** [comment]
We'll figure out a timeline in our monday meeting w/ legal

**Comment by ghost** [comment]
We talked with legal and this is blocking.  We weren't expecting that, so this is on us for having it appear in the middle of a sprint. :-/

The docs are at https://github.com/mozilla/legal-docs/tree/master/firefox_testpilot_PrivacyNotice and https://github.com/mozilla/legal-docs/tree/master/firefox_testpilot_Terms .  We'll never have to worry about partial localizations or anything there -- if the file exists, it's good to show.

Thanks.

**Comment by flodolo** [comment]
I don't know much about the background discussion, but legal docs are in that repo for a specific reason: they're translated by an external agency (usually via @peiying2), localizers don't have direct access to them, they can file bugs for minor fixes.

Personally I think it would be pretty confusing to have Test Pilot legal docs in this repo instead of the legal-docs one. And if we do, they shouldn't be exposed for localization through unreviewed channels.

On the other hand, the about page should be translated, and that can't really happen with a .md file.

**Comment by peiying2** [comment]
These documents are being localized as we speak.  We will have the localized files on Thursday.  There should be a "de" equivalent file in both folders.

**Comment by peiying2** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1317493 tracks legal l10n progress.

Regarding the About doc, this comes from the product team, not legal team.
