### ISSUE TITLE
Ensure that experiments locale file stays in sync with content.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1781]
In #1778 we added `experiments.ftl` to the repository, as a short-term step to start the flow of translations. However, the live file is still being generated in the build step, which introduces the possibility of it coming out of sync with the content.

We should consider remediation steps against this.

My suggestion:

1. Stop generating that build file in the build process.
1. Generate it manually with an npm command
1. Fail builds if the output of that npm command doesn't match the file in the repo.

**Comment by lmorchard** [comment]
Actually peeking at this issue a bit as part of the news feed stuff, since we're adding another category of content that needs to be shoehorned into FTL - and we'd like to get string reviews of this stuff.

The suggested solution sounds good. Thinking about doing it as part of #2418 - or as a follow-up shortly thereafter.
