### ISSUE TITLE
Min Vid experiment is wrongly enabled and working when trying to enable the fake add-on

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#1812]
[Affected versions]:
- Firefox 49.0.2 and up

[Affected Platforms]:
- All Windows
- All Mac

[Prerequisites]:
- The "testpilot.env" string pref was manually added with "dev" value on a new clean profile in "about:config" page.
- Test Pilot add-on was previously installed on the profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.dev.mozaws.net" page.
2. Click on the Dev Example experiment and choose to enable it.
3. Observe the browser behavior.
4. Click on "Test Pilot" toolbar button and observe the available experiments.

[Expected result]:
- The Dev Example experiment is successfully displayed as enabled on experiment page and on toolbar button doorhanger.

[Actual result]:
- Step 3: The "Enable Dev Example" button remains in the "Enabling..." state 
- Step 4: Min Vid experiment is wrongly displayed as enabled in toolbar doorhanger. 

[Notes]:
- Min Vid functionality is available after this occurs, it's not just a visual issue.
- We should verify that setting a graduation date for the fake experiment won't affect the Min Vid experiment graduation date.
- Here is a screen recording with the issue: https://goo.gl/SFDMCn.

**Comment by lmorchard** [comment]
The fake dev experiment is mainly just a copy of the min vid experiment with a few strings changed - there is no associated fake experiment add-on. It's just there to test out some site features. So, this behavior is pretty much expected unless we want to actually build a fake add-on too

**Comment by SoftVision-PaulOiegas** [comment]
We thought so too and thanks for confirming this Les. By logging this we only wanted to be sure, as we mentioned in the bug notes, that modifying the graduation date for it, won't affect the real Min Vid graduation date.

However, I have launched a question related to this on https://github.com/mozilla/testpilot/pull/1796#issuecomment-260656395 for testing the graduation flow. I assume the PR was for this.

**Comment by lmorchard** [comment]
That PR was _just_ for enabling the capability to have an experiment that only shows up on dev. We haven't done anything with the graduation flow yet

**Comment by SoftVision-PaulOiegas** [comment]
After looking over the pre-graduation flow today for the fake experiment we end up to the conclusion that 
we won't be able to test the whole functionality with the current state of it. We have lots of limitations with it and lots of unreachable areas. here are a couple of examples:
- We cannot enable the experiment since it has no fake add-on tied to it. Because of this we will not be able to test the UI and flow for an enabled experiment that graduates. And this includes a lot of UI stuff and changes that were discussed and implemented lately (eg: #1747, #1751, #1752, etc).
- We cannot verify the doorhanger behavior of the fake experiment since today it disappeared from there
- Other UI details since fake experiment appears as just launched and does not behaves entirely like a genuine experiment to be graduated.

Is there a way we could enhance it so it would replicate more closely a graduating experiment ? Otherwise this isn't helping to much...

**Comment by ghost** [comment]
I assigned this to me, but I don't remember why.  Are we wanting a fake xpi made?  I can do it, just want to make sure I'm doing the right thing.

**Comment by SoftVision-PaulOiegas** [comment]
Yes, that would be nice o have since only half of the graduation flow is tested at the moment. 
And also, it would be nice for my team to be able to update the graduation date for the fake experiment whenever we need to test the flow if possible. I know it works if you change the system time, but if there's a simpler way to do it, would be nice.
