### ISSUE TITLE
[release] 2016-11-17-3 on stage

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1834]
Please QA stage. Let's use this issue to track deployment status to production. I've assigned this to Paul, but we should all be checking out stage a bit.

- Verification documentation: https://github.com/mozilla/testpilot/blob/master/docs/development/verification.md
- Release notes: https://github.com/mozilla/testpilot/releases/tag/2016-11-17

http://testpilot.stage.mozaws.net/

**Comment by pdehaan** [comment]
![firefox_test_pilot](https://cloud.githubusercontent.com/assets/557895/20414527/b34e6616-ace7-11e6-8d17-1df796072f73.png)

Looks like the graduation text (top warning component) isn't localized.
Also, top spacing on the two dialogs seems to be different.

**Comment by pdehaan** [comment]
Not sure how much of an issue this is either: https://github.com/mozilla/activity-stream/issues/1544
Activity Stream has recently removed a few features (timeline, bookmark view, recent activity), so both screenshots are inaccurate. All the onboarding images in the tour probably should be redone as well since they feature the Activity Stream toolbar icon, or the last tour image mentions Universal Search, which is retiring soon.

**Comment by chuckharmston** [comment]
> Looks like the graduation text (top warning component) isn't localized.

<img width="1103" alt="screen shot 2016-11-17 at 6 16 33 pm" src="https://cloud.githubusercontent.com/assets/23885/20415063/2747bf62-acf3-11e6-895a-074f33170fd9.png">

This was just committed and the strings haven't come in yet. It does have a `data-l10n-id` attribute and you're seeing the backup language (i.e. English), so all is well here.

**Comment by pdehaan** [comment]
Cool, thanks @chuckharmston. But even after those strings get localized, we won't see the translations until our next deploy, correct?

**Comment by flodolo** [comment]
Tip for planning: that's a good reason to not add new strings last minute. 

Those were exposed in the middle of the night in Europe, and you're targeting a European languages as first localization.

Is there any chance to do a new deployment on stage to fix that? It might be a dumb question, since I have no idea how that's done.

**Comment by SoftVision-PaulOiegas** [comment]
Hi guys, here are the testing results from staging server:

New issues:
1. #1836 - Firefox icon from the "Upgrade Firefox" green buttons, is cropped on German locale
2. #1837 - Prompt notification to check experiments wrongly shows after browser restart instead of 24h from installation 
3. #1838 - The "What experiments?" button from notification to try experiments after 24h from installation is wrongly colored 

Other observations and concerns:
1. There is no legal page localized in German on dev or stage servers yet. Will those be available later or only on production (based on https://bugzilla.mozilla.org/show_bug.cgi?id=1317493)?  
2. Graduation, survey and report cannot be tested (dev / stage) due to the fake experiment current state and limitations. 
3. End of life notice for experiment should be displayed only on experiment details page or also on experiment card ? Currently we have the 11/30th date for Universal search only on details page.

**Comment by ckprice** [comment]
I'm going to keep this one as `needs:qa` until #1817 and #1837 are resolved.

**Comment by chuckharmston** [comment]
Commits to cherry-pick:

- a87e737
- de6f2a1 
- 5967269 
- a8daf0f
- d38b0ea 
- 76c8679
- 39a7860 
- e9ffe2c  
- 8e505a4

**Comment by ckprice** [comment]
Created tag `2016-11-17-1` starting from `2016-11-17` and cherry picking the 9 commits above.

The [resulting compare](https://github.com/mozilla/testpilot/compare/2016-11-17...2016-11-17-1) seems to be what is expected. @chuckharmston @clouserw r? If this looks okay, we'll push to stage tonight for SV to verify.

**Comment by ckprice** [comment]
Okay, we got in another fix.

Release `2016-11-17-2` is on stage. @SoftVision-PaulOiegas please verify for tomorrow morning. Here's a comparison of what was cherry-picked today https://github.com/mozilla/testpilot/compare/2016-11-17...stage-static.

**Comment by SoftVision-PaulOiegas** [comment]
Hy guys,

Here are the issues found while testing staging latest changes:
1. #1858  - Localization missing for specific elements on the Test Pilot website
2. #1860 - "Your Privacy" section looses localization when resizing window (mobile portrait size)
3. #1861 - End phrase dot placed outside the list element in NoMore404s "Your Privacy" section in German locale
4. #1862 - Contributor "Noitidart" is not displayed on Min Vid experiment page (on stage)

**Comment by ckprice** [comment]
> #1858 - Localization missing for specific elements on the Test Pilot website

We determined this to be blocking, and pushed `2016-11-17-3` to stage.
