### ISSUE TITLE
contributors_extra_url is not rendering link correctly

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1882]
The URL doesn't click. This is what is rendered in dev tools:

```html
<p class="disclaimer" data-l10n-id="trackingprotectionContributorsextra" target="_blank" href="https://mzl.la/2fYneDq">
This experiment is based on Firefox Tracking Protection technology built by Mozilla employees and contributors over the past several years.
Learn more about <a>Firefox Tracking Protection</a>.
</p>
```

Ref: [the commit](https://github.com/mozilla/testpilot/commit/1e394f2426347f63673a26a94e4142e8b6ac785e) that this was added in.

**Comment by chuckharmston** [comment]
Two things:

1. I don't see the `trackingprotectionContributorsextra` string in the FTL at all.
2. I may have been mistaken about how l20n gets the URLs in [this comment](https://github.com/mozilla/testpilot/pull/1879#discussion_r89895884). It seems that it picks it up from the fallback/no JS string

Not sure how to move forward with this. A few options immediately come to mind:

1. We can put the URL in the string as John originally did. This is bad practice and a difficult thing to do poorly and fix later.
2. We can have separate strings for the localization and the fallback string, putting the URL in the latter. This is pretty ugly, but relatively effective.
3. We can not localize it at all for this push, and try to figure something out for the next one. Since we aren't shipping a German experiment for the immediate future, this might be okay.
4. We can structure this section better to avoid needing to put HTML into it at all.

**Comment by ghost** [comment]
I'm happy with number 3 for this push

**Comment by flodolo** [comment]
Not sure if these could be useful for a proper fix (see also [link to legal](https://github.com/mozilla/testpilot/blob/a4b08eaafefe15db6720ce3b8b0eba2952ca240b/frontend/src/app/components/MainInstallButton.js#L27))
https://github.com/mozilla/testpilot/pull/1736
