### ISSUE TITLE
Replace lodash references with the small module versions.

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#190]
`npm remove lodash && npm install --save lodash.flatten`

``` javascript
import flatten from 'lodash/array/flatten';
```

should become:

``` javascript
import flatten from 'lodash.flatten'
```

**Comment by lmorchard** [comment]
:+1: I think this could go a long way to helping shrink our `app.js` at the end, that and an `npm dedupe` run. Did this on a side project and it reduced the size from like 1MB down to like 100k because I wasn't using _all_ of lodash, and many of my dependencies all had their own private copies of all the small lodash modules

**Comment by pdehaan** [comment]
Looks like the only 2 instances of **lodash** in this repo are both in [./idea_town/frontend/static-src/app/views/base-view.js](https://github.com/mozilla/idea-town/blob/b60eb9a650d1380897a6e29e8022591982a12e94/idea_town/frontend/static-src/app/views/base-view.js#L2-L3):

``` js
import flatten from 'lodash/array/flatten';
import invoke from 'lodash/collection/invoke';
```
