### ISSUE TITLE
Suport RTL for testpilot FrontEnd

### ISSUE THREAD

**Issue by mohamed7afezz** [mozilla/testpilot#1906]
We almost finished Arabic localization for testpilot website, as part of planning for [Arabic Identity of Test Pilot Activity](https://github.com/ArabicMozilla/Planning/issues/9) and RTL bugs is here.

 
## Home page have 3 main issues with RTL languages:

1. In card-list section, Cards need to margin-left with zero and margin-left with 40px

![untitled2](https://cloud.githubusercontent.com/assets/9789109/20859539/90a93c0a-b96a-11e6-9a55-b9ebaf4c344a.png)

2. In newsletter-footer section, background image "email pic" need to change position to right and change the header margin to left

![untitled1](https://cloud.githubusercontent.com/assets/9789109/20859584/3a26b5d2-b96b-11e6-8f64-9397fbed605f.png)

3. In main-footer section, margin for mozilla-logo need be change to left and margin for social-links need to change to the right

![untitled33](https://cloud.githubusercontent.com/assets/9789109/20859589/84603790-b96b-11e6-89c6-4a7ed7f7b07c.png)

## Experiments page have 2 main issues with RTL languages:

1. In testpilot-promo section, the legal-information paragrapher need to text-align to right

![untitled4](https://cloud.githubusercontent.com/assets/9789109/20861999/4e836bba-b9a7-11e6-8e25-6387e4f79c7e.png)

2. In contributors section, contributor div need to text-align to right and change the padding to right

![untitled5](https://cloud.githubusercontent.com/assets/9789109/20862061/34326ad4-b9a9-11e6-9e44-ebc17dc16c27.png)

In addition to the 3 main issues that appear in Home page

**Comment by johngruen** [comment]
@mohamed7afezz we should do this! I'd like to make sure we hit small viewport sizes correctly as well though. Would you mind taking a look at errors you see there as well?

**Comment by johngruen** [comment]
I think we could reasonably pick this up with any photon redesign we do.

**Comment by meandavejustice** [comment]
Came across [this article](https://hacks.mozilla.org/2015/09/building-rtl-aware-web-apps-and-websites-part-1/) today on mdn which looks pretty helpful. I think the way forward is to detect whether or not the user is using a rtl lang, and set the `dir` attribute on the html document and target it with `html[dir="ltr"]` selector in our css. We don't have a terrible amount of text surface area, so I think it's reasonable to target these areas in our own css rather than trying to use something like https://github.com/twitter/css-flip which may just cause further problems for us.

@johngruen thoughts?

**Comment by meandavejustice** [comment]
Additionally, based on manually testing for `ar` on testpilot prod site, we aren't supporting arabic right now. Maybe our translation percentage fell below the threshhold at some point?
