### ISSUE TITLE
[release] 2016-12-15 on stage

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1917]
Please QA stage. Let's use this issue to track deployment status to production. I've assigned this to Paul, but we should all be checking out stage a bit.
- Verification documentation: https://github.com/mozilla/testpilot/blob/master/docs/development/verification.md
- Release notes: https://github.com/mozilla/testpilot/releases

http://testpilot.stage.mozaws.net/

**Comment by SoftVision-PaulOiegas** [comment]
Hi guys,

Due to the fact that almost all team we'll be out of office for the company Christmas party after the lunch break, we squeezed a run of the Full Functional suite on stage server in the morning. This means also that we won't be joining the evening call so we'll talk on Monday if something is unclear.

Here is the report after our round of testing:
**New Issues:** 
1. #1919 Min-Vid cannot be enabled on latest Test Pilot version - **Critical severity** issue
2. #1920 Universal Search is still displayed in "Other experiments" section of all experiment details pages - **Minor severity** issue

**Known issues**
1. #1866 Failed to enable experiment error message persists after experiment is successfully enabled - Additional details found, the tour is not launched when this occurs. - **Normal severity** issue due to the new found behavior.
2. #1907 Data collection "Learn more" text link from Privacy section looses the URL underneath and localization at small viewport - **Normal severity** issue
3. #1915 Two of the prefs added at the installation are kept after uninstall - **Normal severity** issue

**Comment by ckprice** [comment]
Per our meeting this morning, we'll be pushing to production at 8am PST tomorrow (Tuesday). @SoftVision-PaulOiegas and team will then verify.

**Comment by ckprice** [comment]
Paul confirmed this deployment in channel. Closing bug.
