### ISSUE TITLE
I can't disable test pilot.

### ISSUE THREAD

**Issue by ashonnard** [mozilla/testpilot#1943]
Thank you for contributing to Test Pilot!

Please use this form to report Test Pilot specific issues. If you think you've found an issue with one of the experiment add-ons, please file an issue in the appropriate repo below:

- Activity Stream:      https://github.com/mozilla/activity-stream/issues/new
- Tab Center:           https://github.com/bwinton/VerticalTabs/issues/new
- Universal Search:     https://github.com/mozilla/universal-search/issues/new
- No More 404s:         https://github.com/internetarchive/FirefoxNoMore404s/issues
- Page Shot:            https://github.com/mozilla-services/pageshot/issues/new
- Min Vid:              https://github.com/meandavejustice/min-vid/issues/new
- Tracking Protection:  https://github.com/mozilla/blok/issues/new

<img width="1206" alt="screen shot 2016-12-22 at 3 20 05 pm" src="https://cloud.githubusercontent.com/assets/15874165/21439115/2d6d2ff8-c85a-11e6-9120-8dd21f4f353f.png">

**Comment by SoftVision-CosminMuntean** [comment]
Hi @ashonnard thanks for reporting this.

This issue is also related to #1940. There was some problems with Test Pilot automatically update. I was also able to reproduce this. If you had an older version of Test Pilot, the experiments remained stuck in enabling/disabling state. 

Issue #1940 should be fixed and now Test Pilot is automatically updated to the latest version (0.9.2-dev-78214f8)  and the experiments can be enable and disable without any problems.
If your add-on is not yet updated, you can manually update it from about:addons, "Extensions" section.
