### ISSUE TITLE
Cannot navigate directly between experiments

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#1945]
STR
1. visit TxP website (without addon installed)
2. visit universal-search page
3. scroll to bottom, click on link to any other experiment, say, min-vid

Expected: the min-vid page should be rendered correctly.

Actual: the min-vid title and image are shown, but most of the page is not updated: the universal-search team and description (graduation report) are shown, and the list of experiments at the bottom of the page excludes universal search, not min-vid.

**Comment by jaredhirsch** [comment]
This only happens when the addon is not installed.

**Comment by SoftVision-PaulOiegas** [comment]
This is already fixed on dev by #1920. Graduated experiments should not be displayed without TxP add-on installed. I think we can close this one if you don't see any remaining cases when this could occur.

**Comment by jaredhirsch** [comment]
> Graduated experiments should not be displayed without TxP add-on installed

I'm confused. Why would we bother writing up a graduation report if we want to hide past experiments from new users? Reopening.

**Comment by jaredhirsch** [comment]
I'm going to move the product question to a separate bug and leave this open as a bug about the app not updating the page when navigating away from a graduation report.

**Comment by johngruen** [comment]
So this problem is actually much bigger than what jared saw... it seems like we cannot navigate directly between individual experiments. This is happening on dev...

## STR

- go to any experiments details page
- navigate to another experiment page by click on the experiment cards at the bottom of the page


## Results 

- URL matches new experiment's slug but previous page content is in experiment details

## Expected

- You go to the page of the experiment you clicked on. 

## Notes

So i was fiddling around trying to fix this tonight, but didn't have much luck. With some console logging, it looks like that when you navigate to the experiment page from the home page or the experiments list page, the render method for `ExperimentPage` is called twice. The first time the props aren't available to be passed in and the second time they are (this happens instantly so it isn't noticeable unless you log it) so the page renders correctly. If you go from experiment to experiment to experiment, render only gets fired once per navigation event, and only the prop-less render gets called. That's why @6a68 saw the initial bug he reported here where the previous page's content stayed visible.

## Fix

I'm a little green WRT Redux component life cycle, routing, etc, so I'm not sure the best way to fix the core issue. We could just take out the footer cards for the next sprint if this is tricky to figure out. I bet its like a 2 line fix though if somebody knows what they're doing. 

@dannycoates @chuckharmston flagging you guys b/c you're far more react-genius than i am. I;'m happy to land the patch that removes these cards from the experiment pages, but maybe you can come up with a better solution?

**Comment by johngruen** [comment]
NB, tested on local and dev

**Comment by johngruen** [comment]
BTW, marked as critical b/c this is a bad bug to have floating around in the wild. I'm happy to simply remove these cards for this sprint and re-rack on a longer term fix in the next sprint if necessary.

**Comment by lmorchard** [comment]
Hmm, checking this out and don't see this on prod (yay) but I do on my local machine (boo). I see an error in the console when I try to navigate between experiments: 
```
TypeError: node is null[Learn More]  vendor.js:34708:9
```
I don't see this if I go experiment to home to experiment, just going from experiment to experiment

**Comment by lmorchard** [comment]
Hmm, that error might be unrelated to this issue, though: Started doing a `git bisect` to see if I could find when the issue came in, found a commit with the error but where navigation worked fine. Still bisecting though...

**Comment by lmorchard** [comment]
Looks like this issue was introduced in b331ad901ef6236b52d1d0b27b62c5672c3e1c11 - doesn't happen in c2852025bbe7ba44e1efc376cde06ee706c8685d (the commit before it). Not sure what's causing it, but it seems to start there.

**Comment by johngruen** [comment]
uh oh

**Comment by lmorchard** [comment]
Yeah, this is bizarre. If I comment out [this line in MainInstallButton's renderOneClickInstallButton() method](https://github.com/mozilla/testpilot/commit/b331ad901ef6236b52d1d0b27b62c5672c3e1c11#diff-24c12d4e63197828d8a8c98f33ab2c89R42) this issue goes away. (So does the install button title, but...) Still digging. Doesn't make sense that that line would cause this :/

**Comment by johngruen** [comment]
@lmorchard 

So i added this to the MainInstallButton

```
  constructor(props) {
    super(props);
    this.state = {
      isInstalling: false,
      experimentTitle: this.props.experimentTitle
    };
  }

  componentWillReceiveProps(nextProps) {
    this.setState({ experimentTitle: nextProps.experimentTitle });
  }
```

and now i see this if move between pages:

<img width="1351" alt="screen shot 2017-01-26 at 12 00 52 pm" src="https://cloud.githubusercontent.com/assets/3323249/22341529/2711d9e4-e3bf-11e6-99a5-33a245580e6c.png">

Note the button text is correct while the page content is still wrong
I'm guessing this means there's an underlying bug where the experiment details are not getting props updated.

**Comment by johngruen** [comment]
oh, looks like you just PR'ed something

**Comment by lmorchard** [comment]
Yeah, hashing it out in IRC too. I think we're seeing React & L20N arm wrestling and causing errors & breakage here

**Comment by johngruen** [comment]
@lmorchard yeah i assume that's what was happening in jared's original report
