### ISSUE TITLE
Past experiments should be visible without addon installed

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#1951]
Looks like the 'view past experiments' button is gone from dev, so there's no way for new users to see the universal search graduation report.

We also need to make past experiments visible from the single experiment details page, so users can browse to all the experiments regardless of which page they are on.

Split off from #1945.

**Comment by SoftVision-PaulOiegas** [comment]
The "View Past Experiments" button was never there for users without TxP add-on installed. Because of that, we considered that Universal Search should not be displayed either between other experiments section, without TxP installed. That's why I've closed #1945 in the first place. 

But if you guys consider the graduation reports to be important for TxP new users. Then yeah, it would be nice to have the past experiments section available even without TxP installed.

**Comment by johngruen** [comment]
@6a68 I agree we should do this, but I'm going to let is sit for a minute as is. We're changing around gsome UX in anticipation of getting rid of the add-on so this might get bundled up with that work:

#1922
