### ISSUE TITLE
[release] 2016-01-10 (German launch)

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1968]
Notes: https://github.com/mozilla/testpilot/releases/tag/2016-01-06

Creating a release bug to track todo's/deployment status leading up to our German launch on the 10th.

Currently planning on a production push on Tuesday morning at 8 AM PST.

**Comment by ckprice** [comment]
@johngruen noted that we may possibly want to do another prod push on Monday morning to get folks updated because old en users will see Cliqz in their doorhanger. TODO: how many people actually come to the site from the doorhanger?

**Comment by ckprice** [comment]
Ready for review on stage.

**Comment by ckprice** [comment]
https://github.com/mozilla/testpilot/pull/1993 was merged in after this stage push, we'll want to get it in before we push to prod.

**Comment by SoftVision-PaulOiegas** [comment]
Hi guys,

Here are the results after the stage deployment verification.
### New issues
1. #1998 DE locale restrictions are not applied for Chrome browser - normal severity issue
2. #2000 Loading animations display a white box artifact (Nightly) - minor severity issue

### Known issues
1. #1866 Failed to enable experiment error message persists after experiment is successfully enabled - normal issue.
- Considering this a concern due to the fact that the tour is also skipped when this occurs.

### Concerns
1. #1985 After the installed Test Pilot add-on auto-updated, the localization restricted experiments were redisplayed in doorhanger
- Possible blocker. The issue was reproduced today on stage and it's still reproducible after ~ 6 hours of testing. We have provided additional info on the issue. 
2. #1987 Send correct locale when submitting welcome email
- In regards to Cory's issue with the newsletter not being localized. The shared social media content is also not localized. Should we log an issue for this too ?
3. #1935 Non localized pages are displaying the footer links in English while main pages display them localized
- Since we are deploying a lots of implementations for German users, this could be an issue that would affect them.

**Comment by ghost** [comment]
As discussed this morning I've re-pushed stage with the latest updates.  (Also production)

**Comment by ckprice** [comment]
We are on production. At 4pm PST today we should have access to the Cliqz product page, with it being listed on the homepage in DE.
