### ISSUE TITLE
Convert yaml snake_case vars to JS lowerCamelCase

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#1974]
It's pretty unsavory that we've got a handful of snake_cased variables like  `experiment.locale_grantlist`, while everything else in the JS code is lowerCamelCased.

It'd be easy to wrap the Yaml output in a snake case to lower camel converter, and would make the code more consistent :+1:

This PR should also add an eslint error about snake_cased variables, I think, to enforce future consistency.

**Comment by jaredhirsch** [comment]
New contributors can ping me for help getting started on this bug.

**Comment by pdehaan** [comment]
I think the ESLint rule in question is http://eslint.org/docs/rules/camelcase

**Comment by lmorchard** [comment]
Yeah, the snake case is an artifact of the Django REST Framework API we used to use. Switched over to a static JSON file, but kept all the same property names. We didn't change it then because there are some gotchas:

1. The names are all over the code, so it would be a wide ranging change that could cause trouble and we didn't have sufficient tests to catch problems. (Maybe that's better now?)

2. The names are (I think) used in the construction of L10N IDs, so we'd have to be careful to make sure we don't invalidate any translations.

These things might make this a bit more than we'd like for a first-time contributor to bite off.

**Comment by lmorchard** [comment]
Also, ESLint will complain if certain property name formats are used in JS - but not in YAML or JSON or FTL. So, fixing it just in JS and missing it everywhere else is troublesome.

**Comment by johngruen** [comment]
FWIW, i kind of don't mind the snake cased vars...it's a quick visual indicator of where things are coming from.

**Comment by hammad13060-zz** [comment]
Hi @6a68 I'd like to work on this. can you point me to relevant files :)

**Comment by ckprice** [comment]
Lots of places to change, breaking tests, nice to have some variables with different styles.
