### ISSUE TITLE
Re-enable integration tests

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#1975]
We turned off integration tests because they were flaky.  Let's talk about what it would take to get them turned back on.

**Comment by chuckharmston** [comment]
As I understand it, the tests were failing because we struggled to deal with the new doorhanger. Fortunately, we have a flow (w/`mozAddonManager`) that lets us skip the doorhanger entirely, if certain preconditions are met:

- One of:
    - The hostname of the page and add-on are on a whitelist of production sites.
    - The hostname of the page and add-on are on an extended list of testing sites (which includes `example.com`) and `extensions.webapi.testing` is `true`.
- The page and add-on are served over HTTPS.
- One of:
    - The cert issuer is built in.
    -  `extensions.install.requireBuiltInCerts` is `false`

I think we should be able to achieve these conditions in an integration tests: CircleCI [allows modification of the hostfile](https://circleci.com/docs/configuration/#hosts) and you can change Firefox config with Marionette. The SSL bits might be tricky, but should be doable.

**Comment by fzzzy** [comment]
https://github.com/mozilla/testpilot/issues/1743 has some useful info related to this.

**Comment by fzzzy** [comment]
Looks like https://github.com/mozilla/testpilot/issues/1903 will also need to be taken into account for this.

**Comment by fzzzy** [comment]
This was fixed by https://github.com/mozilla/testpilot/pull/2380
