### ISSUE TITLE
Document config file setup in README

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#198]
The README doesn't mention that you need to copy over .ebextensions/00-environment.config-dist and insert some config values.

I think a new dev will have to replace, at a minimum:
- INITIAL_ADMIN_EMAIL
- SECRET_KEY
- ALLOWED_HOSTS (should we just default it to ideatown.dev?)
- ADDON_URL
- FXA_CLIENT_ID
- FXA_SECRET_KEY

**Comment by jaredhirsch** [comment]
Oh, I guess I'm not sure how to pipe the contents of the elastic beanstalk config file into settings.py. Do I need to manually set the ADDON_URL in both places?

**Comment by lmorchard** [comment]
Thinking out loud in advance of actually addressing this stuff: 
- You'll never have to touch `idea_town/settings.py` for general configuration, just to add new features. Any configurable values are pulled from env vars using [`decouple.config()`](https://github.com/henriquebastos/python-decouple)
- For local dev, everything should be all preconfigured in `docker-compose.yml` with env vars set to useful things for a consistent environment. A new dev should never have to touch this stuff. Things should work out of the box with `docker-compose up`.
- The elastic beanstalk config file is _only_ used in deploying to elastic beanstalk - and actually I'm not entirely sure that's how it's going to work once we've finished synching up with ops. Elastic beanstalk also uses env vars, so that's how values get piped into `settings.py` Should cover off on that as part of #165 
- `ADDON_URL` needs to be set as appropriate for local, dev, stage, prod, etc - assuming we have different versions for each environment. But, again, this should be already taken care of for local dev

**Comment by jaredhirsch** [comment]
:+1: that makes total sense to me
