### ISSUE TITLE
The Cliqz survey cannot be completed due to the last page that seems to be unfinished

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2014]
Affected versions]:
- Firefox 50.1.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Install or extract a German Firefox build for this issue.
- Test Pilot add-on was previously installed on the profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.firefox.com" page.
2. Choose the Cliqz experiment and enable it.
3. Click the "Give Feedback" blue button.
4. While completing the survey observe the third page.

[Expected result]:
- The third page is correctly rendered and the survey can be completed.

[Actual result]:
- "TO BE TRANSLATED: " message is displayed on the third page and the survey cannot be completed.

[Notes]:
- If the English language is set, the third page is empty and the survey cannot be completed.
- If you try to complete a survey after disabling the add-on, the message is displayed on the second page and the survey cannot be completed. 
- Here is a screenshot with the issue:

![cliqz survay](https://cloud.githubusercontent.com/assets/19226534/21889226/93e26f6a-d8d0-11e6-9cd1-bb3434e34994.png)

**Comment by johngruen** [comment]
Matt Grimes thinks he fixed this. @SoftVision-CosminMuntean can you confirm when you have a chance?

**Comment by ghost** [comment]
@SoftVision-CosminMuntean @johngruen:

**Issue cause:**

- SurveyGizmo was marking users that matched our skip to end logic as "Disqualified" and showing them an untranslated disqualification message.  We shouldn't be disqualifying anyone in this survey, so the lack of translation was not the root cause.
  - This is _despite the disqualification checkbox not being checked_ (I believe this to be a bug)
  - This issue was fixed by toggling the "Complete" checkbox in the "If the Logic Passes, mark the response as" section.  (I wish I was kidding)
    - Before: <br>![beforefix](https://cloud.githubusercontent.com/assets/6495848/21911025/796ef902-d8d3-11e6-90fc-8efd580915c3.png)
    - After: <br>![afterfix](https://cloud.githubusercontent.com/assets/6495848/21910940/1b80b286-d8d3-11e6-9d4e-6df88677a37f.png)

**Issue scope:**

- This affected all users who selected "No" to if they want the long form of the survey to "tell us more".  In total 88 users.
- This was the end of the survey anyway, so we did not lose data despite the bad user experience.

**Comment by johngruen** [comment]
thank for the writeup @rayborn marking this as closed

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issues and is no longer reproducible. Marking this as verified.
