### ISSUE TITLE
Proposal for onboarding tour with one-click install

### ISSUE THREAD

**Issue by bigheadcool** [mozilla/testpilot#2066]
https://mozilla.invisionapp.com/share/RJA6SZEHB

Here's a proposal that combines the email prompt with experiment tours. (+promotion screen)
We added a cover onboarding image in the beginning and an email prompt at the end.

![tour cover - update](https://cloud.githubusercontent.com/assets/4211825/22320128/59eec296-e3c4-11e6-9900-400ddf6d4e77.png)
![tour email - update](https://cloud.githubusercontent.com/assets/4211825/22320129/59f0c3a2-e3c4-11e6-9824-84fc2a81a849.png)

Feel free to comment on the InVision screens!
Thanks.

**Comment by johngruen** [comment]
hey @bigheadcool i like the proposal with a few caveats: 
* Modals elsewhere on the site use a common layout that would be easier to adopt here as well.
* We already have a full bleed version of the image on the first slide (see image below)...it seems like we could recycle that for this flow.
* I'd like to see this proposal joined with an experiment onboarding flow, so if a user installs Test Pilot + Page Shot from a one-click install they see something like this: 
`welcome to test pilot +experiment on boarding + email solicitation`

**Comment by youwenliang** [comment]
@johngruen 

I'll see what I can do to adopt the common layout! As for the full bleed version where can I see the image?

By the way, this proposal is exactly what you suggested in your third point ->
"welcome + experiment on-boarding +email solicitation"
I only showed the first and last slide image above but there is going to have the original experiment tour slides in between.

**Comment by youwenliang** [comment]
@johngruen 

Can we do something like this?
![tour cover - modified](https://cloud.githubusercontent.com/assets/8919308/22536886/acd7b9be-e940-11e6-8282-c9d4877f0570.png)
![tour email - modified](https://cloud.githubusercontent.com/assets/8919308/22536887/acd9afe4-e940-11e6-9e7e-6947dd4f0d43.png)

**Comment by SoftVision-PaulOiegas** [comment]
@johngruen I'm currently updating the tests suite for the new UI changes and I have some questions related to this new pop-up style. 
Above I've seen you mentioned a flow with 3 steps "welcome to test pilot +experiment on boarding + email solicitation". Will the pop up for normal Test Pilot install have then only the "welcome + email solicitation" slides since no experiment is enabled ? 
I can see on both proposals that the old onboarding image is already displayed so I'm thinking that there is no point in having a 3 steps there.

**Comment by chuckharmston** [comment]
This seems unlikely to get done. Closing!
