### ISSUE TITLE
[release] 2017-01-30 on Stage

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#2084]
Please QA stage. Let's use this issue to track deployment status to production. I've assigned this to Paul, but we should all be checking out stage a bit.

- Verification documentation: https://github.com/mozilla/testpilot/blob/master/docs/development/verification.md
- Release notes: https://github.com/mozilla/testpilot/releases

http://testpilot.stage.mozaws.net/

**Comment by ckprice** [comment]
Lots of stuff to QA! Most notably one click install (4ad6eb6a170d843ff772d9cdd75f5e70b018dc0d) and the add-on rewrite (ebde508c742f4de171577cc0e8809b322c5db922).

**Comment by SoftVision-PaulOiegas** [comment]
Hi guys,

Here are the testing results after our round of testing:
### **New Issues**
1. #2085 - "Install Test Pilot & Enable Universal Search" button is wrongly displayed on Universal Search past experiment page 
2. #2086 - The "Onboarding" page is not opened after Test Pilot is installed 
3. #2087 - The "moz://a", "GitHub" and "Twitter" logo buttons are wrongly rendered in black color on Edge browser
4. #2088 - Artifacts wrongly displayed before and after the number of participants on Edge browser
5. #2090 - Experiment auto enable hangs if you wait more than ~5 seconds before allowing Test Pilot installation from doorhanger 

### **Known issues**
1. #2068 - Experiment links and "Your Privacy" sections are hidden in mobile view when Test Pilot is not installed
2. #1855 - Verify/Fix Test Pilot doing an "enable" ping on an add-on upgrade
Since the bug was logged the number of participants reached over 500k. And only today, Page Shot participants number increased with ~6k people. Maybe it's something fishy here after all ?

### **Other possible issues observed**
1. The new mozilla logo still seems to be positioned a bit high. Dany Coates suggested it to be lower on his issue #2040.
2. Edge browser strangely renders the text on "About Test Pilot", "Privacy" and "Terms" pages. The text covers almost the entire page at the beginning and after it is narrowed to the center of the page as default on Firefox (see movie - https://goo.gl/bTmf7r).
3. Shouldn't we have the "View Past Experiments" button also under other experiments section from experiment details page ?

**Comment by ckprice** [comment]
Release `2017-01-30` was created from a cherry-pick of `2017-01-26-1`.

See the diff here: https://github.com/mozilla/testpilot/releases/tag/2017-01-30

@SoftVision-PaulOiegas and @SoftVision-CosminMuntean to confirm stage tonight, and if things look good, we'll move forward with a production push at 8am PST.

**Comment by SoftVision-PaulOiegas** [comment]
Hi guys,
 - Waiting bug **(fixed)**: The longer wait time clearly helps as a quick measure for the issue. But we think that adding also a message in the future for when it fails would be even better.  
- White logos **(fixed)**: Edge browser is a proud owner of white logos.
- Install button graduation page **(fixed)**: Button and top part are no longer displayed on "Universal Search" experiment page.

From QA point of view we are good to release. If Peter has nothing to object. 😄
