### ISSUE TITLE
Page contents not fully updated after clicking related experiment

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#2097]
Found in https://testpilot.dev.mozaws.net/__version__ (9ad7ce2afd0dcf60b1cf77679f4f0c90b528acc7):

```json
{ "commit": "9ad7ce2afd0dcf60b1cf77679f4f0c90b528acc7",
  "version": "",
  "source": "https://github.com/mozilla/testpilot",
  "build": "https://circleci.com/gh/mozilla/testpilot/2973" }
```

---

### Steps to reproduce:
1. Go to https://testpilot.dev.mozaws.net/experiments/page-shot
1. Scroll to related experiments and click on min-vid experiment.
1. Scroll down and observe page contents.

### Actual results:
Left sidebar shows correct Min Vid content, but the right content area still shows the content from the Page Shot experiment.

### Expected results:
Main content should be updated to current experiment. Oddly, I wasn't able to reproduce this on stage, so maybe it's a recent regression in master.

---

![firefox_test_pilot_-_page_shot](https://cloud.githubusercontent.com/assets/557895/22389347/e84d502c-e499-11e6-9d9b-0b7f906f63c3.png)
**Before:** Page Shot experiment page.

---

![firefox_test_pilot_-_min_vid](https://cloud.githubusercontent.com/assets/557895/22389365/fd188422-e499-11e6-8b95-b663fe525cfb.png)
**After:** Min Vid experiment page w/ Page Shot details.

**Comment by pdehaan** [comment]
I can still reproduce this on production, commit bc997443ded340eaad5f305819a3cecdcc829231 (we had a user report it also in #2201).

```js
{
  commit: "bc997443ded340eaad5f305819a3cecdcc829231",
  version: "",
  source: "https://github.com/mozilla/testpilot"
}
```

Reopening.

**Comment by dannycoates** [comment]
![](http://i.giphy.com/URcmhQ5PpztC0.gif)

**Comment by SoftVision-PaulOiegas** [comment]
Well, this is definitely a strange regression since we checked the fix. At least on stage I can be 100% sure that this was working since I've tested it and I noticed a slight delay on images update while navigating between pages. But nothing that would concern so much to reopen the issue.
 
However, I'm not 100% sure on production since we have a reduced suite for the deploy (because of testing hours). But I'm betting this was ok on Tuesday deploy too.  
Maybe something broke it on the next pushes for graduation ?

**Comment by ckprice** [comment]
Removing https://github.com/mozilla/testpilot/blob/master/frontend/src/app/containers/ExperimentPage.js#L454 stops the `TypeError` from happening and loads the content.

Looks like it was added by @fzzzy in 8514e6ab5edfc6ccc023dc1dafd151d37dd51f68. I'll poke at it more next week.

**Comment by fzzzy** [comment]
This is just the same issue we've had with race conditions with internationalization updating the dom. If react tries to update the dom after internationalization has been performed, this will continue to happen. Two possible solutions: 1) Remove react-router. 2) Pass the localized strings to react as props, instead of allowing the internationalization library to change the dom after react. Neither is easy.
