### ISSUE TITLE
[release]  2017-02-13 on Stage

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#2158]
Please QA stage. Let's use this issue to track deployment status to production. I've assigned this to Paul, but we should all be checking out stage a bit.

- Verification documentation: https://github.com/mozilla/testpilot/blob/master/docs/development/verification.md
- Release notes: https://github.com/mozilla/testpilot/releases

http://testpilot.stage.mozaws.net/

**Comment by SoftVision-PaulOiegas** [comment]
Hi guys, here are the results after our round of tests:

### **New issues**
1. #2159 - The new thick white border that surrounds the install buttons is missing on other locales than en-US (**Minor**)
2. #2160 - Activity Stream data collection link from your privacy section redirects to a 404 page (**Normal**)
3. #2161 - [Stage] Test Pilot spaceship logo is wrongly positioned on Test Pilot "Experiments" page (**Minor**)
4. #2162 - "Install" button new thick white surrounding border is non persistent on Windows and Linux (**Minor**)
5. #2163 - If experiment download fails, the "Enabling..." button remains in the enabling state and no error is displayed (**Normal**)
6. #2164 - The "Changelog" and "Bug Reports" German words are wrongly split on "Experiment details" page (**Minor**)

### **Known issues**
1. #2103 - Links displayed in "Your Privacy" measurements section, no longer have links (**Major**)
- Users don't have access to links from Privacy section.
2. #1335 & #680 - Manually disabled add-ons (**Normal**)
- A couple of users reported that they cannot install Test Pilot and this was caused by the fact that they had it manually disabled but got no notification to signal this.
3. #1702 - Privacy page content is wrongly positioned on the middle of the page (**Minor**)
- Regression after CSS changes. 
4. #2153 - Missing string on newsletter sign up success pop up (**Minor**)
- Users are not informed of the Newsletter email that is sent after sign up. 

### **Other possible issues observed** 
1. The "Go beyond..." first sentence is missing from Homepage. 
- Was this intended or it was lost in the process ?

**Comment by ckprice** [comment]
Stage is updated with the completed dates for Tracking Protection and No More 404s. There is an uninstall date for Tracking Protection, but the uninstall probably won't function (see #2168).

In addition to the new change, as discussed, please give the new ping-centre some QA attention.

**Comment by ckprice** [comment]
Updated with Danny's l10n caching fix.

**Comment by SoftVision-PaulOiegas** [comment]
Hi guys,

Here are the testing results for today: 
### **1. Graduation dates for Tracking Protection and NoMore404s**
- Both the experiments have "Ending soon" notification, followed by "Ending tomorrow" when you progressively change the system date. 
- If the date for graduation is passed, the experiments are correctly moved at past experiments even if still enabled, and the only available option is to disable them.  
- ***Regarding the uninstall part, as you said, this is not working yet.***

However, we have noticed that the set graduation date for both the experiments was not set also for production server. Meaning that the users that are now using the production server, will know of the graduation only a day before it will happen. Is this ok with you guys ? 
We thought we will let them know faster since the normal flow we have, should display it 1 week before graduation.

### **2.  Ping centre**
- Cosmin tested this most of the day and he already responded with the results on the Jared's PR
https://github.com/mozilla/testpilot/pull/2151#issuecomment-279411288. It seams that there may be some issues with it.

### **3. L10n caching**
Should we test this ? If yes, can you guys give us any details on how we could test ? We haven't seen any details for this on the PR.

**Comment by johngruen** [comment]
Another issue...site appears broken on ios webkit

**Comment by ckprice** [comment]
> Another issue...site appears broken on ios webkit

Stage is updated with John's webkit fix.

**Comment by SoftVision-PaulOiegas** [comment]
Hi guys,

We verified the fix made by John for iOS problem and it seems ok. But sadly we performed some additional testing on the mobile side and we found several new issues on both iOS and Android platforms.
1. #2179 - [iOS] The page items from Test Pilot process description area are overlapped on Firefox and Safari browsers (mobile view)
2. #2180 - [Android] Native internet browsers wrongly overlap the experiment description with other experiments section 
3. #2181 - [Mobile] Footer links are wrongly alligned on Test Pilot related pages (About Test Pilot / Privacy / Terms)

I haven't mentioned any severity for the issues because I don't know how important you guys consider the mobile version.
