### ISSUE TITLE
Bulk invites with email notifications

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#216]
from #212 

"a way to invite users in bulk with email notifications. We can handle that in a future PR that adds such a tool to the Django admin. We'll need a background job queue (#163) to make that happen, too." -@lmorchard

**Comment by lmorchard** [comment]
More details from my head:
1. If we want to invite select subsets of profiles waiting to get in, [we can write new actions for Django admin.](https://docs.djangoproject.com/en/1.8/ref/contrib/admin/actions/) So, we'd write an action that takes selected profiles and 1) sends an email saying basically "you're invited!" and 2) sets `User.is_active` to True and `UserProfile.invite_pending` to False so that the account is activated by the time they might try signing in.
2. But, if we get to a point where we go fully open and want to invite ALL the users, it might be better to write [a Django management command](https://docs.djangoproject.com/en/1.8/howto/custom-management-commands/) for use at the command line that just sweeps through all profiles still pending invitation and sends out the welcome email
3. Might need to consider a case where we want to "pre-invite" someone by sending an email and making a record to auto-activate that person when we see their email address. This doesn't exist right now, and we rely on users already having attempted a sign-in that creates an inactive account.

If we're planning to just go fully open after a period of Mozillians banging on things, we might want to _just_ do 2 and handle exceptions on a one-off basis manually.

**Comment by clouserw** [comment]
wontfix
