### ISSUE TITLE
Enabling FlashPlayer - A lot of people CANNOT!!

### ISSUE THREAD

**Issue by TrevorMcKenna** [mozilla/testpilot#2174]
RE: please update your FlashPlayer it says to play videos... Adobe is a joke here is what I told my son this morn: - plus getting advice form ADOBE site might not help, as they poss pretnd there is nothing to see here, to maintain their image, of a 'can-do' software compnay, but as I said this is a problem I haven't been able to solve, but to-day is the day, as I want to watch catch-up etc. and am sick of that not being something I can do... plus on their site they have all the complaints about no-one being able to update Flashplayer, but no text on the SOLUTION!!! I think I am defeated on it, if you can't find tools in Firefox [big secret that one, great work], and what operating system, ADOBE don't even list my operating system VISTA!! So how can you win?

**Comment by treybigone** [comment]
RE: please update your FlashPlayer it says to play videos... Adobe is a joke here is what I told my son this morn: - plus getting advice form ADOBE site might not help, as they poss pretnd there is nothing to see here, to maintain their image, of a 'can-do' software compnay, but as I said this is a problem I haven't been able to solve, but to-day is the day, as I want to watch catch-up etc. and am sick of that not being something I can do... plus on their site they have all the complaints about no-one being able to update Flashplayer, but no text on the SOLUTION!!!  I think I am defeated on it, if you can't find tools in Firefox [big secret that one, great work], and what operating system, ADOBE don't even list my operating system VISTA!! So how can you win?

**Comment by SoftVision-PaulOiegas** [comment]
Hi @treybigone, I'm not sure I fully understand your problem. Are you unable to update Flash Player due to Test Pilot & experiments ? Or you are unable to update Flash player through Firefox browser in general ?

If it's the second problem, then I think you have logged your issue on the wrong location. All Firefox browser issues should be logged on https://bugzilla.mozilla.org/ page. 
This GitHub repository is only for Test Pilot and its experiments which are extensions that are not included by default in the browser.

**Comment by ckprice** [comment]
Sounds like a Firefox bug. Can you report per Paul's suggestion above?
