### ISSUE TITLE
New level of nesting on webextensions pings is inconsistent with SDK pings

### ISSUE THREAD

**Issue by sunahsuh** [mozilla/testpilot#2197]
While writing the ETL for SnoozeTabs I noticed we have a new level of nesting in the payload just for webextensions pings:
https://github.com/mozilla/testpilot/blob/master/addon/src/lib/metrics/webextension-channels.js#L141

Unless there's a different reason we have this field, senderAddonId is redundant with the addon ID in `payload/test`, and `testpilotPingData` is an unnecessary level of nesting which is also inconsistent with pings sent from SDK addons. Preferably we'd return to the previous format (data from the test inside `payload/payload` without nesting) but, barring that, we should at least make sure webextensions and SDK addons send their pings in similar formats.

**Comment by meandavejustice** [comment]
Looks like @dannycoates is marked in blame, https://github.com/mozilla/testpilot/blame/master/addon/src/lib/metrics/webextension-channels.js#L141 I think we can just pass the `data` object itself to `pingListener` itself and get rid of the `sender` parameter in `notifyPing` as @sunahsuh suggests.

**Comment by dannycoates** [comment]
I copied that directly from the old version https://github.com/mozilla/testpilot/blob/master/old-addon/lib/webextension-channels.js#L127

Comparing the previous code that sends the ping to the latest version I see no *new* level of nesting since the original commit last June https://github.com/mozilla/testpilot/commit/7738ed46ae7d96a29b724b11aec660e73a887952

When did we notice the change and are there any before/after examples?

**Comment by sunahsuh** [comment]
I just noticed this yesterday while working on data coming in from snoozetabs -- think it might be "new" since afaik snoozetabs is the first webextensions-based test. This is what it looks like now (python dictionary formatting quirks, sorry):
```
u'payload': {u'payload': {u'senderAddonId': u'snoozetabs@mozilla.com',
   u'testpilotPingData': {u'event': u'snoozed',
    u'snooze_time': None,
    u'snooze_time_type': u'next'}}
```

On the other hand, here's a payload from pulse, which is an sdk extension:
```
u'payload': {u'payload': {u'category': u'interactions',
   u'id': <uuid>,
   u'method': u'pulse-unloaded',
   u'object': None,
   u'type': u'user',
   u'variant': None},
  u'test': u'pulse@mozilla.com',
  u'timestamp': 1692,
  u'variants': None,
  u'version': u'0.1.0'},
```

**Comment by dannycoates** [comment]
Thanks @sunahsuh 

Maybe @lmorchard can shed light on the original intent, but we can certainly change it if we like.

**Comment by lmorchard** [comment]
If this is the same code as from June, then this isn't a **new** level of nesting for WebExtension based experiments. That is, this ping format might be incorrect—but it's not *new*—so changing it could break things.

Looks like [the Tracking Protection experiment uses this channel](https://github.com/mozilla/blok/blob/9cf3b504128b7a57ceb19f84ed806a462b4ba488/src/js/background.js#L307)—it was actually the first WebExtension experiment. How did we have things set up for pings there? Now might be a good time to change the implemented ping format since we're graduating Tracking Protection. Am I forgetting any other current WebExtension based experiments?

**Comment by lmorchard** [comment]
As for original intent, honesty I think we were just kind of winging it and hoping it was the right format. I don't remember closing the loop on the full metrics flow. Maybe @groovecoder can say how that all went with Tracking Protection?

**Comment by sunahsuh** [comment]
@lmorchard I checked the code that does the ETL for tracking protection pings and I do see this format there (I wasn't the author of that one). I still think it's worth being consistent with the format and it sounds like we'll still be releasing sdk experiments for the near future.

**Comment by lmorchard** [comment]
Should be easy to change in the Test Pilot add-on, but we'll have to get it done before the next round of deployment for Snooze Tabs. 

We *might* want to stick a conditional in there to use the old (incorrect) ping format when we see the Tracking Protection add-on ID, and switch to the corrected format for all future WebExtension experiments. Or, not, if we're okay with Tracking Protection pings switching to the corrected format
