### ISSUE TITLE
Interacting with add-ons causes "Test Pilot may be making Nightly run slow" message

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#2230]
I think `about:performance` is still a thing right?

Here is Test Pilot resting:

> Test Pilot currently performs well
>     Full name: @testpilot-addon.
>     Impact on framerate: 2/10 (6 alerts).
>     CPU usage: 1%.
>     System usage: 1%.
>     Blocking process calls: 0%.
>     Measure start: 263 seconds ago.
>     Processes: 25959 (parent), 25960 (child), 27690 (child)

The following happens after I do either

- [Snooze Tabs] Snooze a tab, then click "OK"
- [Pulse] Click on on the Pulse icon in the URL bar, then give it a star rating

The Test Pilot indicator jumps to red, and it reads:

> Test Pilot may currently be slowing down Nightly
>     Full name: @testpilot-addon.
>     **Impact on framerate: 8/10 (6 alerts).**
>     CPU usage: 2%.
>     System usage: 1%.
>     Blocking process calls: 0%.
>     Measure start: 363 seconds ago.
>     Processes: 25959 (parent), 25960 (child), 27690 (child)

The entries for Pulse and snoozetabs remains green and unchanged.

**Comment by jaredhirsch** [comment]
FWIW, the script on the `about:performance` page brought my Firefox profile to a crawl. I recently heard about a different profiling tool, which is described [on this MDN page](https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Profiling_with_the_Built-in_Profiler). There's an add-on that sends performance reports to https://cleopatra.io, which I think is intended to make it easier for end users to share performance data with FF devs.

In current release Firefox (51.0.1), when I click the snooze tabs button twice in a row, I see the error count increment on the `about:performance` entry for Test Pilot, and I see these two errors in the browser toolbox console:

<img width="992" alt="screen shot 2017-02-22 at 3 32 03 pm" src="https://cloud.githubusercontent.com/assets/96396/23237858/2226d442-f914-11e6-898d-5a37f41ee173.png">

The first error is indeed due to the hidden window's `navigator` not having a `sendBeacon` function. It looks like, if `beacon.enabled` was set to false (the uBlock Origin addon seems to have done this, others still might), then `navigator` won't have a `sendBeacon`. In #2151, I added some code that flips the `beacon.enabled` pref, _but_ the `sendBeacon` function isn't added until the browser is restarted. We'll need a `fetch` fallback for `sendBeacon`, filed as #2231.

The second error is thrown by native FF code when a popup is destroyed before its `browser` element has fully loaded--I think snooze tabs might have hit a bug in the WebExtension code? I filed https://github.com/bwinton/SnoozeTabs/issues/202 to track that error.

I'm fine to leave this open to track perf impact of fixing #2231, or we can close this out. ¯\_(ツ)_/¯

**Comment by ghost** [comment]
#2231 should fix the sendbeacon stuff.  we'll see how the rest is affected

**Comment by ckprice** [comment]
Took a couple videos showing both Snooze Tabs and Pulse (using #2276 branch).

- Snooze Tabs: https://drive.google.com/file/d/0B5T1SCKaYZL8NWhKMUp6dnFDQkU/view?usp=sharing
- Pulse: https://drive.google.com/file/d/0B5T1SCKaYZL8Sm1kMU5YSXpPeUk/view?usp=sharing

Both show interactions affecting `about:performance`.

**Comment by jaredhirsch** [comment]
It looks like about:performance complains about the Test Pilot addon if I open a new window on Nightly. Digging into whether the issue is related to the recent introduction of (synchronous) localstorage usage for variant storage.

**Comment by ghost** [comment]
Is this happening in places outside of Nightly?

Donovan suggests cross process object wrappers? 

Donovan is going to investigate this a bit more.  If it's only happening on Nightly, he'll deprioritize it.

**Comment by ghost** [comment]
This is, we think, fixed in Test Pilot, but not Test Pilot metrics.  Donovan will work to fix this sprint.

**Comment by fzzzy** [comment]
We got more info about this in the firefox meeting. 1) it only shows up in nightly and 2) there was consensus to just remove the warning, which I believe has been landed now.
