### ISSUE TITLE
Allow Test Pilot extensions to set approximate context for heartbeat notifications

### ISSUE THREAD

**Issue by april** [mozilla/testpilot#2236]
Last night I was just browsing the web (as you do) and I got a Test Pilot heartbeat notification asking me what I thought of No More 404s.  This was _very_ confusing, as I wasn't on a page with a 404 error.

This got me thinking: it would be great if extensions could set some kind of context as to whether or not it was an appropriate time for Test Pilot to ask for a heartbeat notification about them.  It would default to true (always on), but you could have contexts such as:

- No More 404s: Only Heartbeat on pages with 404s
- Min Vid: Only Heartbeat when a video is minimized

And so on.  This way, heartbeats could avoid being so jarring in the wrong context.

**Comment by johngruen** [comment]
@marumari, this is a little bit of an anti-pattern UX-wise, but we *want* the experience to be somewhat jarring and not performed strictly in the context of when the experiment is performing its intended function. 

The rationale here is that we want to understand how experiments are thought of, not at the moment of use but in a more general 'does this thing improve the overall experience of firefox' kind of way.

Nevertheless, lets keep this bug open since there might be some interesting targeted feedback we could do to make the experience a little less grating.

**Comment by dannycoates** [comment]
One thing I think we do poorly is we don't set the expectation that these are going to happen or explain why we do them, so when it does happen folks may be confused or annoyed because it's surprising, not because they don't want to help out. Of course people will think we prompt them in the wrong context, we don't set it in the first place.

**Comment by johngruen** [comment]
@dannycoates  to your point, I think this is partly a matter of setting expectation. I think we could fix this in an immediate way by explaining what's going to happen in either experiment or general onboarding.

**Comment by april** [comment]
Yeah, I had no context so it mostly just came off like all those feedback spam popups happen in Android/iOS apps.  I ended up disabling Pulse because I find it so similar to other annoying behavior that I've found grating in the past.

**Comment by april** [comment]
Err, it has been brought to my attention that this was a Test Pilot notification, not Pulse.  I guess it came right after installing Pulse so I misattributed where it came from.  Either way, I just wanted to say that these feedback popups are really frustrating in the wrong context.

**Comment by johngruen** [comment]
So we're gonna move away from our current notification strategy. Closing this bug for now. Will reference #2562 for future updates
