### ISSUE TITLE
Snooze Tab Issue

### ISSUE THREAD

**Issue by glarewolf** [mozilla/testpilot#2252]
Snooze Tab is an excellent idea that I am excited to see when it reaches its final stages. However, I cannot snooze any tabs as it doesn't give me the option to, it only allows me to see what tabs to manage. Yet, I cannot manage any tabs because I can't snooze any tab at all. In addition, it is very slow to open if it opens at all sometimes. #2218

**Comment by johngruen** [comment]
Hey @glarewolf this issue should probably be moved to the snoozetabs repo, but let me see if i understand correctly. Can you provide a concrete example of the steps you're taking to produce this issue. (eg. is there a specific site you're on)

**Comment by glarewolf** [comment]
Its any and all sites that I can't snooze and how would I move this?

**Comment by SoftVision-EmilPasca** [comment]
Thank you for reporting this @glarewolf.

If you click on the SnoozeTabs button in the toolbar for one of the "special tabs" e.g: a new tab(about:newtab), about:addons, about:preferences, about:config or browsing using the "Private Window" mode, the snoozing options won't be available. However the "Manage SnoozeTabs" panel will be displayed in which you can edit or delete your currently snoozed tabs.

There is also a known issue (https://github.com/bwinton/SnoozeTabs/issues/197) that SnoozeTabs doesn't work on Test Pilot site due to very strict CSP security settings and may be the same cause with your websites. When clicking the SnoozeTabs toolbar button and choosing a snoozing option such as "Later Today", "Tomorrow"  or any other snoozing options, the tab doesn't get snoozed.
Is this the same scenario you are encountaring with your sites? Could you please specify some of the websites where this issue is present?
