### ISSUE TITLE
Nor Snooze Tabs neither Pulse are being offered

### ISSUE THREAD

**Issue by kekkyojin** [mozilla/testpilot#2265]
It has being some time since it is possible to test Snooze Tabs and Pulse. However, they are not appearing in my Test Pilot page.

Firefox 51.0.1 es_ES
macOS 10.12.3 es

**Comment by lmorchard** [comment]
Hmm, looks like `es_ES` is not listed in [the `locale_grantlist` for Snooze Tabs](https://github.com/mozilla/testpilot/blob/master/content-src/experiments/snooze-tabs.yaml#L6). Could just add that locale. But, do we actually need that list? Or can we just have the English locale warning while opening it up to everyone until/unless we have proper l10n? 

/cc @ckprice @johngruen @flod (since I see you folks worked on the YAML for Snooze Tabs)

**Comment by lmorchard** [comment]
Possibly fixed when #2279 lands?

**Comment by ghost** [comment]
This will be fixed when #2279 is fixed

**Comment by SoftVision-PaulOiegas** [comment]
Both experiments are displayed now on [es-ES] locale but Snooze Tabs experiment page wrongly displays placeholders instead of default [es] translation. Logged this separately in #2301.
