### ISSUE TITLE
Show also tests for other languages

### ISSUE THREAD

**Issue by writtmeyer** [mozilla/testpilot#2277]
The reasons why I activated testpilot in the first place was the announcement of snooze tabs. Alas, after installing testpilot that was not available. Okay, maybe I give it a few days? But, no, even a week or so later, it's still not there. 

So I googled. And found it. But it was not available for my language (German). Holy cow! That's way too strict. I suggest to show all available tests but to show those that are not available in the users language to be shown beneath the currently active tests for my language. Maybe separated by a differently colored (other shade of blue) background. And they should have some kind of annotation so that the user can quickly recognize which language this test is mainly targeting).

That way users can decide whether they consider themselves to be proficient enough in those other languages or not. 

It would increase the testing base for tests and would help users find more tests and thus keep interested in and engaged with testpilot.

**Comment by writtmeyer** [comment]
Ah, one more: Now that I have activated snooze tabs, I still cannot see it in the test pilot start page and thus not manage it. And the site of the test itself where I can add it shows me "add it" instead of "deactivate it".

**Comment by ghost** [comment]
Fixing #2278 will fix the original issue.  How did you end up enabling snooze tabs?  Did you flip your language pref?  (If so, did you flip it back when you were done?)

**Comment by AdrianoCahete** [comment]
I don 't know if you guys change something, but when i (pt-BR) open the Snooze Tabs URL, shows:
![testpilot_1](https://cloud.githubusercontent.com/assets/37474/23562216/591be89e-0020-11e7-8a58-9b04e53c8f32.PNG)

Who is "This experience isn't avaliable in your language, but you can enable if you want". So, you can enable, but not manage.

**Comment by writtmeyer** [comment]
Exactly, Adriano. That's how I enabled it. I cannot diable it, though, on the same page. It always asks me if I want to enable it.

**Comment by SoftVision-CosminMuntean** [comment]
@wresuolc, based on last two comments, I think that this issue is related to #2189.

I have managed to reproduce this issue. If I change the Firefox content page to German [de] language from "about:preferences#content", Snooze Tabs is not available on Test Pilot (known issue #2278). 
If I manually navigate to "https://testpilot.firefox.com/experiments/snooze-tabs" the experiment can be enabled. After enabling the experiment, it is displayed as "enabled" on the Test Pilot experiment details page, but if the page is refreshed the experiment is no longer displayed as enabled, even if the functionality is present. 
Here is a screen recording with the issue: https://goo.gl/APafUT
This is the same behavior described in issue #2189. Is also reproducible with Portuguese/Brazil [pt-br] language.

@writtmeyer  , @AdrianoCahete , if I understand correctly, this is the encountered issue?

**Comment by writtmeyer** [comment]
Yes. That's exactly the issue. Keep in minds that some might prefer those experiments not to show up or at least less prominently. That's why I suggested to add those with another language to appear beneath those for the users's locale and somehow separated (e.g. by color).

**Comment by AdrianoCahete** [comment]
> if I understand correctly, this is the encountered issue?

Exactly. Note that Test Pilot is usable, works normally, but you can't disable after enabled.

**Comment by johngruen** [comment]
@SoftVision-CosminMuntean will review

**Comment by SoftVision-CosminMuntean** [comment]
In the current behavior Snooze Tabs and Pulse experiments are no longer restricted for certain locales and are correctly displayed on Test Pilot home page (fixed by #2278). The experiments are successfully enabled and are displayed as such even if the browser is restarted.

However, I have retested this issue is no longer reproducible. In order to test it I have used Activity Stream which is restricted for German [de] language and also Cliqz which is available only for German language. 
I also think that this issue is a dupe of #2189, which is fixed and verified.
