### ISSUE TITLE
settings icon

### ISSUE THREAD

**Issue by jegoddar** [mozilla/testpilot#2284]
The Settings icon in the new Share button matches the current Windows 10 icon, but a new Share icon was introduced in build 15031 of Windows 10. Please consider updating the Share icon in March or April, when the Windows Share icon update is officially rolled out to the public.

**Comment by SoftVision-CosminMuntean** [comment]
Hi @jegoddar,

To which new Share button do you refer? Is it the Activity Steam Share button?
Can you please attach a screen shot or a screen recording with the new Share button?

**Comment by jegoddar** [comment]
Hmm... Looks like it's an update to an [existing icon](https://support.mozilla.org/t5/Chat-and-share/Share-a-webpage-through-Firefox-Share/ta-p/38200) and I just noticed the change when looking at the Test Pilot experiments. Nonetheless, here's my screenshot.
![firefox share icon](https://cloud.githubusercontent.com/assets/26193991/23638636/703b337e-02a8-11e7-8562-3261f398ef27.png)

**Comment by SoftVision-CosminMuntean** [comment]
Hi @jegoddar , thanks for the information.

The button that you mention is the Activity Stream "Share" button. That's why you observed the icon after using Test Pilot. Probably you have enabled the Activity Stream experiment from Test Pilot. 
Unfortunately Activity Stream Share functionality was removed in the latest version (1.6.0). 

However, the Firefox [Share ](https://support.mozilla.org/t5/Chat-and-share/Share-a-webpage-through-Firefox-Share/ta-p/38200)functionality is still available and you can find it in "Additional Tools and Features" section from Firefox menu -> Customize. 
If you consider that the Firefox Share icon should be updated you can log a new issue in Bugzilla: https://bugzilla.mozilla.org/
