### ISSUE TITLE
All are working fine. Got error to the Testpilot webpage few times. But later works OK.

### ISSUE THREAD

**Issue by linuxlover** [mozilla/testpilot#2292]
Thank you for contributing to Test Pilot!

Please use this form to report Test Pilot specific issues. If you think you've found an issue with one of the experiment add-ons, please file an issue in the appropriate repo below:

- Activity Stream:      https://github.com/mozilla/activity-stream/issues/new
- Containers:           https://github.com/mozilla/testpilot-containers/issues/new
- Min Vid:              https://github.com/meandavejustice/min-vid/issues/new
- Page Shot:            https://github.com/mozilla-services/pageshot/issues/new
- Pulse:                https://github.com/mozilla/pulse/issues/new
- Snooze Tabs:          https://github.com/bwinton/SnoozeTabs/issues/new
- Tab Center:           https://github.com/bwinton/VerticalTabs/issues/new
![2017-03-07_11-29-49](https://cloud.githubusercontent.com/assets/3076938/23674298/502d261e-032a-11e7-9024-6d9c8e603cbf.png)

**Comment by chuckharmston** [comment]
@linuxlover Thanks for the report! Do you have any antivirus software installed?

**Comment by linuxlover** [comment]
I'm using Avast.
The website working most of the time. Only few times I got this error message.
Been a regular user of TestPilot but this error message pops up few times only today.
Not sure why.
Thanks

**Comment by chuckharmston** [comment]
@linuxlover Unfortunately, this is due to Avast. It adds a root certificate to Firefox's store, which allows it to intercept and decrypt encrypted web traffic. Changes in newer versions of Firefox (which you likely received in the last day or two) are noticing this and are more aggressively blocking it, since it opens up security holes.

More information about the feature and instructions on disabling it here: https://blog.avast.com/2015/05/25/explaining-avasts-https-scanning-feature/
