### ISSUE TITLE
Can't minimize tab center left column

### ISSUE THREAD

**Issue by transmetent** [mozilla/testpilot#2297]
Just it.

Can't minimize tab center left column.

Firefox 52.

Ubuntu 16.04

**Comment by ghost** [comment]
Tab Center bugs are tracked at https://github.com/bwinton/TabCenter/issues .  If you file there, please include all the information you can and some steps to reproduce the problem.  How many tabs are open? Are any tabs pinned?  What version of tab center? Are you saying when you mouse away from the tabs it doesn't shrink?  What happens when you toggle the auto-shrink button?

For the record, I'm on ubuntu with Nightly and the "Shrink sidebar when not in use" button works as expected for me.

Oh -- also what other add-ons you have installed.  Tab Center is incompatible with a bunch of other add-ons.
