### ISSUE TITLE
[release] 2017-03-13 is on Stage

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#2316]
Please QA stage. Let's use this issue to track deployment status to production. I've assigned this to Paul, but we should all be checking out stage a bit.

- Verification documentation: https://github.com/mozilla/testpilot/blob/master/docs/development/verification.md
- Release notes: https://github.com/mozilla/testpilot/releases

Current diff from production: https://github.com/mozilla/testpilot/compare/production-static...stage-static

http://testpilot.stage.mozaws.net/

**Comment by SoftVision-PaulOiegas** [comment]
Hi guys,

The Stage server seems to be seriously affected on the localization side. Here are the new issues found after our round of testing:

### **New issues:**
1. #2317 - Multiple UI issues on Test Pilot pages on stage server (Critical)
2. #2318 - Localization is not working in other language than English (Critical)
3. #2319 - Missing space between "in" string and "this Privacy Notice" link from the Newsletter section (Minor)

### **Known issues:**
1. #2301 - Snooze Tabs page wrongly displays placeholders for [es-es] locale and does not fallback to [es] or [en] locales 
- Cannot be verified due to localization issues from stage server.

If the above critical issues cannot be fixed in time today (next hour). Probably we should postpone the production deploy for tomorrow since we will be unable to test it today.

**Comment by ghost** [comment]
This is out. Thanks!
