### ISSUE TITLE
Notify user of missing mozAddonManager

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#2364]
@fzzzy will be removing the non-`mozAddonManager` paths with this release. Since those APIs have specific prerequisites, including an about:config pref, we may see some mysteriously broken behavior like that experienced this morning if any of those prerequisites are not hit.

To remediate, we should check for the existence (`!!navigator.mozAddonManager` should suffice) on  startup, notify the user if any of them are not met, and suggest steps for fixing it.

I'd suggest the following logic to determine messaging.

1. `window.location.protocol === 'https'`
    - If not, tell the user to make sure they are accessing on that protocol.
2. Firefox version is >= 49 ~47 (double-checking that that's when `mozAddonManager` shipped~.
    - If not, tell the user to update.
3. `!['example.com', 'testpilot.dev.mozaws.net', 'testpilot.stage.mozaws.net'].includes(window.location.host)`
    - If not, tell the user that they need to set `extensions.webapi.testing`.
4. `window.location.host !== 'testpilot.firefox.com'` 
    - If not, tell the user that they must access Test Pilot on an approved hostname.
5. Tell the user that they should file a bug because we have no idea what's going on.

~It is very likely that this is only seen on dev or stage, but there's no reason to not build this to be something that we're comfortable shipping on production.~ When [bug 1359837](https://bugzilla.mozilla.org/show_bug.cgi?id=1359837) lands, there's a very reasonable way production users may run into this. To accommodate, we should also disable the install button with appropriate messaging.

**Comment by fzzzy** [comment]
Not this release -- the old code is still in place for now. But I will remove the old path fairly soon.

**Comment by fzzzy** [comment]
@chuckharmston If you have some time this sprint, do you feel like doing this? It should be really straightforward.

**Comment by chuckharmston** [comment]
See this bug for another place where mozAddonManager may be prevented in the future: https://bugzilla.mozilla.org/show_bug.cgi?id=1359837

**Comment by ghost** [comment]
If a user has the pref mentioned in bug 1359837 flipped, they'll see an install dialog followed by an error message here.  The biggest use case for that pref is managed workstations who have admins who flip it.

marking needs UX for how we want to communicate to the user and cc @johngruen .  This feels like a pretty slim audience (@chuckharmston is asking about how many people were talking about) but this issue is blocking landing the patch in the bug.

edit: didn't mean to close

**Comment by fzzzy** [comment]
Time to get going on this soon.

**Comment by johngruen** [comment]
Will bring it up in the UX meeting; no reason we can't crank something out ASAP

**Comment by fzzzy** [comment]
@johngruen Since this will only be seen by a small number of users that try to test Test Pilot locally, on stage, or on dev, but have something misconfigured, I don't think much UX is required. I did a simple implementation, here are examples of what it looks like in various error cases:

<img width="982" alt="screen shot 2017-05-25 at 2 25 07 pm" src="https://cloud.githubusercontent.com/assets/46048/26464577/3a5a513a-4156-11e7-8625-0fe02e368112.png">

<img width="982" alt="screen shot 2017-05-25 at 2 25 36 pm" src="https://cloud.githubusercontent.com/assets/46048/26464588/4350eb78-4156-11e7-9248-db6f35d00ae9.png">

**Comment by flodolo** [comment]
As asked in the past, please ping when there are pull requests with strings (plus #2532)

**Comment by fzzzy** [comment]
@flodolo Sorry about that. We will work on setting up a localization branch next quarter so this process is more formalized.
