### ISSUE TITLE
Add selenium UI tests

### ISSUE THREAD

**Issue by b4handjr** [mozilla/testpilot#2376]
@krupa @pdehaan
Starting this issue to keep track of my work.

I am adding a few ui tests as well as checking to make sure the test pilot addon installs correctly.

**Comment by SoftVision-PaulOiegas** [comment]
Hi @jrbenny35. I'm Paul, one of the Team leads of the Softvision QA Engineering team that deals with manual testing of Test Pilot and most of the experiments.
I was thinking that maybe some of our manual tests would help you with the automation tests you are designing. You can find them [here](https://docs.google.com/spreadsheets/d/1FZI3FZ_MgRjXQavimuamqfPRyzThnBiE4w-q9qTTu0I/edit#gid=557160182). It's not the latest version since we're using TestRail tool for all our tests, but if you have access you can always check them [there](https://testrail.stage.mozaws.net/index.php?/projects/overview/3).

Hope it helps. If you have any questions or you need anything, please let me know. 😃

**Comment by ghost** [comment]
@jrbenny35 is this ready to be closed?

**Comment by b4handjr** [comment]
Yup. Closing.
