### ISSUE TITLE
Newsletter submission should include a "source_url" parameter

### ISSUE THREAD

**Issue by pmac** [mozilla/testpilot#2392]
The email marketing team would very much appreciate you adding this parameter. It'd be best to send the value as the current URL of the page, but if you'd rather hard-code "https://testpilot.firefox.com/" that works for us as well.

**Comment by ScottDowne** [comment]
Hey all, figured I would pick up another few small bugs while I had some time between campaigns.

I used the hard coded url because that's what I've used with my previous basket interactions, but happy to change it to something along the lines of `window.location.origin + window.location.pathname` or something else.

Thoughts?

**Comment by pmac** [comment]
👍 from me. It might be best and more future proof to use the `window.location.*` values, but this is better than what we have and is probably more robust. Are there multiple URLs at which the newsletter form currently lives on testpilot.f.c?

**Comment by lmorchard** [comment]
The newsletter form lives in the footer on all pages of Test Pilot, but I'm not sure we're all that worried about getting granular

**Comment by pmac** [comment]
The email marketing team is pretty worried about it from what I understand, but this is a step forward. Thanks!
