### ISSUE TITLE
Test pilot website bypasses xpinstall.enabled = false

### ISSUE THREAD

**Issue by mkaply** [mozilla/testpilot#2398]
The test pilot website installs the Test pilot add-on even if xpinstall.enabled is set to false (and locked).

It should honor this preference and not install the add-on if installations are blocked by an administrator.

**Comment by chuckharmston** [comment]
If the purpose is security, I’d suggest that the issue should be fixed in the browser, not on the website. Two primary reasons:

1) The website doesn’t have a way to know what the value of that preference is.
2) We install add-ons from the website using mozAddonManager, a WebAPI mirroring the SDK AddonManager that is granted by the browser to webpages on a very small whitelist of websites. Since it’s a web API, any user has access to it from the developer console while browsing Test Pilot’s website. So even if we did have a way to read that preference, it wouldn’t prevent users from subverting administrator intent to install add-ons.

I’d propose that the fix for this would be to not provide that API to the Test Pilot website at all if `xpinstall.enabled` is `false`.

I'm closing this, but will file a bug for that on Bugzilla and CC you.
