### ISSUE TITLE
[release] 2017-05-04 is on stage

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#2416]
Please QA 2017-05-04 on stage.

**Comment by SoftVision-CosminMuntean** [comment]
Hi guys,

Here is the testing report for the Stage server:

### **New issues (not yet logged):**
1. The hint tooltips for the email field and for the privacy ceckbox do not persist if the "Sign Up Now" button is clicked (only on latest Firefox (53.0) release)
- This is a Firefox issue that was introduced in Beta 53.0b2, but it seems that is no longer reproducible on Beta 54.

- Considering this I have performed a regression range in order to find the issue that caused this. Here are the results:
Last good revision: a5ccc32310c9a424ccb4f5106f5155ca20dd360a
First bad revision: ea823a8262ac96b7150df0a41beb2ba5e40fe89c
Pushlog: https://goo.gl/F61vOk
One of these bugs introduced the issue. We suspect [Bug 1109868](https://bugzilla.mozilla.org/show_bug.cgi?id=1109868). 

- I have also performed a "find fix" regression range in order to find the issue that fixed this.
Unfortunately I have obtained a large pushlog, due to the fact that all the changesets are in the same push. 
Pushlog: https://goo.gl/AqhAc7

### **Known issues**

[#1866](https://github.com/mozilla/testpilot/issues/1866#issuecomment-292979056) - The confirmation pop up with the Tour is not displayed anymore if first enable action fails.
#2366 - The enabled experiments are not removed at Test Pilot uninstall

**Comment by ghost** [comment]
Thanks!  We think these are ok to go forward with
