### ISSUE TITLE
Test Pilot can cause huge performance issues in Firefox (especially on Linux) with Telemetry turned on

### ISSUE THREAD

**Issue by ehsan** [mozilla/testpilot#2422]
See this Mozilla bug https://bugzilla.mozilla.org/show_bug.cgi?id=1360702 and this profile: https://perfht.ml/2pHdFkY

Test pilot is calling `getCurrentPingData` for some reason with a very high frequency.  That function is generally very expensive and on Linux it can be *extremely* expensive.  This made my real browsing profile so bad that I had to turn off telemetry for a few days in order to get a usable web browser.

Test pilot should only call `getCurrentPingData` a few times per browser session at maximum.

(Please note that I rarely look at github notifications unfortunately so sadly if you have any questions from me asking on github is probably not a great way to get in touch.  Sorry for this...)

**Comment by lmorchard** [comment]
Looks like we're calling this in [`addon/src/lib/Telemetry.js`][1] and [`addon/src/lib/metrics/experiment.js`][2] to assemble contextual data for Ping Centre metrics event submissions. How often does this context change? Maybe we can cache it super aggressively / only ask for it at startup? /cc @6a68 since I see your name on these lines

[1]: https://github.com/mozilla/testpilot/blob/master/addon/src/lib/Telemetry.js#L95
[2]: https://github.com/mozilla/testpilot/blob/master/addon/src/lib/metrics/experiment.js#L64

**Comment by Dexterp37** [comment]
Mh, from a quick look this seems to be doing:

- Calling `TelemetryController.getCurrentPingData` to get the *ping structure*. Note that this method gathers all the data required for the `session ping` (aka [main-ping](https://gecko.readthedocs.io/en/latest/toolkit/components/telemetry/telemetry/data/main-ping.html)) and it's quite expensive.
- It then [overrides](https://github.com/mozilla/testpilot/blob/master/addon/src/lib/Telemetry.js#L96-L97) the gathered `main-ping` payload with the one passed in, making all the heavy lifting gathering it in the previous step useless.

Is this the right interpretation? Are we doing that because we need the `environment` and the `clientId` sections?

**Comment by georgf** [comment]
The only data from the main ping i see the test pilot code using here is the environment data.
You can get that much much cheaper using `TelemetryEnvironment.currentEnvironment`.

**Comment by jaredhirsch** [comment]
> The only data from the main ping i see the test pilot code using here is the environment data.
You can get that much much cheaper using TelemetryEnvironment.currentEnvironment.

Great! I'll switch to that

**Comment by EricRahm** [comment]
You can see the issue in the existing [profile](https://perfht.ml/2pHdFkY): I select 'Invert call stack', if you expand that a few rows we see `GetProcSelfSmapsPrivate`, expand further we see telemetry show up, and even further it's an entry in test-pilot.

![screenshot from 2017-05-12 11-41-08](https://cloud.githubusercontent.com/assets/426919/26012225/b1dc2eb6-3708-11e7-8ad8-b40043d0f141.png)

Ideally in a new profile with test-pilot enabled and your fixes we wouldn't see `__read` at the top. _Note: to reproduce I believe this was a 5 minute profile run on Linux (Linux is important here)._

**Comment by jaredhirsch** [comment]
Thanks so much for uploading some instructions and a screenshot!

I'll try to repro the current issue on my ubuntu laptop, then switch to just check `TelemetryEnvironment.currentEnvironment` once, at startup, and cache that value, then see how the profiles differ.

**Comment by Dexterp37** [comment]
> I'll try to repro the current issue on my ubuntu laptop, then switch to just check TelemetryEnvironment.currentEnvironment **once, at startup, and cache that value,** then see how the profiles differ.

There's no need to cache if you use `TelemetryEnvironment.currentEnvironment`, as the environment might change during the lifetime of the browsing session and `TelemetryEnvironment.currentEnvironment` always contains the most recent cached copy.

**Comment by georgf** [comment]
Hey @6a68, this is showing up repeatedly in quantum flow triaging etc. and distracts from other problems
Can we get this fixed so we don't skew performance profiles with it anymore?
Thanks.

**Comment by georgf** [comment]
A short-term fix here would be great if the bigger change is taking more time.

**Comment by jaredhirsch** [comment]
@georgf Hi, sorry about the delay. I'll get the fix landed today or tomorrow. Our next planned addon release isn't until June 20, but it sounds like it might be good to do a special release sooner than that. I'll look into an off-cycle release.

**Comment by jaredhirsch** [comment]
This change has been released in the latest addon, which has a version number "1.1.3-dev.ba83fba".
