### ISSUE TITLE
Add and implement max_release field for experiments

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#2424]
We currently have a [`min_release`](https://github.com/mozilla/testpilot/blob/master/docs/content/reference.md#min_release) field for experiments to require a minimum Firefox version for installation. We have a new need for a `max_release` field that behaves similarly, but prevents installation for Firefox versions beyond a maximum.

**Comment by ghost** [comment]
This is pretty much copying the max_release code and s/>/</g so let's do it.  Don't forget to update the docs and example yaml file.

**Comment by meandavejustice** [comment]
What do we want the copy to be for the notice when a version is too high? 

"Experiment name requires Firefox 99 or earlier."
Seems like we should recommend "release" channel instead of linking to something like: https://support.mozilla.org/en-US/kb/install-older-version-of-firefox?redirectlocale=en-US&redirectslug=Installing+a+previous+version+of+Firefox

![](https://raw.githubusercontent.com/mozilla/testpilot/master/docs/content/img/min_release.png)

**Comment by johngruen** [comment]
@meandavejustice yeah that seems right. Maybe something like:

"${experiment.name} is not supported in Firefox Beta or Firefox Nightly." 

or "${experiment.name is not supported in Firefox Nightly."

I don't think we want to link users to the old releases page, maybe just 

"Get the current version of Firefox." with a link to https://www.mozilla.org/en-US/firefox/

**Comment by meandavejustice** [comment]
@johngruen Yesterday I decided on the screenshot below, just to get it into review. What do you think of that?

![](https://raw.githubusercontent.com/meandavejustice/testpilot/c8c3d6924f0c2bb401466750a025a6bbcb813eb7/docs/content/img/max_release.png)

**Comment by johngruen** [comment]
${experiment.name} is not supported in this version of Firefox.
Get the current version of Firefox.

**Comment by meandavejustice** [comment]
![](https://raw.githubusercontent.com/meandavejustice/testpilot/38d1d842f76ef887b3377048c90ca6cbdfa6379c/docs/content/img/max_release.png)
