### ISSUE TITLE
Move pontoon commits to a branch

### ISSUE THREAD

**Issue by fzzzy** [mozilla/testpilot#2430]
We should tell pontoon to put commits on a branch, then only open a pull request for all the pontoon stuff once a sprint. This will cut down a lot on both #testpilot-bots spam and on circleci load.

Remaining steps (per @lmorchard):

- [x] Get testpilot-l10n.dev.mozaws.net working as an approved host name
- [x] Add l10n environment to add-on
- [x] Create an l10n branch on this repo
- [x] Update CircleCI to auto-deploy the site to the new dev server on l10n branch commits
- [x] [Bug 1393106](https://bugzilla.mozilla.org/show_bug.cgi?id=1393106) - Ping pontoon folks to move commits over to l10n branch, after all the above is done
- [ ] Consider any git automation that might help keeping master & l10n branches in sync (might need to be a manual post-deploy process?)
- [ ] Consider any test automation steps that might help make sure we run PRs through l10n branch before master
- [ ] Document the new l10n process

**Comment by ghost** [comment]
@flod if we do this we lose the string preview on -dev (until we merge it in).  Is that important to have?

**Comment by ghost** [comment]
er, I mean @flodolo ^

**Comment by flodolo** [comment]
Yes, it's important to have a dev server that works against that branch (also cc @mathjazz).

I'm fine in having Pontoon committing to the branch, but we owe localizer an easy and automated way to check their work.

**Comment by lmorchard** [comment]
Just had a brief thinking-out-loud about this on IRC... what if in addition to a branch and a second l10n-specific dev instance, we had a little more process too:

1. When there are new strings, we submit a pull request from `master` branch to an `l10n` branch.
1. Strings in that PR get reviewed / revised as needed, then merged into `l10n`
1. Commits from localizers on Pontoon flow into `l10n` branch.
1. When we decide we're ready to ship the locales, we submit a PR with a single squashed commit back to `master` - this will cut down on the number of commits in `master` history.

The wrinkle here, though, is squashing commits destroys [contributor attribution](https://github.com/mozilla/testpilot/graphs/contributors) when we have it - because git only supports a single author & committer per commit. 

So, if we did squash masses of Pontoon commits down to one, can we find another way to attribute the work of l10n contributors? (e.g. an API we can hit on Pontoon to get a contributor list and publish it on the site?)

**Comment by mathjazz** [comment]
> So, if we did squash masses of Pontoon commits down to one, can we find another way to attribute the work of l10n contributors? (e.g. an API we can hit on Pontoon to get a contributor list and publish it on the site?)

No such thing [yet](https://bugzilla.mozilla.org/show_bug.cgi?id=1302053). If you have more detailed API requests in mind, please add them to the bug. We're expecting to spec this out at the end of the quarter at Pontoon all hands.

Not sure if this is helpful, but we also attribute localizers in Pontoon:
https://pontoon.mozilla.org/projects/test-pilot-website/contributors/

**Comment by lmorchard** [comment]
Quick update - it's not entirely working yet ("Unapproved hostname!" error), but I have a start on a new dev server just for an l10n branch:

https://testpilot-l10n.dev.mozaws.net/

Next steps (moved to issue description)

**Comment by lmorchard** [comment]
Ah, crud, hit a roadblock: We can't set up a new Test Pilot dev environment that has access to mozAddonManger without getting a change made to [the whitelist of allowed hosts hardcoded in Firefox](https://dxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/AddonManagerWebAPI.cpp#45)

So, two options (not mutually exclusive):

1. We make the site fail as gracefully as possible without mozAddonManager so that localizers can at least browse to see string changes
1. We lobby to add `testpilot-l10n.dev.mozaws.net` to this whitelist

It's a Big Deal to expose this API to more hosts, so it would be good to just fall back to mocking out the experiment install functionality

**Comment by lmorchard** [comment]
The auto-deployment changes have been merged, so now any commits to the `l10n` branch will appear here:

https://testpilot-l10n.dev.mozaws.net/

Also, I softened the restrictions requiring access to `mozAddonManager`. That means the l10n server is browseable but does not entirely work, because its not whitelisted for access to the addon manager APIs in Firefox.

**Comment by flodolo** [comment]
That's great to see progress on this, thanks!

What are the next steps? Are we already at a point where we should start committing to the branch?

**Comment by lmorchard** [comment]
[A couple of next steps left](https://github.com/mozilla/testpilot/issues/2430#issuecomment-322912085), but basically a) move Pontoon commits to the new branch and b) see if I can come up with a test script that fails if we try committing en-US string changes to master before l10n

**Comment by lmorchard** [comment]
Filed [bug 1393106](https://bugzilla.mozilla.org/show_bug.cgi?id=1393106) with the Pontoon team to switch commits from master to l10n.

<strike>We should hold off on requiring that PRs with string changes go through the l10n branch yet. But, once Pontoon moves over there, that should become our new process.</strike>

And now the change has been made: Pontoon commits to l10n branch, now. So, any PRs with string changes should be submitted against l10n branch for string review. Merging into l10n is now how we request localizations and merging from l10n to master is how we ship localizations.

**Comment by lmorchard** [comment]
Had an IRC discussion that made me think maybe we need a few more branch process tweaks:

https://public.etherpad-mozilla.org/p/testpilot-new-branch-process

**Comment by flodolo** [comment]
This approach would also solve one of my main grudges with Test Pilot, which is A landing on Wednesday night, right in time for for Thursday tagging.
