### ISSUE TITLE
Wayback Machine jumps the gun!

### ISSUE THREAD

**Issue by Jdsgames** [mozilla/testpilot#2471]
Thank you for contributing to Test Pilot!

Please use this form to report Test Pilot specific issues. If you think you've found an issue with one of the experiment add-ons, please file an issue in the appropriate repo below:

- Activity Stream:      https://github.com/mozilla/activity-stream/issues/new
- Containers:           https://github.com/mozilla/testpilot-containers/issues/new
- Min Vid:              https://github.com/meandavejustice/min-vid/issues/new
- Page Shot:            https://github.com/mozilla-services/pageshot/issues/new
- Pulse:                https://github.com/mozilla/pulse/issues/new
- Snooze Tabs:          https://github.com/bwinton/SnoozeTabs/issues/new
- Tab Center:           https://github.com/bwinton/VerticalTabs/issues/new

No more 404s many times when connecting to sites with CloudFlare enabled it will ask if I want to use the Wayback Machine although the page is still online. That or if it seems to load slightly slower than normal it will also ask even though the site is still online and just loading slowly.

Suggestion: Push the delay a little so it doesn't want to pop up before it knows the page is actually offline.

**Comment by SoftVision-PaulOiegas** [comment]
Hi @Jdsgames and thanks for the report. I' don't think that Test Pilot team could help here since the experiment graduated. 

Could you please re-log your issue on the repository used for the NoMore404s development ([link](https://github.com/internetarchive/wayback-machine-firefox/issues))? Cannot guarantee a quick answer there, but I think your issue could have a better chance for fixing there.

Closing this in the meantime. Thanks !
