### ISSUE TITLE
Idea-town splash pages scroll vertically

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#249]
Tested in FF and Chrome.

http://idea-town-dev.elasticbeanstalk.com/

Even when viewing the pages on my big monitor @1413px high, I notice that the pages scroll ~6px (which seems to be the exact height of the [`border-top`](https://github.com/mozilla/idea-town/blob/5c2f837ee8a47680f32bef493c5e77ba2b1eacd6/idea_town/frontend/static-src/styles/_theme-helpers.scss#L34) bar in [_cta-view.scss:19](https://github.com/mozilla/idea-town/blob/5c2f837ee8a47680f32bef493c5e77ba2b1eacd6/idea_town/frontend/static-src/styles/modules/_cta-view.scss#L19) above the Tabzilla tab).

**Comment by chuckharmston** [comment]
I don't have enough time to get up a PR, but this is fixed in dev tools by changing [this line](https://github.com/mozilla/idea-town/blob/5c2f837ee8a47680f32bef493c5e77ba2b1eacd6/idea_town/frontend/static-src/styles/_base.scss#L72) to `min-height: calc(100vh - 6px)`. Fair chance that value is exposed as a variable in Tabzilla somewhere.

**Comment by pdehaan** [comment]
I can't seem to reproduce this, so I'll blame https://github.com/mozilla/idea-town/pull/250 for fixing this.
