### ISSUE TITLE
[release] 2017-06-01 on stage

### ISSUE THREAD

**Issue by fzzzy** [mozilla/testpilot#2491]
Please report issues here.

**Comment by SoftVision-CosminMuntean** [comment]
Hi guys,

Here is the testing report for the Stage server:

### New Issues
#2497 - A "-" symbol is wrongly displayed on all experiments details pages if Test Pilot is not installed - **minor**

### Known issues
#2366 - The enabled experiments are not removed at Test Pilot uninstall
#1866 - The confirmation pop up with the Tour is not displayed anymore if first enable action fails.
#2473 - Experiments images are not displayed on Facebook and Activity Stream one is not displayed on Twitter

The new issue found is a minor one so it would not affect a release. However, we would like to raise attention on #2366, which has now 2 months since logging and no solution was found for it yet. We consider the issue quite important, even if the behavior is met when an user leaves Test Pilot.
