### ISSUE TITLE
Ensure AWS S3 access can use IAM credentials from EC2 instance metadata

### ISSUE THREAD

**Issue by mostlygeek** [mozilla/testpilot#252]
The preferred way for applications running in AWS is to use IAM role permissions. These are available through [ec2-metadata](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html) that boto and other AWS libraries can automatically pull out. 

The application shouldn't even be setting these values directly. The preferred way is to allow the AWS sdk library to decide on values from the environment, from ec2 metadata, etc. 

Please remove these values from the configuration.

**Comment by lmorchard** [comment]
For context, [an issue comment](https://github.com/jschneier/django-storages/issues/34#issuecomment-124002532) about this suggests that just making these settings default to `None` will cause Boto 2.38.0 to [populate the keys from EC2 metadata](https://github.com/boto/boto/blob/2.38.0/boto/provider.py#L379). Hope that's true! :)

**Comment by mostlygeek** [comment]
If they are not in the environment variables will they default to `None`?

**Comment by lmorchard** [comment]
Yeah, the settings default to None when the env vars aren't present. That _should_ make Boto look for the credentials from EC2 metadata, unless we really do need [this unmerged patch](https://github.com/jschneier/django-storages/compare/master...lmorchard:34-iam-role-credentials).

**Comment by lmorchard** [comment]
Also, FWIW, taking a look today at getting this working myself on our dev instance on elastic beanstalk.

After wrapping my head around this some more yesterday, I suspect that maybe boto - as used by django-storages - _will not_ properly look up the credentials from EC2 metadata. Going to make sure that's working, one way or another, even if I have to move us onto [a private temporary fork of django-storages](https://github.com/lmorchard/django-storages/tree/34-iam-role-credentials).

**Comment by lmorchard** [comment]
So, after some false starts & some tinkering, it appears that the release version of django-storages _should_ work with the IAM role credentials from EC2 metadata.

The one gotcha I ran into is that you have to make sure that the `AWS_ACCESS_KEY_ID` / `AWS_SECRET_ACCESS_KEY` env vars are _removed_ from elastic beanstalk, and not just blank. I had to upload a new .zip bundle with those keys commented out of the `.ebextensions/00-environment.config` file. When I hit the "X" next to those vars, they kept coming back in subsequent deploys.

I might tweak the `settings.py` to use a `None` value if it sees a blank string for those settings.

Oh, and also the S3 bucket policy needed to have something like this statement added to allow the EC2 instance role write access to the bucket:

``` json
{
            "Sid": "S3PermsForEC2",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::2345345345:role/aws-elasticbeanstalk-ec2-role"
            },
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::idea-town-media-dev-lmorchard/*",
                "arn:aws:s3:::idea-town-media-dev-lmorchard"
            ]
        }
```

You might already know that, but one of my false starts was because I was missing that :)

**Comment by lmorchard** [comment]
This seems to be working in dev, let's reopen / file new issues if prod problems come up
