### ISSUE TITLE
Test Pilot dev server not working (docs need to be updated)

### ISSUE THREAD

**Issue by flodolo** [mozilla/testpilot#2582]
https://testpilot.dev.mozaws.net/
Error about environment not being correctly set up

```
When running Test Pilot locally or in development environments, special configuration is required. Please see our documentation for details.
```

Stage works as expected
https://testpilot.stage.mozaws.net/

**Comment by SoftVision-PaulOiegas** [comment]
Hey @flodolo. Yeah, that happens because you need to manually add 2 prefs in order to navigate to dev Test Pilot page.
1. "testpilot.env" string type with "dev" value
2. "extensions.webapi.testing" boolean type with "true" value.
And on top of these 2, you are also notified to enter "https://" if not already added. 

This is a new implementation on dev server in order to assure that the environment is correctly setup before navigating to the page. Stage works because the change wasn't merged on it yet.

**Comment by flodolo** [comment]
Thanks, it works indeed.

I don't think it's great to have to manually change config to test a dev server, but that's a different discussion.

**Comment by flodolo** [comment]
Actually, reopening. The page points you to https://github.com/mozilla/testpilot/blob/master/docs/development/quickstart.md and there's no mention of setting up the dev server.

**Comment by SoftVision-PaulOiegas** [comment]
Even if the setup on that page, contains the two prefs, yeah, it's oriented for local development setup. Something tells me that we'll encounter the same thing on Stage server after merge. 

Maybe it would be ok to have the setup steps embedded in the message, instead of adding individual steps or creating new pages? After all, there are just 2 prefs and the "https://" protocol usage.

**Comment by lmorchard** [comment]
> I don't think it's great to have to manually change config to test a dev server, but that's a different discussion.

Problem is that the add-on can only work with one environment at a time across all tabs, which helps mitigate some security concerns. We tried automatically changing the pref, but it would cause confusing issues when someone had more than one environment open in tabs (e.g. dev vs stage vs prod) and the add-on kept flipping back & forth.

> Actually, reopening. The page points you to https://github.com/mozilla/testpilot/blob/master/docs/development/quickstart.md and there's no mention of setting up the dev server.

That doc is *only* about getting a local dev env up & running. This doc is about the other server environments:

https://github.com/mozilla/testpilot/blob/master/docs/development/environment.md

There *is* an optional add-on described there which will change the pref for you, but you have to build it yourself and manually select the environment with a toolbar button.

**Comment by flodolo** [comment]
> That doc is only about getting a local dev env up & running.

That's where the link points to though. So, you open https://testpilot.dev.mozaws.net/, follow the link as instructed and don't find anything useful to fix the problem.

**Comment by chuckharmston** [comment]
This documentation has since been updated and is no longer incorrect. Closing!
