### ISSUE TITLE
Test Pilot intermittently does not stop loading on nightly

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#2625]
Test Pilot side does not stop loading, ever. I'm on Nightly 56.

**Comment by johngruen** [comment]
Cannot repro in release 54...
BTW, here's what i'm logging:
<img width="767" alt="screen shot 2017-07-19 at 6 10 58 pm" src="https://user-images.githubusercontent.com/3323249/28377634-ba4c73aa-6cad-11e7-9c3a-9c2c799575fd.png">

**Comment by johngruen** [comment]
@fzzzy ^

**Comment by fzzzy** [comment]
This is much easier to reproduce on the 1714-fluent-react-merge branch. The fact that this may not happen on release firefox is really useful info, I'll see if I can repro on release on my branch.

If this is caused by a nightly problem, not a test pilot problem, we should still try to reduce a test case if we can figure out what the actual problem is.

**Comment by fzzzy** [comment]
Ok, I take that back, it doesn't seem as easy to reproduce as it was...

**Comment by fzzzy** [comment]
Duping this to #2634
