### ISSUE TITLE
Test Pilot Facebook share post title is wrongly displayed and the description is missing

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/testpilot#2639]
**[Affected versions]:**
- Firefox Latest Release 54.0.1 and up

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- The "testpilot.env" string type pref was manually added in "about:config" page with "stage" value.
- The "extensions.webapi.testing" boolean type pref was manually added in "about:config" page with "true" value.
- User is logged on Facebook.

**[Steps to reproduce]:**
1. Open Firefox and go to https://testpilot.stage.mozaws.net/share .
2. Click on the "Facebook Share" button.
3. Observe the Facebook share post message.

**[Expected result]:**

Facebook share post message contains:
- Test Pilot logo
- "Firefox Test Pilot" title in black chars
- "Test new Features. Give us feedback. Help build Firefox." text in black chars under title
- "TESTPILOT.FIREFOX.COM" page url in grey chars.

**[Actual result]:**

Facebook share post message contains:
- Test Pilot logo
- "testpilot.firefox.com" title in black chars
- "TESTPILOT.FIREFOX.COM" page url in grey chars.

**[Notes]:**
- This issue is also reproducible on production.
- The issue is also reproducible when posting the TestPilot homepage or experiment page to the user Facebook wall page.
- On Twitter the tweet message contains all corresponding information.
- Attached a screenshot of the issue:
![facebook_testpilot_issue](https://user-images.githubusercontent.com/20083658/28470290-f3c18bd0-6e41-11e7-9804-13fa1b2a946a.png)

**Comment by lmorchard** [comment]
Not sure what the issue is... Here's the FB debugger URL: https://developers.facebook.com/tools/debug/

[I just ran the stage URL through their debugger](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Ftestpilot.stage.mozaws.net%2F%3Futm_source%3Dcopy%26utm_medium%3Dsocial%26utm_campaign%3Dshare-page), and it looks okay:

![capture](https://user-images.githubusercontent.com/21687/28532992-94d67778-7069-11e7-83a4-ba17d2398793.PNG)

**Comment by SoftVision-PaulOiegas** [comment]
Yeah, probably it was something from Facebook. Testing now on Production and the share message looks ok.
