### ISSUE TITLE
Error message on Test Pilot homepage on Firefox for iOS

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#2642]
![img_0113](https://user-images.githubusercontent.com/23885/28475225-a8d73ae0-6e08-11e7-9dc1-c6501bf8ee59.PNG)

**Comment by SoftVision-PaulOiegas** [comment]
Indeed, just checked on Vlad's iPhone. And also the footer links are on the middle of the page. 

On Android is working fine, no error displayed while navigating. However, when you enter on an experiment page, the  "Just launched" sentence is displayed for every experiment instead of current number of participants.

![android](https://user-images.githubusercontent.com/17258026/28524557-aaabc420-7089-11e7-8d62-a630879b71fe.png)

**Comment by chuckharmston** [comment]
Confirmed that this fixes it on actual devices on stage:

![img_5e6cf3c657f5-1](https://user-images.githubusercontent.com/23885/35186208-c220c804-fdcd-11e7-8a30-928bdd96edb7.jpeg)

**Comment by SoftVision-PaulOiegas** [comment]
I can confirm this too, but I have one question. What versions of mobile devices we should support for the responsive UI? I've checked on iPhone 5 and 6 and on the 5, the content is wrongly displayed to left and some sentences are cut. 
I assume that iPhone 5 is too old and we are not supporting it?

**Comment by chuckharmston** [comment]
@SoftVision-PaulOiegas is it an issue of screen resolution on the device, or is it specific to iOS 10?

(iPhone 5 is stuck on 10.3.3, iPhone 6 can go up to 11.)

**Comment by SoftVision-PaulOiegas** [comment]
Well I don't think I have how to confirm that. The iPhone 6 cannot be downgraded to iOS 10.x (personal device of a colleague) and the iPhone 5, as you said, it's blocked to 10.x. 

Could be the screen specs, it's 4.0 inch vs 4.7 and resolution is 640 x 1136px vs 750 x 1334px. But still, might be something on our end too since I'm seeing 2 different behaviors on dev vs production, where some of the page elements is aligned to right.  

I'll share some screenshots in a few minutes.

**Comment by SoftVision-PaulOiegas** [comment]
After a second look, it seems that it might be a combination of both since some of our elements are "bleeding" on the small screen. But can't say for sure. 

![img_0186](https://user-images.githubusercontent.com/17258026/35232677-c7d3de48-ffa4-11e7-97b4-9180b25ca0d1.PNG)
