### ISSUE TITLE
[l10n] Clarify the notification about locale availability

### ISSUE THREAD

**Issue by bidaian** [mozilla/testpilot#2653]
The current says:

`"This experiment is not supported in your language (ab_CD)"`

That could give the impression of lack of functionality in the localized browser. Could you change it to:

`"This experiment has not been yet translated to your language (ab_CD)"`

The "not yet" also hints at the possibility of contributing to the translation.

**Comment by flodolo** [comment]
I agree that supported might not be the best choice. Maybe "This experiment is not available in your language yet (XX)"?

Eduardo also raises an interesting point (cc @stasm): if my accept languages specifies "eo,it,en", I get the page in Italian, and a warning saying that the experiment is not available in "Esperanto (eo)", because check stops at the first language. 

Should we display this warning at all? If a user is comfortable in reading the website in Italian, he shouldn't have a problem in using the add-on in Italian too.

**Comment by marsjaninzmarsa** [comment]
Or maybe just simple "This experiment is not available in _$language_ yet"?

**Comment by stasm** [comment]
> Eduardo also raises an interesting point (cc @stasm): if my accept languages specifies "eo,it,en", I get the page in Italian, and a warning saying that the experiment is not available in "Esperanto (eo)", because check stops at the first language.

This sounds like a bug. Ideally, the dialog would use `fluent-langneg` to choose the correct language, just like the website does for its localization.

**Comment by bidaian** [comment]
The experiment **is** available (it is active) and **is** supported (my browser can run it), but it has not been translated to the browser's language. We should be able to put that clearly into words.
@marsjaninzmarsa on top of that I would rather avoid "[not available](https://transvision.mozfr.org/?recherche=not+available&repo=central&sourcelocale=en-US&locale=eo&search_type=strings#browser)" and "[not supported](https://transvision.mozfr.org/?recherche=not+supported&repo=central&sourcelocale=en-US&locale=eo&search_type=strings#browser)" because they could be interpreted as "it will/might not work". The links point to Transvision, where you can see that Firefox users find  those messages  in situations where lack of functionality is involved, and that's not the case.

**Comment by stasm** [comment]
How about `This experiment has not been translated into LANGUAGE yet.` combined with `Install Anyway`?

(I'm not a Test Pilot dev so I'm not sure how feasible this is.)

**Comment by bidaian** [comment]
@stasm that'd be perfect.

**Comment by lmorchard** [comment]
Dropped this back to ready status, because there's not actually a pull request associated with this that's ready for review

**Comment by lmorchard** [comment]
Actually, reading through the comments on this, I think the existing message is correct & as intended. Having an experiment supported in a locale is not entirely based on the availability of translations. 

For example, the Cliqz experiment was only available in the German locale - not because it hadn't been translated, but because it was mainly intended for a German regional audience for product reasons. I don't remember the exact reasons, but they were not strictly related to UI translation.

**Comment by johngruen** [comment]
`yet` is overdoing it a bit since some experiments will never be localized.

Lets do: `This experiment has not been translated to your language (ab_CD)`

**Comment by lmorchard** [comment]
> Lets do: This experiment has not been translated to your language (ab_CD)

Does this cover the concept that some experiments are unavailable for product reasons and not just lack of translations? (Or is that not actually worth worrying about?)

**Comment by johngruen** [comment]
@lmorchard there's a yaml flag that lets us hide these entirely (ie Cliqz)

**Comment by SoftVision-PaulOiegas** [comment]
@lmorchard @johngruen Guys, on what experiments this message should be displayed?
I'm asking because I can see it only on Cliqz, if language is other than German and for Containers experiment if language is other than English. All the others are not displaying this message. Not even Voice Fill which is restricted for other locales than English. 
Also, the message is only partially translated:

![not available message](https://user-images.githubusercontent.com/17258026/31344359-237f647e-ad1b-11e7-84d7-6afdfee7f6c9.png)

However, this message is displayed for most of the old graduated experiments (Pulse, Page Shot, Tracking Protection, Activity Stream, NoMore404's and Universal Search, except Tab Center). 

Did we forgot to do that for the newer experiments?
