### ISSUE TITLE
UX to link to graduation reports in blog

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#2694]
## Currently

Graduation reports [live on the site](https://testpilot.firefox.com/experiments/no-more-404s), but we'd like to move them to the blog.

## Proposal

For experiments like [Page Shot](https://testpilot.firefox.com/experiments/page-shot) we'd  like to be able to keep the majority of page content, but provide a CTA to visit a link on the Test Pilot Medium Channel highlighting the Graduation report.

## Acceptance

- [ ] It should provide a CTA to the previous experiment graduation report
- [ ] It should still be possible to view the original experiment page content

**Comment by ChenMorpheus** [comment]
Sorry for the late reply. I came up with the proposal based on current visual style. The biggest difference is to change the icon to a less warning information icon since the original one might be confused. Please find the screens below for measurements and asset.

![notice in detail page](https://user-images.githubusercontent.com/18019946/29405372-463a25aa-8370-11e7-9b57-7054bf3ab194.png)

Measurement
![notice in detail page](https://user-images.githubusercontent.com/18019946/29405665-205727ba-8371-11e7-9756-6aec62120141.png)

Assets
http://design.firefox.com/icons/viewer/
(Fin **info 16**)

**Comment by johngruen** [comment]
I need to provide a GA event for this.
