### ISSUE TITLE
Misleading "Just launched" label

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#2696]
When an experiment is new, it shows a `Just Launched` label on the experiment card that goes away when you visit it:

<img width="1049" alt="screen shot 2017-08-01 at 09 12 23" src="https://user-images.githubusercontent.com/23885/28829916-f286ab9a-769a-11e7-9921-a8ebb5830184.png">

This is unexpected. Visiting a page does not change that an experimented had recently been launched.

**Comment by lmorchard** [comment]
This is an [intentional feature](https://github.com/mozilla/testpilot/issues/1052) - we [store a timestamp](https://github.com/mozilla/testpilot/blob/beee92166f23be03f743573d282dc2d8615706c0/frontend/src/app/containers/ExperimentPage.js#L236) and [clear the banner](https://github.com/mozilla/testpilot/blob/bd2f98beef70c5e6562fd6ad0182da826ed839e0/frontend/src/app/components/ExperimentRowCard.js#L169) after an experiment page is visited.

**Comment by chuckharmston** [comment]
Sure. It's still unexpected.

I'd suggest either changing the behavior or label (perhaps to just "New").

**Comment by lmorchard** [comment]
But, it's not unexpected in the sense that it's a bug / regression.

**Comment by ghost** [comment]
Let's drop the "visited page" logic

**Comment by marvinsanchez1** [comment]
Hi @wresuolc , I am a student at seneca college. I'm currently taking a open source course, looking for my first bug. If this bug is not assigned to someone, can I work on it for my assignment?
Thank you!

**Comment by lmorchard** [comment]
> Hi @wresuolc , I am a student at seneca college. I'm currently taking a open source course, looking for my first bug. If this bug is not assigned to someone, can I work on it for my assignment?
Thank you!

Thank *you*, we'd very much appreciate the contribution! Feel free to ask for help or raise any questions you might think of!

**Comment by marvinsanchez1** [comment]
Hello @lmorchard  I'm not sure how to reproduce this issue on my computer. I was able to set up the environment and have it running.

**Comment by lmorchard** [comment]
>Hello @lmorchard I'm not sure how to reproduce this issue on my computer. I was able to set up the environment and have it running.

@msanchez5  If it helps, I've got links to the code involved [back in this comment](https://github.com/mozilla/testpilot/issues/2696#issuecomment-319387161). 

But, reproducing the behavior is a little weird, because you'll probably have to temporarily edit the YAML for an experiment (e.g. [min-vid.yaml](https://github.com/mozilla/testpilot/blob/master/content-src/experiments/min-vid.yaml#L100)) and change the `created` date to sometime within the past two weeks. 

Then, if you haven't visited the page locally yet, there should be a "Just launched" banner on the experiment. After you've visited it, the banner should go away. 

For this issue, we want to remove that page visit check, so that the "Just launched" banner stays visible for 2 weeks even if you have visited the page.

**Comment by marvinsanchez1** [comment]
@lmorchard so, I managed to replace this code 
 https://github.com/mozilla/testpilot/blob/beee92166f23be03f743573d282dc2d8615706c0/frontend/src/app/components/ExperimentRowCard.js#L169-L170 
with this code.

```javascript
    // If never seen and seen since last time, *do* consider it "just" launched.
    if (!getExperimentLastSeen(experiment) || getExperimentLastSeen(experiment)) { return true; }
```

this works if you **haven't visited** the page and after **you visited** the page. Although you said you wanted to be removed the visit logic, but i wasn't sure if this function 
> getExperimentLastSeen(experiment);

is uses somewhere else.

**Comment by lmorchard** [comment]
> I managed to replace this code ... with this code.
> ```
> if (!getExperimentLastSeen(experiment) || getExperimentLastSeen(experiment)) { return true; }
> ```

Hmm, looks like this code will always return `true`. 😁 

Because if `getExperimentLastSeen()` returns `true`, then this conditional is `if (!true || true)` . If the function returns `false`, then it's `if (!false || false)`. Both of these conditions result in `true` - so `return true` will always happen. 

So, TL;DR: Might as well just delete this `if` statement altogether and `return true` at the end of the function.

> but i wasn't sure if this function
> ```
>    getExperimentLastSeen(experiment);
> ```
> is uses somewhere else.

That's a really good question! I just [searched for the function with GitHub](https://github.com/mozilla/testpilot/search?utf8=%E2%9C%93&q=getExperimentLastSeen&type=) and it looks like the function is just used here, but it's mocked up for tests and stories. But, those tests & stories will need updating to reflect the change in functionality

There's also [`setExperimentLastSeen()`](https://github.com/mozilla/testpilot/search?utf8=%E2%9C%93&q=setExperimentLastSeen&type=), which is what sets the value used by the `get` function. We should remove that stuff too

**Comment by lmorchard** [comment]
Looks like PR #2993 fixed a part of this issue, but there's still work left:

- [x] Remove getExperimentLastSeen / setExperimentLastSeen
- [x] Update tests to reflect changes as necessary
- [x] Update stories if necessary (might not be)
