### ISSUE TITLE
Problem...ish thingy with Min Vid

### ISSUE THREAD

**Issue by ApodasheisstRed** [mozilla/testpilot#2706]
You can drag the box so far out of the screen, that you`re unable to drag it back in or close it, so it´s basically stuck. Would be nice if you would change it,so that you can drag the video from every side, not just the upper one. That´s it.

**Comment by SoftVision-PaulOiegas** [comment]
Hi @ApodasheisstRed  and thanks for your report. However, this issue is already filled in Min Vid repository and has steps to reproduce for bot Mac OS and Windows (https://github.com/meandavejustice/min-vid/issues/499).
I'm gonna close this one in favor of the one from Min Vid repo, so please follow the discussions there.

**Comment by ApodasheisstRed** [comment]
Ok sorry. I didnt know that.
