### ISSUE TITLE
"Enable" button is available and no notification is displayed to inform the user that Notes is incompatible with Firefox versions lower than 54

### ISSUE THREAD

**Issue by Carlos1946** [mozilla/testpilot#2731]
Hi, 
I installed Notes and on Test Pilot page the Notes feature is saying "Enabled". However when i run Sidebar to find it the sidebar do not show Notes, only whows bookmarkks, etc. 
I have Windows XP and Firefox version 52.2.1 (32-bit). Maybe this feature requires another OS higher than XP? Could you helpo me on this issue?
Best for all
Carlos

**Comment by SoftVision-EmilPasca** [comment]
It seems that your OS and latest supported Firefox version is too old for this experiment.

I have tested this issue on Windows XP (32-bit) with the latest supported release 52.0 and also the latest Firefox version 52.2.1 ESR and managed to reproduce the issue.
After enabling Notes experiment, the Notes option is no available in the sidebar.
The issue is also reproducible on Windows 10 x64 with Firefox version 52.2.1 ESR, Firefox Release 52.0 and 53.0.

When loading the add-on in about:debugging on Firefox Release 53.0, the following message is displayed:
"There was an error during installation: Add-on notes@mozilla.com is not compatible with application version. add-on minVersion: 54.0a1."

With Firefox 54.0, the issue is no longer reproducible, Notes is successfully enabled and it is displayed in the sidebar.

Because of this, I think the "Enable Notes" button should not be displayed for the users that try to install the experiment form an outdated version. Also, we should add a notification on the experiment details page when this occurs.
I will modify your bug title to reflect this.

**Comment by ghost** [comment]
Let's add a note to the minimum version field.  Same for voice fill

**Comment by Carlos1946** [comment]
Sorry but still do not understand why Firefox (and i support Firefox regularly with donations) is so dependant from Microsoft Os and do not stimulate developers to create add-ons that are compatible with old versions of Firefox and Windows OS, like XP for example. Why we are so discriminated just because we refuse to update the OS versions thay decide to place on the market. Windows XP is a good version with all security updates and do not understand why to update for the recent version Windows 10 if we have a good old version. It is the same thing to change from the vynil to Cd  that is even worst. Vynil is recovering after long years of CD propaganda. Why to not ask the developers to do add-ons compatible with old versions of Firefox and Windows XP at least this one that is a very good version.
Thanks and best to you all,
Carlos

**Comment by SoftVision-PaulOiegas** [comment]
If I remember well, the browser that supported XP the longest was Firefox. They were the last ones to drop the updates for it. Other browsers were long gone from XP when Firefox decided to pull the plug. All this happened because even Microsoft no longer supports it and recently also Vista had the same fate in April this year. 
The idea that Firefox will stop the support for XP somewhere along the way was a known fact when Microsoft announced this. They just didn't knew when this will happen and they chose to do it as late as possible, because they care about their users.

When it comes to add-ons and Firefox versions, I wouldn't call this "discrimination", but instead "technological progress". New security policies and technologies were created and implemented in the new OSes. The same thing happens with Firefox add-ons. Right now we are migrating from SDK based add-ons that are now considered unsafe, to webextensions based add-ons. I believe that some OSes, like XP, are not capable of supporting this new technologies anymore and will never do. So I don't think it's logic to create unsafe add-ons just for the sake of backward compatibility.

However, I agree with you on the vinyls vs CD's comparison, but sadly, I don't think this applies to coding and security. And the problem we are talking about, is all about the evolution of coding and user security.

I wouldn't return to old VCR's just for watching a good old movie if it's available on newer technology at a better quality. 😃

**Comment by Carlos1946** [comment]
Technology and security it is not everything humans need. The updating of
the old weaponry is the nuclear boms, did we need to use it to be updated
and follow the big weapon corporations?
If Microsoft decided to turn computers connected to the central agencies it
will be an update on security too?.
Each time Microsoft decide to launch another OS millions of shools from
everywhere are forced to change their OS too, this is a manipulation and
the globalization of a monopoly. Microsoft is a giant shark and you follow
what they decided to do. It is not a question of evolution of technology.
Bio-technology is an evolution of biology or just a way to corrupt the
human kind from within?
Robotization is it an evolution to make the things more easy and people
more fat? The real dog changed to a dog robot is an evolution of technology
or simply a way of extinction for our pets?

Chrome and another browsers i never use them. That´s it.

**Comment by SoftVision-PaulOiegas** [comment]
Well I agree with you on some of the points. But in the end, it all reduces to the free will and the point of view you look at... Nobody forces you to do so. If you still prefer XP, it's fine, but Mozilla cannot update the Microsoft OS to support the new add-ons. So I'm afraid we are stuck on this matter.

By the way, the latest Windows OS (Windows 10) was a free upgrade for more than a year for everyone that held a copy of Windows 7, 8, 8.1. So I think you re judging them a bit to harsh. After all, we all need money to live, and somehow we never fell to have enough...

In my opinion, Windows 7 and Windows 10 are both better then old XP (maybe not 8 and 8.1). I have worked with all starting from Windows 3.1... but that's probably just my opinion.

**Comment by Carlos1946** [comment]
well, i started with ZX Spectrum and the old Amiga 500, times where it was
the computer of the year (in 90s). Money that´s all i need to live for some
guys. Money and Technology, the two actual Gods you need we must to
believe. Like the bilionaires and big corporations are saying everyday. I
don´t still understand why are you ask us to donate to keep independant and
your words are so similar like them? Why are you quoting Chrome and others
because they follow the way of making money as Microsoft did. If you want
to follow them why not if you are screaming the same speech of so called
technology evolution?

**Comment by SoftVision-PaulOiegas** [comment]
This was partially fixed, the button now is lo longer displayed if Test Pilot add-on is installed. However, the error message for unsupported version is not displayed if TxP add-on is not installed (#2109) and the button to Install TxP and enable experiment is still displayed (#2848).

Since both the remaining issues are tracked separately, I will mark this one as verified.
