### ISSUE TITLE
Localized news updates linking to en-US only Medium posts need some tweaks

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#2762]
Copying over @flodolo's comment from #2759 on the news updates section and en-US only Medium posts:

> I think we need to start a larger discussion on how to manage this section.
>
> They're not going to be localized, so I wonder if we could find a less prominent space to show them for language != en-US (is it just me or they're not displayed right now on TP?), and only localize a section title (TP Latest News) + blurb explaining that news are in English, and only show the title for each news in English.

**Comment by flodolo** [comment]
> They're not going to be localized,

To answer a question from the previous PR: are these titles always linked to Medium articles, or sometimes they're just short news? I have no way to check that, maybe it's just my memory getting confused.

"They" in the sentence above was referred to the destination of the link (articles on Medium they're not localized).

**Comment by lmorchard** [comment]
> are these titles always linked to Medium articles, or sometimes they're just short news?

These titles will *not* always be linked to Medium articles. The link is optional, and some (most?) will just be short news updates.

**Comment by flodolo** [comment]
OK, then it makes sense to keep exposing them for localization as they are. The improvement would be having IDs that give a clear idea of the date, and avoid potential duplication.

**Comment by johngruen** [comment]
So there are few ways to go about this:

1. We could simply remove links from news items where the link is not localized on non-en-* locales. This would obviate the problem of connecting l10n-ed content to English blog posts, but we'd have to make sure all news items had full content as stand alone. 
2. We could not show news items linking to EN content in non-en-* locales. This is a coarser fix, but might make the types of things we put in our news feed more flexible.
3. We could add some kind of asterisk to items that link to english articles specifying htat the content is in English

I'm inclined toward option three since I'd hate to remove choice from a user whose first language is, say German, but is totally comfortable reading English. This would jibe with our policy on letting non-en users try en only experiments but giving them a heads-up first. @flodolo any preferences here?

**Comment by flodolo** [comment]
I'm OK with 3.

There's one other issue at the moment with news: often I've seen these strings added at the very last moment, and pushed to prod within a few hours. That means they stay untranslated until the next push to prod, which might be 2 weeks away, and those news might be completely outdated by that time. 

I think that's part of a larger issue (l10n should be decoupled from code pushes), but It could be mitigated by adding those strings at least a couple of days before prod is tagged.

**Comment by ChenMorpheus** [comment]
Please find the attached screens for my proposal, measurement and [icon](http://design.firefox.com/icons/viewer/). Let me know your thoughts, thanks.

![english only](https://user-images.githubusercontent.com/18019946/30845972-4fca7a3a-a2c8-11e7-9bdf-78205d4796d9.png)

**Comment by johngruen** [comment]
@ChenMorpheus LGTM

**Comment by meandavejustice** [comment]
@ChenMorpheus Could you link the icon, the link you provided is just the list of icons and the closest one I can find in that list to your screenshots is "share 16 windows" which isn't quite right.

**Comment by meandavejustice** [comment]
Also "Link to English article" should be able to be translated

**Comment by ChenMorpheus** [comment]
@meandavejustice Sorry that it hasn't been updated to the current design. Yes, the "Link to English article" should be able to be translated. Please refer to the link below for the updated measurement, and find the [icons](http://design.firefox.com/icons/viewer/) named "open in new 16" and "arrowhead right 16", thanks.

[News updates](https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Photonized_Txp_Website_Final/#artboard6)
