### ISSUE TITLE
[l10n] Lot of duplicated content (job title, feedback) in Test Pilot localization

### ISSUE THREAD

**Issue by alex-mayorga** [mozilla/testpilot#2773]
Steps:
1. Load https://pontoon.mozilla.org/es-MX/test-pilot-website/experiments.ftl/?string=169076
2. Click "MACHINERY" tab.

Result:
This string has been translated 5 times already in just the es-MX locale.

Expected result:
The string is translated once then reused, maybe use %ExperimentName% and make Test Pilot a %BrandName%

**Comment by flodolo** [comment]
For reference: "You can always give us feedback or disable Notes from Test Pilot."

The only thing changing is the name of the add-on.

We have similar duplications for job title, if we could avoid translate "Software Engineer" 10 times, it would be a good thing.

**Comment by alex-mayorga** [comment]
FWIW the "Software Engineer" example https://pontoon.mozilla.org/es-MX/test-pilot-website/all-resources/?search=Software+Engineer&string=159450

**Comment by lmorchard** [comment]
This one's going to be difficult to address. 

We manage site content [in YAML files for each individual experiment](https://github.com/mozilla/testpilot/tree/master/content-src/experiments). The strings in `locales/en-US/experiment.ftl` [are auto-extracted from YAML](https://github.com/mozilla/testpilot/blob/master/docs/content/reference.md#localization). The IDs are auto-generated from a combination of experiment slug and field names in YAML - plus an l10n suffix for when strings change. 

So, there's currently a 1-to-1 automatic mapping between the YAML schema and `.ftl` IDs.

To normalize & dedupe strings in `experiment.ftl` would mean introducing a different mapping scheme. We'd need to come up with a many-to-1 association between YAML properties and `.ftl` IDs so that the same string can be shared between multiple spots across experiment content.

But, ideally, I think we'd like to avoid maintaining a fully manual dictionary of IDs-to-phrases. Maybe we could base L10n IDs on hashes of the en-US strings? For example, these strings:
```
activitystreamContributors0Title = Software Engineer
activitystreamContributors4Title = Software Engineer
activitystreamContributors11Title = Software Engineer
notesContributors3Title = Software Engineer
pageshotContributors0TitleEngineer = Software Engineer
pageshotContributors1Title = Software Engineer
```

Could be collapsed into this hashed ID instead (using `echo 'Software Engineer' | sha256sum` as a example):
```
3d1f8d1dbcb265645cdd355869c74cb91af000ac8c14df6f44556cb33a57ad5e = Software Engineer
```

Of course, the problem now is that the ID loses any kind of human-readable meaning. Is that a problem?

**Comment by lmorchard** [comment]
Also, looking for suggestions & best practices... are there other projects around Mozilla with a bunch of localized site content that handle this better?

**Comment by lmorchard** [comment]
And of course, the hashed-ID approach doesn't address strings that are alike except for a possible placeholder. Not sure there's any easily automated approach for that.

**Comment by flodolo** [comment]
> Of course, the problem now is that the ID loses any kind of human-readable meaning. Is that a problem?

In general, the ID should be meaningful, since it gives information on how and where the string is used.

Firefox Send and Firefox Screenshots are using l20n, but they don't use YAML file to map content to strings.

I know zero about how the current FTL file is generated, I only wonder if we can exclude some strings from this extraction process, and associate them to a static ID.

**Comment by lmorchard** [comment]
[Did a quick hack to find repeated strings and come up with some auto-generated IDs.](https://gist.github.com/lmorchard/878867dbec4883fde14abceee1a893d9)

This might help us build a common string alias map, and also keep the ID looking relatively sensible. The ID gets ugly if the en-US string gets too long, though.

Looks like the only exact duplicate strings so far are contributor titles:
```json
{
  "titleSoftwareEngineer": {
    "string": "Software Engineer",
    "ids": [
      "activitystreamContributors0Title",
      "activitystreamContributors4Title",
      "activitystreamContributors11Title",
      "notesContributors3Title",
      "pageshotContributors0TitleEngineer",
      "pageshotContributors1Title"
    ]
  },
  "titleEngineeringIntern": {
    "string": "Engineering Intern",
    "ids": [
      "activitystreamContributors7Title",
      "activitystreamContributors8Title",
      "minvidContributors2Title",
      "notesContributors0Title",
      "sendContributors0Title",
      "sendContributors1Title"
    ]
  },
  "titleProductManager": {
    "string": "Product Manager",
    "ids": [
      "activitystreamContributors9Title",
      "universalsearchContributors0Title"
    ]
  },
  "titleSeniorUxDesigner": {
    "string": "Senior UX Designer",
    "ids": [
      "activitystreamContributors12Title",
      "trackingprotectionContributors1Title",
      "universalsearchContributors1Title"
    ]
  },
  "titleFirefoxQa": {
    "string": "Firefox QA",
    "ids": [
      "containersContributors4Title",
      "notesContributors5Title",
      "pulseContributors3Title",
      "snoozetabsContributors5Title"
    ]
  },
  "titleFirefoxUx": {
    "string": "Firefox UX",
    "ids": [
      "containersContributors7Title",
      "containersContributors8Title",
      "containersContributors9Title",
      "pulseContributors1Title",
      "sendContributors4Title",
      "sendContributors5Title",
      "snoozetabsContributors1Title",
      "snoozetabsContributors2Title",
      "snoozetabsContributors3Title",
      "tabcenterContributors0Title",
      "tabcenterContributors1Title",
      "tabcenterContributors2Title",
      "tabcenterContributors3Title",
      "voicefillContributors3Title",
      "voicefillContributors4Title"
    ]
  },
  "titleStaffEngineer": {
    "string": "Staff Engineer",
    "ids": [
      "minvidContributors1Title",
      "universalsearchContributors2Title"
    ]
  },
  "titleSeniorEngineer": {
    "string": "Senior Engineer",
    "ids": [
      "notesContributors4Title",
      "pulseContributors0Title",
      "snoozetabsContributors0Title",
      "universalsearchContributors3Title"
    ]
  },
  "titleSoftvisionQa": {
    "string": "Softvision QA",
    "ids": [
      "notesContributors6Title",
      "snoozetabsContributors6Title",
      "snoozetabsContributors7Title",
      "voicefillContributors5Title",
      "voicefillContributors6Title"
    ]
  },
  "titleSpeechEngineer": {
    "string": "Speech Engineer",
    "ids": [
      "voicefillContributors0Title",
      "voicefillContributors1Title"
    ]
  }
}
```

**Comment by flodolo** [comment]
That would be a step in the right direction.

> Looks like the only exact duplicate strings so far are contributor titles:

That's because the other problem involves slightly different strings.

```
activitystreamToursteps2Copy = You can always give us feedback or disable Activity Stream from Test Pilot.
cliqzToursteps2Copy = You can always give us feedback or disable Cliqz from Test Pilot.
containersToursteps4Copy = You can always give us feedback or disable Containers from Test Pilot.
minvidToursteps3Copy = You can always give us feedback or disable Min Vid from Test Pilot.
nomore404sToursteps1Copy = You can always give us feedback or disable No More 404s from Test Pilot.
notesToursteps3Copy = You can always give us feedback or disable Notes from Test Pilot.
pageshotToursteps4Copy = You can always give us feedback or disable Page Shot from Test Pilot.
pulseToursteps3Copy = You can always give us feedback or disable Pulse from Test Pilot.
snoozetabsToursteps4Copy = You can always give us feedback or disable Snooze Tabs from Test Pilot.
tabcenterToursteps4Copy = You can always give us feedback or disable Tab Center from Test Pilot.
universalsearchToursteps2Copy = You can always give us feedback or disable Universal Search from Test Pilot.
voicefillToursteps3Copy = You can always give us feedback or disable Voice Fill from Test Pilot.
```

In any other project that would be one string:

```
experimentFeedback = You can always give us feedback or disable {$expname} from Test Pilot.
```

And this aslo ties with #2657. Test Pilot is gaining popularity, especially thanks to Firefox Send. So, there are new locales starting (I've added es-AR and da in the past 2 days), but they have to look at strings that are not used anywhere…

**Comment by chuckharmston** [comment]
For reasons Les outlined, it's going to be very challenging to change the job titles. Strings in `experiments.json` should more-or-less be considered like fields in a record in a content management system. The way they're entered and identified would make it very challenging to deduplicate values, doubly-so if someone's job title changes.

We should investigate if there are ways to improve the `You can always give us feedback or disable` string, however.

**Comment by ghost** [comment]
One of our goals this quarter is to stop working on the Test Pilot site and focus on experiments.  Due to the large engineering changes this would need and the relatively few strings we have (1-3 new experiments per quarter?) we've decided to wontfix this.
