### ISSUE TITLE
Ensure that post-bootstrap add-on has good test coverage.

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#2782]
Thought I'd get to this really quick before launching the new embedded webextension add-on. I did not. So, I'm filing this issue to make it a more formal thing rather than something I just keep kind of meaning to get to.

**Comment by chuckharmston** [comment]
Slightly repurposing this bug to make sure that we have good test coverage for the add-on in a post-bootstrap world.

**Comment by meandavejustice** [comment]
https://www.npmjs.com/package/sinon-chrome

**Comment by meandavejustice** [comment]
Been looking into this a lot more this afternoon, in order to make this happen [background.js](https://github.com/mozilla/testpilot/blob/master/addon/background.js) will need to be changed up a bit to use webpack so we can export the functions to be tested.

Additionally we'll need to use sinon-chrome(linked in the last comment).

Trying to decide if it's even worth writing these tests, the functionality of the addon is pretty minor. While I'd love to have test coverage I don't wanna introduce more complexity to the code. We're currently at 200 lines.

Current functionality of the addon includes:
- adds button to browser which navigates user to correct environment(env is now provided
in separate builds in #3556
- fetch resources (experiments, news updates)
- update badge text on new experiments or new major news updates
- send a metrics ping once daily, including clientUUID, and installed txp addons

After looking through some repos to find examples of usage of `sinon-chrome` it looks like we would be doing a _lot_ of mocking to essentially test the webextension apis(which already have significant tests in firefox)

Thought i'd see what some of yall think before going and diving into all of this.

@lmorchard @fzzzy @dannycoates 
What do ya think?

**Comment by dannycoates** [comment]
The add-on does so little now that I'm meh on test coverage

**Comment by meandavejustice** [comment]
moving out of project
