### ISSUE TITLE
Min vid does not work on twitch.

### ISSUE THREAD

**Issue by Greeka67** [mozilla/testpilot#2814]
Min vid does not work on twitch.
The add-on icon does not appear on the video.
The add-on works popup video (https://addons.mozilla.org/en-US/firefox/addon/popup-video/)

**Comment by SoftVision-PaulOiegas** [comment]
Hi @Greeka67 and thanks for your report. Min Vid only supports YouTube, Vimeo and SoundCloud officially. Any other websites video that works with it, happens by chance and not because they are supported. 

Previously, users have reported that they found other websites videos that worked trough context menu option that we had. But recently the Min Vid experiment migrated from an SDK based add-on to a webextensions for security reasons, and the context menu option was temporarily lost.
It will probably return in a later version and maybe the dev team will extend the support for other players too.

In regards to extended support, I will need to close your issue since we already have this tracked under another issue in the repository (https://github.com/meandavejustice/min-vid/issues/331). Please follow the thread there and provide more info if you think you can help.
