### ISSUE TITLE
Test Pilot can no longer be installed from dev server

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2826]
[Affected versions]:
- Firefox 55.0.3 and above

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "testpilot.env" string type pref was manually added in "about:config" page with "dev" value.
- The "extensions.webapi.testing" boolean type pref was manually added in "about:config" page with "true" value.

[Steps to reproduce]:
1. Open the Firefox browser and navigate to "https://testpilot.dev.mozaws.net" page.
2. Click the "Install Test Pilot add-on" green button.
3. Observe the browser behavior. 

[Expected result]:
- Test Pilot add-on is successfully installed.

[Actual results]:
- The button remains in the "Installing..." state.

[Additional notes]:
- Here is a screenshot with browser console errors:
![test pilot install](https://user-images.githubusercontent.com/19226534/29770021-9961cb60-8bf5-11e7-9114-e0724fd0a977.png)

**Comment by fzzzy** [comment]
This is because we no longer sign the addon in circleci, and can't.

**Comment by SoftVision-PaulOiegas** [comment]
So this will no longer work straight from Dev? We should use the stage add-on to test dev website?

**Comment by johngruen** [comment]
This blocks testing on changes to the add-on. 
- needs site to use mozextensionsmanager
- will firefox accept the add-on

**Comment by fzzzy** [comment]
Just to clarify John's comment, we were discussing how a site needs to be whitelisted to use the mozAddonManager, which dev and stage are, but the l10n branch is currently not. However, this issue is because even though the dev site is whitelisted to use mozAddonManager, it won't accept the add-on because it hasn't been signed by the Mozilla key, which is only done by an ops script in the prod pipeline.

We should probably get ops to sign the add-on in the stage pipeline, so that the add-on can be installed from stage for testing. However, I don't think we currently have any plan or even strategy of how we could get install to work on dev.

**Comment by b4handjr** [comment]
Use Firefox Nightly as some of the prefs needed to install the experiment are not allowed to be set on anything besides nightly. You can set them, but they don't actually work.

**Comment by lmorchard** [comment]
Whew. Okay, this was annoying and I filed #2840 to try to make it less annoying...

Using **Firefox Developer Edition** - 56.0b9 (64-bit) on Windows - I was able to get the add-on to install from my local server. I set all the prefs  in the dev [quickstart](https://github.com/mozilla/testpilot/blob/master/docs/development/quickstart.md) and ensured `extensions.legacy.enabled=true` [as mentioned in `addon/README.md`](https://github.com/mozilla/testpilot/blob/master/addon/README.md).

I didn't try Nightly, just assuming the same works there as on Developer Edition.

Using **Firefox** - 55.0.3 (64-bit) on Windows - I **was not able** to get the add-on to install from my local server even after setting all the prefs.

Using [**an unbranded build of Firefox**](https://wiki.mozilla.org/Add-ons/Extension_Signing#Unbranded_Builds) - [55.0.4 (64-bit) on Windows](http://archive.mozilla.org/pub/firefox/tinderbox-builds/mozilla-release-win64-add-on-devel/1503742639/) - I **was able** to get the add-on to install from my local server after setting all the prefs.

None of the above worked on dev or stage - because they try to point to the production path for the add-on, which doesn't exist on those servers. I submitted PR #2838 to try to address this.

Feels like a lot of hoops to jump through with unbranded builds and all the prefs - but that could be a path to getting this tested on a release-like version of Firefox.

One problem, though, for automated testing: I don't think [mozdownload](https://github.com/mozilla/mozdownload) supports fetching an unbranded release build, so I'm not sure how we can roll that into our test runs easily

**Comment by fzzzy** [comment]
We should mention extensions.legacy.enabled in the quickstart... I made an issue: https://github.com/mozilla/testpilot/issues/2843

**Comment by lmorchard** [comment]
Huh. Maybe I was wrong about needing to use an unbranded release for the dev server? I just tried again with 55.0.3 (64-bit) on windows after the merge of #2828 and was able to install the addon with the big green button. Going to close this for now, since it seems to work for me? Let's reopen if I'm wrong!

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue on latest Firefox (55.0.3) release, Beta (56.0b9) and latest Nightly (57.0a1) build and Test Pilot add-on installs successfully if the "extensions.legacy.enabled" boolean pref is set to "true". 
Tested on Mac Os and Windows.

**Comment by SoftVision-CosminMuntean** [comment]
After the latest changes, this issue is reproducible. Test Pilot add-on can no longer be installed from dev server.  The button remains in the "Installing..." state.

Here is a screenshots with browser console errors:
![test pilot dev](https://user-images.githubusercontent.com/19226534/30584971-0f66a052-9d34-11e7-8370-7d799e140f54.png)

**Comment by lmorchard** [comment]
> After the latest changes, this issue is reproducible. Test Pilot add-on can no longer be installed from dev server. The button remains in the "Installing..." state.

@SoftVision-CosminMuntean What browser version & about:config settings did you use? 

Going back to my [checks from a couple of weeks ago](https://github.com/mozilla/testpilot/issues/2826#issuecomment-327277679), it seems like I was mistaken about getting install to work on the normal release version.

I tried all of that again just now - created new profiles, set all the prefs ([ugh](https://github.com/mozilla/testpilot/issues/2840)), tried installing.

It works for me on DevEdition 56.0b12 and [an unbranded build](https://wiki.mozilla.org/Add-ons/Extension_Signing#Unbranded_Builds) of Firefox 55.0.4. 

It did *not* work with the normal branded release Firefox 55.0.3. 

So, as restrictions tighten up around legacy add-ons, I think we *will* have to test on dev (and stage) using an unbranded build as a substitute for release Firefox. 

On production, of course, normal release Firefox should work - because our add-on there is signed with the Mozilla Extensions key.

**Comment by SoftVision-CosminMuntean** [comment]
> @SoftVision-CosminMuntean What browser version & about:config settings did you use?

I have reproduce this issue on latest Firefox (55.0.3) release and latest Nightly 57.0a1 build. In "about:config" I have added the following prefs:
- the "testpilot.env" string pref with "dev" value
- the "extensions/webapi.testing" boolean pref with "true" value 
- also I have set the "extensions.legacy.enabled" boolean  pref to "true" on Nightly (on Firefox release is already  set to "true" by default)

Reproducible on Windows and also on Mac OS. Please let me know if you need more information.

**Comment by SoftVision-CosminMuntean** [comment]
I just tested this on DevEdition 56.0b12 and an unbranded build of Firefox 55.0.1 and the issue is still reproducible. At least on Windows.
I have used a new clean profile for each browser version and also I have used the prefs mentioned above.

**Comment by lmorchard** [comment]
Missing a couple of prefs - these are also required to install unsigned add-ons:
  * extensions.install.requireBuiltInCerts = false
  * xpinstall.signatures.required = false

I've got [a list of all the current required prefs](https://github.com/mozilla/testpilot/issues/2840) over on this issue to create an assistant add-on to make setting all these easier. (Because it's awkward & error prone right now 😞)

But with all 5 of those prefs set, I can install the add-on on windows with devedition and unbranded

**Comment by SoftVision-PaulOiegas** [comment]
I confirm that using all the 5 prefs, the add-ons from dev and stage servers are correctly installed. We have created a "user.js" file containing all the 5 prefs and we are adding it to each new profile created for dev/stage server testing, to ease our job. 😄
