### ISSUE TITLE
Test Pilot site lacks a scroll bar in Firefox on Mac OS X 10.13.x (macOS High Sierra)

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/testpilot#2827]
![2017-08-29 07 14 11](https://user-images.githubusercontent.com/192271/29807163-9b93d79e-8c8a-11e7-80ec-cb700faabad9.png)

Impossible to use with a trackball. 

```text
highsierra:~ grahamperrin$ date ; uname -v ; sw_vers
Tue 29 Aug 2017 07:21:30 BST
Darwin Kernel Version 17.0.0: Wed Aug 16 20:06:51 PDT 2017; root:xnu-4570.1.45~23/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.13
BuildVersion:	17A352a
highsierra:~ grahamperrin$ 
```

**Comment by SoftVision-PaulOiegas** [comment]
Hi @grahamperrin and thanks for your report. However, I'm using Mac OS X 10.12 with the same settings as you have in the screenshot and I have the scroll bar displayed on the right side of the window.

Is there a chance that this only reproduces on Mac OS X 10.13? It could be a Test Pilot website issue, but until we check this, I'm inclining to think it could be an OS issue, since 10.13 is still in development.

Can you please check on other websites too and let me know of the results?

**Comment by grahamperrin** [comment]
Thanks. 

All other sites were OK and as far as I recall, all of the (few) Test Pilot pages that I visited appeared to be bugged. 

When I next have some free time with the Mac I'll take a closer look.

**Comment by grahamperrin** [comment]
A brief review of the history at the Mac: 

- the page before I visited the Test Pilot site is unaffected
- Test Pilot pages are affected
- some other pages are affected

– and where the bug does bite, it seems that both vertical _and_ horizontal scroll bars are missing. 

I can't guess what might cause the bug – the set of extensions on the Mac is, through Firefox Sync, probably a _subset_ of what I normally use with FreeBSD – but the symptoms are not limited to Test Pilot so I'll close this. Apologies for the noise.

**Comment by SoftVision-PaulOiegas** [comment]
I've updated on of the OSes from testing laptop to 10.13 Beta and I've managed to reproduce the issue. 

However, This might be related to website implementation. I've tried well known websites like youtube.com, reddit.com, 9gag.com and the scroll bar was present. But when I tried giphy.com and imgur.com, the issue was reproducing as on the Test Pilot website.

@fzzzy, @lmorchard, do you guys have any idea why this is reproducing on our website? Probably it has to do with some change that was made on Mac OS 10.13 since on 10.12 the behavior is not present. Maybe we can fix this ahead of the release of the new OS.

**Comment by grahamperrin** [comment]
OK … if it helps, here's a shortlist of some other currently affected URLs (I might make additions): 

- http://barisderin.com/?p=2871
- http://www.bolwin.com/software/snb.shtml

**Comment by grahamperrin** [comment]
Reproducible with Firefox Developer Edition 56.0b9 (64-bit) on more recent build 17A360a.

**Comment by grahamperrin** [comment]
I didn't test release 10.13. 

The bug is reproducible with release Firefox 56.0 (64-bit), with no extensions, on pre-release build 17B25c of Mac OS X 10.13.1.

**Comment by johngruen** [comment]
Works in 10.13

**Comment by SoftVision-PaulOiegas** [comment]
Yep, seems to be fixed on official Mac OS 10.13 release. 👍

**Comment by grahamperrin** [comment]
@johngruen @SoftVision-PaulOiegas please, which version(s) of Firefox did you test?

For me, the issue is still present with pre-release build 17C67b of Mac OS X 10.13.2 with: 

- Firefox ESR 52.4.1 (64-bit)
- Firefox 56.0.2 (64-bit). 

For extended support, please consider reopening this issue. Thanks.

**Comment by SoftVision-PaulOiegas** [comment]
I have tested the fix using latest Firefox Beta 57.0b14 and latest Nightly build v59.0a1 (2017-11-12) using the official MacOS 10.13 release. The issue is still reproducible on latest release (v56.0.2), but no longer reproducible on 57.0. Probably tomorrow you'll already have to update your Firefox to 57.0 which is launching tomorrow, so the issue will no longer be reproducible afterwards.
Also, the issue was also treated on the Test Pilot website by some UI changes. An update that will come on Tuesday this week also. 

Since the release dates were so close, we didn't wanted to uplift faster a fix for this and waited for the new versions planned release dates. Please bear with us a little more. 😃

**Comment by grahamperrin** [comment]
Thanks, I switched to Waterfox (and locked lesser-used Firefox to 56.0.2).

**Comment by SoftVision-PaulOiegas** [comment]
No problem. Also, you should definitely try Firefox 57 (Firefox Quantum). It's a whole new browser with a faster engine and lot's of good stuff.

**Comment by grahamperrin** [comment]
> try Firefox 57 (Firefox Quantum).

Done, thanks. 

Is there a plan to make the site work with Firefox ESR 52.x?

**Comment by SoftVision-PaulOiegas** [comment]
Well, this won't happen soon since the next release(s) are still based on Fx 52.x. However I can tell you for sure that there will be an ESR 59 or 60 launched and this will come only somewhere in quarter 2 (between April and June).

The Test Pilot website does not work on ESR since there were some major changes in the later Firefox releases that affected the website (especially for Quantum). Those changes forced the dev team to limit the minimum supported version to Firefox 54.x 
So, probably there is no chance until the next ESR launches. Sorry about this...

**Comment by grahamperrin** [comment]
Fair enough; thanks for the feedback.
