### ISSUE TITLE
Playlist videos do not match

### ISSUE THREAD

**Issue by Luck07** [mozilla/testpilot#2893]
When I go to a playlist, and I press the Min Vid to stay on, does not continue# 

![2017-09-28 19_43_55-](https://user-images.githubusercontent.com/32375803/30993445-77b79820-a485-11e7-8526-bddaf992cab1.png)

**Comment by SoftVision-PaulOiegas** [comment]
Hi @Luck07 and thanks for your report. However, can you please fill this issue again on [Min Vid GitHub page](https://github.com/meandavejustice/min-vid/issues)? Here is the Test Pilot GitHub page so it's a bit unrelated. 
Also, can you please provide a bit more details? We would like to know what operating system are you using, what Firefox version, what kind of playlists / videos you were trying to play.  Maybe you can give us some links so we ca debug your issue.

I will close this since it's in the wrong place, but please relog it on Min Vid repository. You might be on to something important.
