### ISSUE TITLE
Test Pilot website is not completely loaded in Microsoft Edge and Internet Explorer browsers

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2943]
[Notes]:
- This issue is reproducible on all servers.

[Affected versions]:
- Microsoft Edge
- Internet Explorer

[Affected Platforms]:
- All Windows

Steps to reproduce]:
1. Open the Edge or IE browser and navigate to "https://testpilot.stage.mozaws.net/" page.
2. Observe the Test Pilot page.

[Expected result]:
- Test Pilot page is correctly loaded.

[Actual results]:
- Only the blue background with stars and constellations is loaded.

[Additional Notes]:
- Here is a screenshot with the issue:
![ie](https://user-images.githubusercontent.com/19226534/31608631-990f7112-b279-11e7-809e-d0ca8983f942.png)

**Comment by fzzzy** [comment]
This is because we are using Array.includes, which is part of ES2016, not ES2015. For some reason our babel settings don't convert it; probably our babel settings only use ES2015.

Easiest fix is just to switch back to indexOf; alternatively we could upgrade babel to support ES2017 (which has async/await, which would be nice)

**Comment by chuckharmston** [comment]
We should be using [`babel-preset-env`](https://github.com/babel/babel-preset-env), in favor of which `babel-preset-es####` has been deprecated. Rather than choosing a version of the ES spec to comply to, you define your browser spec, and it makes sure it works in each of those browsers.

Worth noting that we should choose our browser spec carefully, as it has the potential to bloat the bundle size with polyfills if you're too liberal.

**Comment by fzzzy** [comment]
.includes( was a red herring. It seems that IE chokes on Symbol. Investigating.

**Comment by fzzzy** [comment]
Symbol is being used by fluent-react, which is in the vendor bundle, which isn't getting transpiled by our babel toolchain. We are including the compat version of fluent-react which has already been transpiled by babel, but still includes references to Symbol (which it shouldn't as Symbol is defined in es6)

**Comment by fzzzy** [comment]
https://github.com/projectfluent/fluent.js/issues/79

**Comment by lmorchard** [comment]
[Back when I replaced `babel-polyfill` with `regenerator-runtime`](https://github.com/mozilla/testpilot/commit/4537c8ce8dde6482fd74afa026fc657519d373e0#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L16), it seemed like async/await was the only thing we needed polyfilled. 

Maybe we need to re-introduce `babel-polyfill` as a quick fix? Long term fix would be to selectively re-introduce some polyfills - which I think is what #2946 would help with, if it turns out we need more than just Symbol

**Comment by lmorchard** [comment]
Also, [this comment with a .babelrc](https://github.com/babel/babel-preset-env/issues/203#issuecomment-285820866) might be relevant, since it's also about IE11 & Symbol

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and is no longer reproducible on Test Pilot dev server.  Test Pilot website is now fully loaded in Microsoft Edge and Internet Explorer.
But, on Internet Explorer the website is wrongly rendered. This issue was logged a while ago (#1705) but was closed based on  low number of users on Internet Explorer.
