### ISSUE TITLE
Test Pilot news alerts and latest updates section are no longer displayed on dev server

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2951]
[Notes]:
- Yesterday the Test Pilot news alerts and also the "Latest Updates" section were available on dev server.
- The "Latest updates" section is correctly displayed on the stage server.

[Affected versions]:
- Firefox 56.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

Steps to reproduce]:
1. Open the browser and navigate to "https://testpilot.dev.mozaws.net/experiments" page.
2. Click the "Install the Test Pilot Add-on" button.
3. Observe the Test Pilot experiments page.

[Expected result]:
- The Test Pilot news alerts are displayed.
- The Test Pilot latest updates is displayed under the "Welcome to Test Pilot!" title.

[Actual results]:
- The Test Pilot news alerts are no longer displayed.
- The Test Pilot latest updates section is missing.

[Additional Notes]:
- Here is a screen recording with the issue:
![news pop-up and latest updates](https://user-images.githubusercontent.com/19226534/31665942-36c444a8-b353-11e7-9ec7-42ea430a7623.gif)

**Comment by lmorchard** [comment]
Starting to take a look at this. First impression was this is working as expected - until I noticed when it was filed, at which point the news (not yet 2 weeks old) *should* have still been showing up. Will investigate

**Comment by lmorchard** [comment]
Hmm, actually, I was unable to reproduce a problem for this issue. This is what I tried:

* Created recent news items on my local dev machine, both with `major: true` and without. The dialog and news update section appeared as expected.

* Set my clock back in time to October 17 and visited testpilot.dev - the news update section appeared as expected. 

* The section on testpilot.dev disappeared as expected when I restored my clock to the correct time, because we have no news items newer than 2 weeks

Looks like we've [made changes to news update & dialog handling since October](https://github.com/mozilla/testpilot/commit/dffbc1944e919a954014ea2852b7faaa6cc04c80), so I'm guessing we fixed this along the way too?

Let me know if I'm missing a step to reproduce an issue, because I have a vague memory of something weird happening here
