### ISSUE TITLE
Apply Photon Style to News Feed Items

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#2959]
Please see the following Spec:

https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Homepage_20170927/#artboard4

**Comment by lmorchard** [comment]
Starting work on this. First question: I clicked on the spaceship copter and saw an exportable [`icon_spaceship.svg`](https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Homepage_20170927/assets/icon_spaceship.svg). So, I figured I'd use that rather than the `copter.png` [we moved into its own component](https://github.com/mozilla/testpilot/commit/a4bc201244dba7441fab678715d7e72fc3f8aa0b).

But, the colors on the SVG look kind of blown out. Is there a different way I should be getting images from these specs? Or something I need in CSS to make the SVG display properly?

![capture](https://user-images.githubusercontent.com/21687/32294833-c8b21310-bf1d-11e7-9d24-b008a22e3c7f.PNG) vs ![capture](https://user-images.githubusercontent.com/21687/32294766-9175a2c2-bf1d-11e7-9377-d681929dc747.PNG)

**Comment by johngruen** [comment]
🤷‍♂️ huh

**Comment by SoftVision-PaulOiegas** [comment]
The News Feed section was Photonized, but I see some differences between design measurements and the actual implementation.
1. The big container without subtitle has 980px x 129px instead of 1000px x 126px
2. The big container with subtitle has 980px x 152px instead of 1000px x 146px
3. Icon container is now too small for other experiments icons and they get cut on top and bottom (eg: Send).
4. "Title" and "Date" and "Subtitle" containers have 22px while in designs the "Title" and "Subtitle" ones should be 24px and the "Date" one 19px.

@johngruen Any concerns here? I'm only concerned about the icon part.
