### ISSUE TITLE
Create featured experiment section on homepage.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#3003]
We will be replacing the homepage newsfeed with a section highlighting a featured experiment. This bug tracks the work for the implementation of that section itself.

Some [UX is available](https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Featured_experiment/), but pieces of this are blocked on #2976:

- Photonization
- The no-featured-experiment experience
- The no-video experoence
- The not-Firefox experience
- The small-screen experience

Additionally, this will use the modal in #2998 and is blocked by its creation.

**Comment by Pekochen** [comment]
The latest visual measurement:
https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Featured_experiment/

**Comment by chuckharmston** [comment]
Of note, we will maintain the existing News Feed section in place of this if there are no featured experiments.

**Comment by chuckharmston** [comment]
No longer blocked on #2976; the work from it just needs to be updated to match the Photon styles, tracked in #3019.

**Comment by meandavejustice** [comment]
@Pekochen Are we getting rid of the news feed section for the news feed page? Where do the news feed items go? above or below the featured item?

cc/ @chuckharmston

**Comment by chuckharmston** [comment]
> Are we getting rid of the news feed section for the news feed page?

Yep.

> Where do the news feed items go? above or below the featured item?

They're not on the homepage unless there are no featured items.

**Comment by meandavejustice** [comment]
Came up with a ux question when running my cleaning up / running my tests today.

When installing the addon and extension, or just the extension from the home page, should we redirect to the experiment detail page and show the tour? The current behavior installs the addon and leaves the user on the home page with the "manage/feedback" buttons in place of the install button.

In order to accomplish this we'll need to add a promise object to the enable experiment and install addon methods to navigate to the detail page when install is complete. We'll also need to pass some state into the detail page to show the tour dialog on load.

These seem to be reasonable changes since we have a bit more time now before lockbox launches. Most of the time spent would be writing the integration tests.

thoughts? @chuckharmston @johngruen

**Comment by chuckharmston** [comment]
One more alternative that might have a smoother UX: show the tour in place, and have the "Done" button ship you to the experiment page.

CC @Pekochen and @ChenMorpheus for their thoughts as well.

**Comment by ChenMorpheus** [comment]
@meandavejustice @chuckharmston Sorry for the pretty late reply. Yes, my thought works exactly like Dave said. Please find the link below and interact with the install button for reference, and sorry that it should be a tour there. If it's not an easy task to implement, Chuck's solution works as well. Let me know if any questions, thanks. 

https://mozilla.invisionapp.com/share/QCCPNI3YZ#/258957338_a-0-0_FE_TxP_Not_Installed

**Comment by meandavejustice** [comment]
@ChenMorpheus I went with @chuckharmston's solution after seeing how difficult passing that state to experiment details would have been. We would have to refactor a ton of stuff on that page, it seems like current behavior (chuck's suggestion) works well.

We can revisit it of course though
