### ISSUE TITLE
[Newsletter] Notification that informs about the need to check the privacy notice checkbox is no longer displayed

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3042]
**[Affected versions]:**
- Firefox 56.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to https://testpilot.dev.mozaws.net page.
2. Click the "Install the Test Pilot Add-on" big green button.
3. After TxP "Newsletter sign up" dialog is displayed, click the text field in order to focus it.
4. Enter a valid email address and leave the privacy checkbox unchecked.
5. Click the "Sign Up Now" button and observe the dialog behavior. 

**[Expected result]:**
- The sign up process is not performed and you are notified that you need to check the privacy notice checkbox in order to proceed.

**[Actual result]:**
- No notification is displayed that informs you about the need to check the privacy notice checkbox.

**[Notes]:**
- The same behavior occurs also for the footer Newsletter sign up form.
- Here is a screen recording of the behavior https://goo.gl/9Ussyv.

**Comment by meandavejustice** [comment]
poking around at this is seems like `handleSubmit` isn't being called because of #1891, at least locally. If I set an `onClick` handler instead I can get the message to show up, although it appears that it lost it's style (probably in a refactor).

This is what it looks like now
![newsletter-form-privacy-checkbox-notification](https://user-images.githubusercontent.com/1844554/34133449-9d1ef368-e44c-11e7-9e03-3fc51b264ba3.png)

Gunna dig around for the mockups in the morning but cc/ing @johngruen @ChenMorpheus in case yall have opinions on this

**Comment by ChenMorpheus** [comment]
@meandavejustice The style would work like the incorrect email in a red bubble. Find the link below and navigate to the bottom of the measurement.

https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Photonized_Txp_Website_Final/#artboard8

**Comment by meandavejustice** [comment]
This is what the email submit error notification currently looks like:
![email-notification-error](https://user-images.githubusercontent.com/1844554/34687213-f6d74892-f4a5-11e7-9577-fceeeeca383f.png)

This is a screenshot from the mockup you linked:
![email-notification-mockup](https://user-images.githubusercontent.com/1844554/34687305-3375b950-f4a6-11e7-9585-7fd226a98ae2.png)

Would you like me to also update the email submit error notification or make the privacy notice notification match the existing style?

@ChenMorpheus

**Comment by ChenMorpheus** [comment]
@meandavejustice Sorry that I am a little bit confused. I thought these two warning boxes would not appear at the same time like this:

![image](https://user-images.githubusercontent.com/18019946/34703994-03627538-f531-11e7-8203-53419f12b8da.png)

My understanding is if user unchecks the checkbox and inputs an incorrect email address as well, we would show checkbox warning until the user checks it and submit again, then we show the error warning message. If it's not easy to implement, we could merely show two warnings at the same time as the mockup below:

![image](https://user-images.githubusercontent.com/18019946/34704119-0a21c512-f532-11e7-8cda-386c9e8fa274.png)

What do you think? 

BTW, I noticed the font weight here is all bold in the current implementation, could you also fix this? Thanks.

**Comment by meandavejustice** [comment]
@ChenMorpheus I was referring to the placement and style of the Error message in the first screenshot I posted. With the text "There was an error submitting your email address. Try again.". It's above the form and centered in the footer section with a white background.

I'm going to leave it alone for the time being and only address the privacy-notice checkbox error notification. If the "error submiting email address" message needs to be addressed we can file another issue for that, especially since it does work as is.

**Comment by ChenMorpheus** [comment]
@meandavejustice Sorry that I didn't make myself clear. I meant we should follow the style of the red bubble we provided for both "please check the checkbox if you want to proceed" and "There was an error submitting your email address. Try again." since this is specifically defined [here](https://design.firefox.com/photon/components/input-fields.html) in Design System. They will look like the screen below.

![](https://user-images.githubusercontent.com/18019946/34703994-03627538-f531-11e7-8203-53419f12b8da.png)

**Comment by meandavejustice** [comment]
@ChenMorpheus Yeah that makes sense, I'll file a separate issue for that message

**Comment by chuckharmston** [comment]
Since this missed the tag, moving to milestone 39.

**Comment by fzzzy** [comment]
🎉

**Comment by SoftVision-PaulOiegas** [comment]
The default browser dialog is displayed now with the error message for the privacy checkbox. 👍
