### ISSUE TITLE
"Enable" experiment button is wrongly clickable in the pinned floating bar while "Thank you" pop-up is displayed

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/testpilot#3067]
[Affected versions]:
- Firefox 57 and up

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = stage" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".
- Test Pilot add-on was already installed on the same profile.
- One of the active experiments was already enabled.

[Steps to reproduce]:
1. Open the browser from prerequisites and navigate to the experiment's detailes page (e.g. https://testpilot.dev.mozaws.net/experiments/voice-fill)
2. Click on the "Disable (experiment)" button.
3. Scroll down the page and observe the "Enable (experiment)" button.
**BONUS:**
4. Click on the "Enable (experiment)" button and observe the Tour pop-up.

[Expected result]:
3. The "Enable (experiment)" button is not actionable.
4. The "Tour" pop-up is displayed instead of the previous "Thank you" which is dismissed.

[Actual result]:
3. The "Enable (experiment)" button becomes actionable once the pinned floating bar is displayed.
4. 4. The "Tour" pop-up overlaps the previous "Thank you" one.

[Notes]:
- Here is a screencast with the issue:

![pop up](https://user-images.githubusercontent.com/26000308/32790116-3547310c-c966-11e7-8035-c96b54f567a8.gif)

**Comment by kgeorgiou** [comment]
This seems to be resolved on master branch. 

By briefly inspecting the page, this is due to `.modal-container` having `z-index: 4` on the deployed environments. 
On master it has `z-index: 9999` which overlays the sticky header, as expected. 

The weird part: It's been at `z-index: 9999` [for over a year](https://github.com/mozilla/testpilot/blame/7bf5108cf4d3e9adbf464405be1a0e8a76e01d2c/frontend/src/styles/modules/_modals.scss#L71) and I can't figure out where `z-index: 4` comes from.

**Comment by SoftVision-PaulOiegas** [comment]
Seems to be fixed, duno why it's still open.
