### ISSUE TITLE
I want to know the situation of tab-center

### ISSUE THREAD

**Issue by riocke** [mozilla/testpilot#3070]
Hello!

I used firefox for a long time, it seems that everything is perfect, the same is true of facts.

But I spend most of my day using the browser. When you open too many tabs, apparently the horizontal tab makes people panic. We find it hard to find the needed tab.

This problem has been bothering me until I see tab-center, It's so cool!!
Unfortunately, when I found it, it seemed to have stopped.

So I would like to ask, do you still have the possibility to restart this project?

Thanks!!

**Comment by SoftVision-PaulOiegas** [comment]
Hi @riockeio. This may happen in the future, but we cannot say for sure. It depends on a lot of things that for now are missing. 
However, there is a good alternative that looks better and better each day, and that was developed as webextension from scratch. I encourage you to try [Tab Center Redux](https://addons.mozilla.org/en-US/firefox/addon/tab-center-redux/) until then, since most of the Tab Center features are already implemented in it.

I personally loved Tab Center too, and was quite sad when it stopped working. Hated Tab Center Redux because it lacked some of the key features. But lately this changed a lot in the latest versions and I'm even impressed by some of the new features that were not on the original add-on. 
The only downside for now is that you'll have both horizontal and vertical tabs on the browser. But this is due to a current lack of API's that allows hiding the horizontal tabs in the new browser architecture. But this will change too in the future.

**Comment by lmorchard** [comment]
For what it's worth, this is pretty much the situation:

https://discourse.mozilla.org/t/whats-all-this-about-sunsetting-tab-center/15999/7

**Comment by fzzzy** [comment]
You might also consider the new webextension Tree Style Tab. I've really been enjoying it.

https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/

**Comment by riocke** [comment]
Yes! The extension I used before firefox57 is it.
Anyway, thank you!

________________________________
发件人: Donovan Preston <notifications@github.com>
发送时间: 2017年11月15日 9:23
收件人: mozilla/testpilot
抄送: riockeio; Mention
主题: Re: [mozilla/testpilot] I want to know the situation of tab-center (#3070)


You might also consider the new webextension Tree Style Tab. I've really been enjoying it.

https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/

―

**Comment by riocke** [comment]
ok...Tab Center Redux looks good.
________________________________
发件人: Les Orchard <notifications@github.com>
发送时间: 2017年11月15日 9:12
收件人: mozilla/testpilot
抄送: riockeio; Mention
主题: Re: [mozilla/testpilot] I want to know the situation of tab-center (#3070)


For what it's worth, this is pretty much the situation:

https://discourse.mozilla.org/t/whats-all-this-about-sunsetting-tab-center/15999/7

―

**Comment by riocke** [comment]
Thanks you!
I am trying Tab Center Redux, yes! it looks good!
________________________________
发件人: Softvision - Paul Oiegas <notifications@github.com>
发送时间: 2017年11月15日 2:01
收件人: mozilla/testpilot
抄送: riockeio; Mention
主题: Re: [mozilla/testpilot] I want to know the situation of tab-center (#3070)


Hi @riockeio<https://github.com/riockeio>. This may happen in the future, but we cannot say for sure. It depends on a lot of things that for now are missing.
However, there is a good alternative that looks better and better each day, and that was developed as webextension from scratch. I encourage you to try Tab Center Redux<https://addons.mozilla.org/en-US/firefox/addon/tab-center-redux/> until then, since most of the Tab Center features are already implemented in it.

I personally loved Tab Center too, and was quite sad when it stopped working. Hated Tab Center Redux because it lacked some of the key features. But lately this changed a lot in the latest versions and I'm even impressed by some of the new features that were not on the original add-on.
The only downside for now is that you'll have both horizontal and vertical tabs on the browser. But this is due to a current lack of API's that allows hiding the horizontal tabs in the new browser architecture. But this will change too in the future.

―
