### ISSUE TITLE
Update getting started docs

### ISSUE THREAD

**Issue by fzzzy** [mozilla/testpilot#3079]
There are a few things that can be simplified in the docs, and a few things that are missing that need to be documented w.r.t. running the integration tests.

For the initial install, we can remove all the `npm install` steps and recommend people run `npm run bootstrap` which does `npm install && cd addon && npm install && cd .. && gulp`. (Check to see if there are any other steps which should be added to this script. (I think the addon needs to be built as well?))

For the section where the 5 prefs have to be set manually, we should instead provide a user.js file that can be placed inside the profile to set them all. Softvision can provide this file.

We should document the `npm run test:all` command, which runs the tests, flow coverage checks, and the integration tests. However, we need to document the steps required to get the integration tests running, which I think involves installing geckodriver and `pip install tox`.

**Comment by fzzzy** [comment]
Download geckodriver from here:

  https://github.com/mozilla/geckodriver/releases

To install on OS X, put it on the $PATH.

**Comment by kgeorgiou** [comment]
Also the section about [DevPrefs](https://addons.mozilla.org/en-US/firefox/addon/devprefs/) extension will need to be adjusted since it seems it's not compatible with Firefox Quantum.

**Comment by ghost** [comment]
Alright, this is from last year, so I'm trying to interpret it.  We have two docs that are related to what this issue is talking about:

https://github.com/mozilla/testpilot/blob/master/docs/development/quickstart.md
https://github.com/mozilla/testpilot/blob/master/docs/development/testing.md

Quickstart addresses the npm commands above.  Testing.md talks about setting up the integration tests.  You still have to set the prefs individually, but I don't think that's something that needs to change.  The test:all command is documented, as well as installing geckodriver and tox.

So... I'm going to close this issue.  If there are further changes needed please open a new issue (one for each change) and be specific about the changes.  Thanks!
