### ISSUE TITLE
Experiment card hover state should not have blue title

### ISSUE THREAD

**Issue by youwenliang** [mozilla/testpilot#3091]
Experiment card hover state should not have blue title.

Current Implementation:
![image](https://user-images.githubusercontent.com/8919308/33166163-3f5405f2-d074-11e7-95d0-64d454ba529c.png)

Spec:
![image](https://user-images.githubusercontent.com/8919308/33166181-4ce29454-d074-11e7-8580-c5af17e1d297.png)

**Comment by SoftVision-PaulOiegas** [comment]
Well, that was the old behavior when card was hovered and we all probably missed that since we were so used to it. So, just to clarify, now the only things that should happen at card hover are:
1. Border showed around the card.
2. "Get started" / "Learn More" buttons color change when hovering them.

Am I right?

**Comment by youwenliang** [comment]
@SoftVision-PaulOiegas that is correct!

**Comment by SoftVision-PaulOiegas** [comment]
Seems to be as designed now. The experiment titles and subtitles are no longer highlighted. 👍
