### ISSUE TITLE
Test Pilot Homepage background gradient

### ISSUE THREAD

**Issue by youwenliang** [mozilla/testpilot#3095]
From the spec the homepage should have a gradient background from top #000F40 (100% opacity) to bottom #25003E (80% opacity), and the experiment section has a #000000 15% opacity overlay while the email subscription section has a #ffffff 5% opacity overlay.

checkout the spec here: https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Homepage_20170927/
![image](https://user-images.githubusercontent.com/8919308/33167121-81792428-d077-11e7-882e-590a8f516f58.png)

**Comment by SoftVision-PaulOiegas** [comment]
@youwenliang @johngruen This was implemented, but for me at least, the gradient looks awkward. I'm seeing it like strips of different colors instead of a smooth gradient. Are you guys sure that this is right? Tested on Windows 10 and Mac OS 10.11 and it looks the same on both.

The old implementation looked way better, and the colors were richer also. Now it looks kind of pale...

**Comment by SoftVision-PaulOiegas** [comment]
John has already made a PR for this (#3132) so I'll mark this as verified.

**Comment by youwenliang** [comment]
@SoftVision-PaulOiegas I did see the strips of colors but not sure why...I'll take a look into this.
