### ISSUE TITLE
2017-12-6 on stage

### ISSUE THREAD

**Issue by fzzzy** [mozilla/testpilot#3127]
Please test!

**Comment by fzzzy** [comment]
Actually, it looks like stage hasn't updated since November 13. Dev looks correctly up-to-date. I will work with relud or miles tomorrow to figure out what is going on with stage.

Please test dev!

**Comment by SoftVision-PaulOiegas** [comment]
I think it's better to wait for a proper stage server deploy to run our tests. We are also a bit overwhelmed today with tasks on experiments and Cosmin is in PTO. If you guys manage to deploy stage today, I'll start the run today and finalize it tomorrow together with Cosmin which returns tomorrow too. 
And if everything is ok with stage tomorrow, we'll test also the production server when you wake up and deploy.

In the meantime I will verify the latest changes on dev server.

**Comment by fzzzy** [comment]
Ok. Thanks!

**Comment by fzzzy** [comment]
Ok, stage is now fixed, and a new release with one more css commit, 2017-12-5, is on stage.

**Comment by fzzzy** [comment]
We did another release, 2017-12-6, which is on stage and prod now.

**Comment by SoftVision-PaulOiegas** [comment]
Stage and production both look ok. Just finalized production testing with a 95% pass rate. Will add tomorrow a full testing report for both and close this.

**Comment by SoftVision-PaulOiegas** [comment]
Testing results

## New issues: ##
1. ~~#3136 - Test Pilot Homepage lacks the CSS formatting **(major)**~~
2. #3137 - Experiment tour header wrongly says that experiment is enable even if Test Pilot and the experiment are not
3. ~~#3138 - Experiment tour modals are displayed oversized on other browsers than Firefox **(normal)**~~
4. ~~#3139 -[Responsive UI][Experiment details] The "Firefox Free Download" button for unsupported browsers is wrongly alligned to left on mobile view **(minor)**~~
5. ~~#3140 - Experiment details page top part subtitle is wrongly aligned to left for some of the localizations **(normal)**~~
6. #3142 - Experiment gets enabled and tour modal is displayed only when the install confirmation doorhanger is dismissed **(normal)**

## Known issues: ##
1. #3059 - The "Enter" key wrongly advances you to error dialog after you checked the privacy notice and deleted the entered string
2. #3042 - [Newsletter] Notification that informs about the need to check the privacy notice checkbox is no longer displayed
3. #3048 [Newsletter forms] The privacy notice message checkbox shortly disappears after hover, check and hover away actions

Since it's a late report, the striketrough items are already fixed. Only 2 and 6 are still occurring with the ones from known issues. We strongly suggest to fix all the remaining issues from the report in the next milestone since all are user facing ones and easy to encounter.

Closing this issue as the changes are already on production.
