### ISSUE TITLE
Pinterest Browser Button stopped working on both browsers

### ISSUE THREAD

**Issue by kitchen5203** [mozilla/testpilot#3133]
I started preferring the Firefox reaction to my saves on Pinterest immediately, but at that point Pinterest seemed to stop allowing my use of Safari, and when I opened the New York Times and found important news I could save to several of my sites, but not Pinterest, because suddenly they didn't allow me to share using either browser, yet it recognizes me. What is that about? Is Pinterest causing issues with their browser attention, like Google is trying to guide people to insist on Google to play videos on YouTube. I'm feeling like Net Neutrality is already being thrown in the trash.I miss Obama.

**Comment by SoftVision-PaulOiegas** [comment]
Hi @kitchen5203 and thanks for your report. Is this issue related to Test Pilot and its experiments or with the Firefox browser itself? I'm asking this because this GitHub repository is designed for the Test Pilot platform only. 
If the bug you mention is browser related only, then your issue must be filled in [Bugzilla](https://bugzilla.mozilla.org/enter_bug.cgi).

If your issue is indeed related to Test Pilot, can you please give us more details like, where is this Pinterest button located, provide a screenshot, provide some steps to reproduce, etc.
