### ISSUE TITLE
Release 2017-12-21 on stage

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#3157]
Tagging one more release for the year and pushing to [stage](https://testpilot.stage.mozaws.net/)

https://github.com/mozilla/testpilot/compare/2017-12-6...2017-12-21

**Comment by SoftVision-CosminMuntean** [comment]
We have finalized testing the stage server. Here are the testing results:

**New issues:**
- No new issues

**Known issues:**
#3137 - Experiment tour header wrongly says that experiment is enable even if Test Pilot and the experiment are not
#3142 - Experiment gets enabled and tour modal is displayed only when the install confirmation doorhanger is dismissed (normal)
#3042 - [Newsletter] Notification that informs about the need to check the privacy notice checkbox is no longer displayed
#3148 - [UI] All website modals have pixelated corners instead of perfectly round
#3048 - [Newsletter forms] The privacy notice message checkbox shortly disappears after hover, check and hover away actions

Considering the fact that we haven't found any new issues and most of the known issues are already assigned for the next sprints, we are good for deploy to production.

**Comment by lmorchard** [comment]
Going to consider this QA:verified and deploy to production

**Comment by lmorchard** [comment]
[And it looks like this release has finished deploying](https://testpilot.firefox.com/__version__)
