### ISSUE TITLE
Changing content requires killing server and restarting

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#3172]
This is probably a dev papercut only, but as i add new items to the news feed, i notice things like assets and URLs getting out of step with the news item and/or news items not showing up at all.

Not sure if this is to do with gulp/webpack getting into a fight, but i figured i'd file anyway since it's a bit of a nuisance. 

## STR
1. start the server locally
2. add a new item to the `news_updates.yaml` file
3. refresh the page

## Expected
The news feed page should reflect the new set of updates accurately

## Actual
Images and Icons do not seem to align with the text in news feed items

Again, this can be remediated by re-running npm start

**Comment by lmorchard** [comment]
Took me a few tries to actually realize I was reproducing this issue. Seems like it's weirder than a gulp/webpack thing.

The server *does* successfully rebuild the JSON data for news items on changes to news_updates.yaml. It does *not* seem to rebuild the static /news page HTML with updates. So, when the page loads, React should update the DOM with fresh news items.

However, it looks like React gets confused and applies incorrect updates to the DOM from the new set of update item content. Icons stay in their old positions on incorrect updates.

The reason why restarting the local server fixes things is because it rebuilds the static HTML and React doesn't need to apply any changes on page load.

This *shouldn't* happen on prod / stage / dev, since we do a full site rebuild on every deploy.

**Comment by lmorchard** [comment]
Further investigation: Although the news feed page HTML is getting rebuilt on YAML changes, it's getting rebuilt with stale content cached in memory by the gulp task. However, the JSON used by React gets rebuilt with fresh content. So, the server-side static HTML ends up with old content, while the client-side React components try to render new content on top.

Since we upgraded to React 16, [server-generated HTML that differs from client-side HTML doesn't get fully fixed up](https://hackernoon.com/whats-new-with-server-side-rendering-in-react-16-9b0d78585d67?token=nVWMJUyuYkp0s6eL). So, weird things happen like news items having the wrong images. 

Going to see if that gulp task can get its cache refreshed to update the static page correctly.

**Comment by lmorchard** [comment]
FWIW, even though this mainly looks like a dev papercut, I'm spending some time digging into this because I worry it *could* end up being a prod issue. (e.g. when some time-based thing changes markup on the client that differs enough from the server to cause breakage on the page because React gets confused)

**Comment by lmorchard** [comment]
Gave up on futzing with caching in gulp and just nuke server-side DOM in a PR. Seems like that may head off some worse problems in the future that might occur in production.
