### ISSUE TITLE
Drop bootstrap prefs reading/writing code

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#3180]
This is bootstrap-y:

> Prefs (read-only) - legacy method for configuring add-on for current environment (i.e. dev / stage / prod)

> Prefs (read/write) - Backing up and enabling prefs for telemetry, healthreport, beacon.enabled

**Comment by lmorchard** [comment]
I think this is a thing we can just drop. If I understand recent changes to Telemetry correctly, these pref changes won't be respected for us anyway in the near future

**Comment by lmorchard** [comment]
Oh, wait, there's a pref unrelated to Telemetry that we still use: `testpilot.env`

If / when we lose access to prefs, we need some other mechanism for deciding which environment the add-on should use. Maybe settings in about:addons? I think we avoided that at first because we didn't want to make the setting easily discoverable

**Comment by fzzzy** [comment]
Would it be acceptable to have the pref in about:addons if we just label it as "for development of testpilot use only"?

**Comment by meandavejustice** [comment]
bumping this to get discussion going again,

@fzzzy I think the pref in about:addons is reasonable but not preferable... I wonder if we could show it only on dev builds, check for an environment variable, though that could be a bit of a pain as well.
