### ISSUE TITLE
content not loading with Firefox in safe mode

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/testpilot#3199]
User agent, reported by <https://udger.com/resources/online-parser>: 

`Mozilla/5.0 (X11; FreeBSD amd64; rv:56.0) Gecko/20100101 Firefox/56.0`

With (slightly outdated) Firefox 56.0.2 in safe mode I get only the sky, and the fox in its spacecraft: 

![2018-01-08 14 33 09 firefox test pilot - mozilla firefox](https://user-images.githubusercontent.com/192271/34675282-07c8a670-f481-11e7-865d-302cfa589cc1.png)

Should we expect the site to work with Firefox-based browsers in safe mode?

**Comment by SoftVision-PaulOiegas** [comment]
Hi @grahamperrin and thanks for your report. Can you tell me exactly on what browser and what OS are you experiencing this?
I'm asking this because, testing on official Firefox 56.0.2 release using Safe Mode on Ubuntu 14.04 and Windows 10, I'm not experiencing this issue.

Also tried Tor browser and Waterfox. While Waterfox is working properly, on Tor browser the Test Pilot website is not working due to Firefox 54.x as being the minimum version supported (Tor is based on ESR 52.x).

I'm wondering if this is not something related to your profile preferences. Can you please create a new profile and retry?

**Comment by grahamperrin** [comment]
```text
[grahamperrin@momh167-gjp4-hpelitebook8570p-freebsd] ~% date ; uname -v
Sun 14 Jan 2018 17:23:52 GMT
FreeBSD 12.0-CURRENT #0 r320869: Mon Jul 10 13:57:55 UTC 2017     root@releng3.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC 
[grahamperrin@momh167-gjp4-hpelitebook8570p-freebsd] ~% pkg info firefox | grep -i version
Version        : 56.0.2_9,1
```

Strangely, I can no longer reproduce the issue with any profile that's used by Firefox.

**Comment by SoftVision-PaulOiegas** [comment]
Great, thanks for further investigating this. Glad it doesn't occur anymore. 
Have a nice week!
