### ISSUE TITLE
Experiment onboarding modals should not have "enabled" label

### ISSUE THREAD

**Issue by youwenliang** [mozilla/testpilot#3220]
There's an enabled label on the top left corner of the modal, which should not be there.
![image](https://user-images.githubusercontent.com/8919308/34758193-f87dd5fa-f610-11e7-8bc2-8ea8624fec79.png)

**Comment by SoftVision-PaulOiegas** [comment]
Hmmm, then we wrongly understood this storybook design (#3149)? 
There was a design that had no "Enabled" string in it [here](https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Component_20171003/#artboard0), which is mandatory. And there was a Storybook deploy for Tour that had the "Enabled" label. So combining the received design with the storybook deploy, I thought it should be there.

If not, then both the design and Stoybook were wrong because one was missing the word in title and one was having it without a specific design...

To be honest I like how it looks, and the resemblance with the experiment cards, and now also with the news modal that displays the same [label](https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Modal_Photon_Styles/#artboard1). But it's up to you guys if you want to change it back.

**Comment by SoftVision-PaulOiegas** [comment]
The removal of the label was implemented but we forgot to add back the "enabled!" string. Filled separately #3254 for this.

**Comment by ChenMorpheus** [comment]
@marniepw @SoftVision-PaulOiegas I checked several related tickets (#3149, #3220) and I guess there was a confusion here. There are two kinds of modal; one is the onboarding modal which appears after users enable an experiment(see img_1); the other one is the updates modal which emerges once there is an update to an experiment(see img_1). These two modals share the similar style, but there is a difference.

Onboarding tour doesn't need to have "enabled" label since it happens right after users enable experiment. As for updates modal, it needs the "enabled" label to inform users two states: default and enabled(see img_2 and img_3). However, they don't have "enabled" on the header regardless of different modals.

Please check the links below for difference. 
https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Modal_Photon_Styles/#artboard0

https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Component_20171003/#artboard0

![image](https://user-images.githubusercontent.com/18019946/35263252-fb8cde16-0052-11e8-8169-907f03c4e977.png)
img_1

![image](https://user-images.githubusercontent.com/18019946/35263029-11160588-0052-11e8-9b68-62bf85163270.png)
img_2

![image](https://user-images.githubusercontent.com/18019946/35263469-cf9f182c-0053-11e8-91a4-9ace77e7edda.png)
img_3
