### ISSUE TITLE
Checkbox style should follow design system

### ISSUE THREAD

**Issue by youwenliang** [mozilla/testpilot#3221]
As title.

Normal mode
Current:
![image](https://user-images.githubusercontent.com/8919308/34758409-983f4240-f611-11e7-9d4e-a425dbd7bd56.png)

Spec:
![image](https://user-images.githubusercontent.com/8919308/34758422-a73f7364-f611-11e7-96d4-a4bd171dda7e.png)

Dark mode
Current:
![image](https://user-images.githubusercontent.com/8919308/34758248-40d546c6-f611-11e7-8d53-78db733c9611.png)

Spec:
![image](https://user-images.githubusercontent.com/8919308/34758315-6437d6ec-f611-11e7-91b2-bbb8d45c03b7.png)

**Comment by johngruen** [comment]
@youwenliang you want the checkbox string to overflow the width of the form?

**Comment by SoftVision-PaulOiegas** [comment]
@johngruen I think he was actually referring to the checkbox design. 
1. For the modal it should be a blue checkbox with a white check mark when selected (spec). 
2. For the in page Newsletter it should be a "purple" checkbox with white border and a white check mark (spec). 
Also, for the in page Newsletter, the font must have a bit of transparency if I'm seeing well.

**Comment by ChenMorpheus** [comment]
@johngruen @SoftVision-PaulOiegas We created both light and dark mode for various components, including primary/default buttons, checkbox, etc. That's why the box here has two versions of the dark and light background. It's under discussion to collect these defined dark mode components into Design System so that all Firefox websites with dark background could follow our elements afterward. 

> Also, for the in page Newsletter, the font must have a bit of transparency if I'm seeing well.

I don't mean to correct @SoftVision-PaulOiegas >.<. But the font doesn't have transparency. It's regular size. Please find the details below.
![image](https://user-images.githubusercontent.com/18019946/34977012-f044c0d4-fad3-11e7-8d4b-8d7c97e14479.png)

As for John's question, no, it doesn't have to overflow the width of the form. But the alignment should be like this:

![image](https://user-images.githubusercontent.com/18019946/34977394-5772ae32-fad5-11e7-8b63-01871267edce.png)
