### ISSUE TITLE
New Experiement Card measurements

### ISSUE THREAD

**Issue by youwenliang** [mozilla/testpilot#3224]
Current implementation:
![image](https://user-images.githubusercontent.com/8919308/34758829-9f91f658-f613-11e7-899d-afd259a292f4.png)

Spec new design:
![image](https://user-images.githubusercontent.com/8919308/34758824-98e5c0d2-f613-11e7-9e6a-e13c728e778e.png)

Full spec here: https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Photonized_Txp_Website_Final/#artboard2

And here for different status: https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Photonized_Txp_Website_Final/#artboard7

Also new changes on the feedback button:
![image](https://user-images.githubusercontent.com/8919308/34758925-1fa3553a-f614-11e7-8a99-a7ebb621109b.png)

**Comment by SoftVision-PaulOiegas** [comment]
Wasn't the card size issue discussed before and everyone agreed that they seem too narrow in the designs?

**Comment by ChenMorpheus** [comment]
@SoftVision-PaulOiegas  If I recall correctly, I remembered John told us it was too narrow and UX team didn't have time to fix that since it was too close to release date. Hence, we said, "let's scale it up for now, and Peko will provide a refined version to replace the temporary change." And this one is the refined version. @johngruen Please correct me if I am wrong, thanks.

**Comment by SoftVision-PaulOiegas** [comment]
Could be, lots of changes occurred back then, so I probably missed this bit. Thanks for clarification! 👍
