### ISSUE TITLE
Extreme loading jank on dev and local

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#3251]
This might be on my machine or something, but maybe @SoftVision-PaulOiegas can verify.

## STR
1. Have Test Pilot Installed and have the Notes experiment enabled
2. Go to `testpilot.dev.mozaws.net`

## Result
The state of the featured experiment first shows up as Test Pilot not being installed, then rerenders as the featured experiment installed state.

## Expected
The right state is rendered first w/o a lot of jank.

Note: this bug is reproducible in some form across all views.

![state issue](https://user-images.githubusercontent.com/3323249/34984967-e30152fa-fab2-11e7-92d2-4af37b1e681a.gif)

**Comment by johngruen** [comment]
Note that the featured experiments section is not the only issue...icons as well as page content seems to flicker in and out randomly as the page loads.

**Comment by johngruen** [comment]
I can think of some easy CSS hack ways to fix this, by setting animation delays and fading in the `view` component, but i suspect what's going on here is to do with react lifecycle issues.

**Comment by SoftVision-PaulOiegas** [comment]
Obtained a bit different results on our end. For us, only the experiment appears as not enabled for ~1 second on an old iMac (late 2009) and almost not visible on a Windows 10 machine.

Here are the screen recordings:
- MacOS 10.13 with 1 tab opened only - https://goo.gl/bRdZcW
- MacOS 10.13 with multiple tabs opened - https://goo.gl/SSkTGU
- Windows 10 x64 1 tab & multiple tabs - https://goo.gl/gyi2z3

I have seen this short delay in displaying the experiment state on WIndows a few days ago, but since it is so short on WIndows, I've decided not to log it. 
However, if someone can reproduce John's behavior, where TxP add-on also appears as not installed, that's something else.

**Comment by johngruen** [comment]
Okay, I'd like to see if other ppl can repro this at all. I'll test on new profiles and VMs on my machine.

**Comment by johngruen** [comment]
Here are some more examples of the issue on my Win10 VM. Shows the problem with both the homepage and experiment details page

Ed. Removed b/c the gifs don't actually show anything (probably to do with trying to screencapture from a mac app into the vm)...will add new ones soon.

Ed. 2 Here's a a screen recording showing both cases https://www.dropbox.com/s/8u7uhtmh1gk8s2l/the-flicker.mov?dl=0

**Comment by johngruen** [comment]
Note that this seems to be limited to local env, but there's still a little flicker on dev.

**Comment by marniepw** [comment]
Feel free to reopen if you can reproduce.
