### ISSUE TITLE
Add back the "enabled!" string on enabled experiment tour modal header

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3254]
**[Notes]:**
- This was removed in #3149 along with adding the "Enabled" label. It seems that I wrongly understood the designs and this should return to the old implementation. The label was already removed in #3220.

**[Affected versions]:**
- Firefox 57.0.4 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".
- Test Pilot add-on was already installed on the same profile. 

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.dev.mozaws.net/experiments page.
2. Click on any of the active experiments cards that are not yet enabled (except Send).
3. Click the "Enable <experiment_name>" button.
4. Choose to "Add" the extension when asked in doorhanger (except for Min Vid).
5. Observe the displayed tour modal and compare it with the designs.

**[Expected result]:**
- The modal is 100% following the design

**[Actual result]:**
- The modal header is missing the "enabled!" string after the experiment name.

**[Notes]:**
- Here is a screenshot of how the modal should look like:

![tour modal title](https://user-images.githubusercontent.com/17258026/34991947-1c438ecc-fad4-11e7-9b5b-8f462f79f30b.png)

**Comment by marniepw** [comment]
@ChenMorpheus can you please verify what you'd like to see here.

**Comment by ChenMorpheus** [comment]
@marniepw @SoftVision-PaulOiegas I checked several related tickets (#3149, #3220) and I guess there was a confusion here. There are two kinds of modal; one is the onboarding modal which appears after users enable an experiment(see img_1); the other one is the updates modal which emerges once there is an update to an experiment(see img_1). These two modals share the similar style, but there is a difference.

Onboarding tour doesn't need to have "enabled" label since it happens right after users enable experiment. As for updates modal, it needs the "enabled" label to inform users two states: default and enabled(see img_2 and img_3). However, they don't have "enabled" on the header regardless of different modals.

Please check the links below for difference. 
https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Modal_Photon_Styles/#artboard0

https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Component_20171003/#artboard0

![image](https://user-images.githubusercontent.com/18019946/35263252-fb8cde16-0052-11e8-8169-907f03c4e977.png)
img_1

![image](https://user-images.githubusercontent.com/18019946/35263029-11160588-0052-11e8-9b68-62bf85163270.png)
img_2

![image](https://user-images.githubusercontent.com/18019946/35263469-cf9f182c-0053-11e8-91a4-9ace77e7edda.png)
img_3

**Comment by SoftVision-PaulOiegas** [comment]
Long story short, this issue just became invalid based on your explanation. Thanks for the clarifications!

However, I still believe that having the "Enabled" green label on every modal related to an enabled experiment would have been more consistent and user friendly. But maybe that's only my opinion... after all it's your call.
