### ISSUE TITLE
All strings are shortly displayed in English before they are displayed in Firefox build localization

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#3318]
**[Notes]:**
- The issue is also reproducible for any language other than English set in "about:preferences#content".
- This behavior can also be observed the page is refreshed.

**[Affected versions]:**
- Firefox 57.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".
- Have a Firefox localized build other than English.

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.dev.mozaws.net/ page.
2. Observe the page language while it's loading.

**[Expected result]:**
- The page is correctly displayed in the default localized Firefox build.

**[Actual result]:**
- All strings are shortly displayed in English while the page is loading.

**[Additional Notes]:**
- This issue is probably related to #3269. 
- This issue is also reproducible on stage and production servers.
- Here is a screen recording of the issue: https://goo.gl/bkRFPV

**Comment by lmorchard** [comment]
FWIW, I think we've had this issue since we started rendering the site statically and dropped the loading spinner. All pages are served up in English, translated strings aren't applied until our JS code starts up and the first React rendering happens. This could be more or less easily noticed depending on how fast your browser starts up the page.

We've also got [this issue for re-structuring the site so that the locale is in the URL](https://github.com/mozilla/testpilot/issues/3008), and then we can render pages in locales on the server.

Could also be made less noticeable past the first load by re-introducing React Router, so that subsequent clicks are handled by the already-loaded page app

**Comment by chuckharmston** [comment]
This is something that will be solved by #3405, but I'm going to leave it open so we can do specific testing on this after that lands.

**Comment by SoftVision-PaulOiegas** [comment]
@chuckharmston this behavior was partially fixed by the merge of #3405, the right translation is displayed while navigating trough pages. But, if you refresh most of the pages, this still occurs.

This issue also occurs on localized builds, not only on [en-US] with content language changed. Which means that all the users using a localized build other than [en-US], will first see the English version of the website when navigating to Test Pilot and only after the right localization. 
But from that point further, the right one when just navigating trough pages.

This decreased the rate of encounter, but on the other hand, it's still there... Mostly for non [en-US] users which I assume are more numerous than the ones that change the content language on [en-US] builds.

**Comment by dannycoates** [comment]
mitigated by the loading spinner in #3484

**Comment by SoftVision-PaulOiegas** [comment]
Works like a charm. 👍
