### ISSUE TITLE
English strings appear in the middle of terms and privacy sentence for Notes

### ISSUE THREAD

**Issue by flodolo** [mozilla/testpilot#3344]
Image is from the [l10n demo](https://testpilot-l10n.dev.mozaws.net/), but the same happens on prod

![schermata 2018-02-12 alle 14 24 58](https://user-images.githubusercontent.com/3644868/36098812-a3e4bdf6-1000-11e8-8d17-ce490aa84242.png)

Strings are from #3286, so they have been localized for a while at this point.

**Comment by SoftVision-PaulOiegas** [comment]
@flodolo Something must have happened since last week public deploy. We have checked the localization for that string on Dev, Stage and Production servers and it was all ok. 
This was tested especially since the "Featured Experiment" section launch was delayed 1 sprint due to it. So I'm quite sure it was ok last week.

**Comment by dannycoates** [comment]
fixed in #3517
