### ISSUE TITLE
Additions to Test Pilot Recommendations

### ISSUE THREAD

**Issue by ianb** [mozilla/testpilot#3354]
Some additional things that could be documented in [Test Pilot Recommended Development Process for Experiments](https://github.com/mozilla/testpilot/blob/master/docs/experiments/developing_an_experiment.md):

- At what stage in an experiment does this stuff apply? Prototype? After being "accepted"? (Is that a formal thing?)
- If you are a team coming in with your own resources (e.g., a team's priorities are to experiment in some area), what should you do to properly establish a relationship with Test Pilot? (If you don't have your own resources, *getting* resources is probably that thing)
- Who should you invite to meetings? Or optionally invite?
- Where should the meetings be published?
- What GitHub org should you use for your repo? If you start it elsewhere, should you move it?
- I assume you really want people to use [testpilot-ga](https://www.npmjs.com/package/testpilot-ga), but calling that out directly would be good.
- Who reads the analytics? How often?
- How should people interface with QA? When? What expectations should there be?
- What level of polish do we expect in an experiment?
- When do we do user testing? What's expected of the experiment at that time?
- Anything to say about WebExtensions and/or Web Experiments?
- What if you want to have an experiment that isn't an add-on?
- Who puts together the copy for the page, images, etc?
- Are there people who can help with UX, UI, design, etc? Generally: if you feel your team doesn't have all the skills necessary before shipping, who should you talk to?
- What's a good team size? Or maybe easier: what's a bad team size?
- CI recommendations? CI or testing requirements? (If there aren't, then it's worth saying that)
- What kind of schedule does Test Pilot want to see for an experiment? How do you talk about / notify people about slippage or risk?
- Security review, privacy review, etc.
- Localization: how should it be done? Is it a hard requirement? What if it slips?
- Where do you ask for help on stuff? E.g., #testpilot, #l10n, #teamaddons (or #extdev?), etc.
- Any preferred stack or tools? E.g., React, Webpack, blah blah. Probably not a requirement, but people often want to be told what to do in order to fit in.

**Comment by ghost** [comment]
Thanks Ian!

>     At what stage in an experiment does this stuff apply? Prototype? After being "accepted"? (Is that a formal thing?)
>     If you are a team coming in with your own resources (e.g., a team's priorities are to experiment in some area), what should you do to properly establish a relationship with Test Pilot? (If you don't have your own resources, getting resources is probably that thing)
I revised our project checklist and added reviewing this document to our kickoff meeting notes, which I think will address these.

>     Who should you invite to meetings? Or optionally invite?
>     Where should the meetings be published?
I'll add a link to our calendar.

>     What GitHub org should you use for your repo? If you start it elsewhere, should you move it?
I clarified the GitHub paragraph, although it's not really a deal breaker I think.

>     I assume you really want people to use testpilot-ga, but calling that out directly would be good.
It's called out directly in the linked doc (ga.md).

>     Who reads the analytics? How often?
>     How should people interface with QA? When? What expectations should there be?
These are going to depend on the experiment too, and will come up as we move through the process spreadsheet (linked below, because I'm doing some of these out of order, sorry).

>     What level of polish do we expect in an experiment?
This will depend on the experiment and be a part of how we define the MVP.

>     When do we do user testing? What's expected of the experiment at that time?
This is part of the [process doc](https://docs.google.com/spreadsheets/d/1ma8o8Qi436q1hjV3YaB1otmBdQCe5zdG29WsHbuOL9c/edit#gid=0)

>     Anything to say about WebExtensions and/or Web Experiments?
>     What if you want to have an experiment that isn't an add-on?
Good idea, added a paragraph about these two.

>     Who puts together the copy for the page, images, etc?
>     Are there people who can help with UX, UI, design, etc? Generally: if you feel your team doesn't have all the skills necessary before shipping, who should you talk to?
These are part of the process spreadsheet.

>     What's a good team size? Or maybe easier: what's a bad team size?
>     CI recommendations? CI or testing requirements? (If there aren't, then it's worth saying that)
I added a paragraph about CI.  Not sure how to fit team size in...seems like that would depend on the people.

>     What kind of schedule does Test Pilot want to see for an experiment? How do you talk about / notify people about slippage or risk?
I mention two week sprints being good.  The process doc and check-ins should handle the notifications and slipping scenarios.

>     Security review, privacy review, etc.
These are rows in the process spreadsheet.

>     Localization: how should it be done? Is it a hard requirement? What if it slips?
Depends on the experiment.

>     Where do you ask for help on stuff? E.g., #testpilot, #l10n, #teamaddons (or #extdev?), etc.
We've got stand-ups a couple times per week.

>     Any preferred stack or tools? E.g., React, Webpack, blah blah. Probably not a requirement, but people often want to be told what to do in order to fit in.
I'm afraid if I put this in the doc it'll be out of date in no time.  That seems like something we can talk about when we kick off.

Sorry for the "it depends on the experiment" answers, but I think a lot of it does.  The process doc makes sure we don't forget things.
