### ISSUE TITLE
Everything the Add-on should do before we stop working on it

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#3382]
This is intended to track discussion about the add-on once we remove all bootstrap components.

Here's a list of all of the things the add-on should do:

1. When installed, it should register a browserAction in the Firefox Toolbar
2. When clicked, that toolbar button should take the user to one of the following:
`${URL}/experiments?utm_source=testpilot-addon&utm_medium=firefox-browser&utm_campaign=testpilot-doorhanger&utm_content=${not+badged || badged}`
3. Any time a new experiment is added to test pilot, the add-on should be badged for two weeks or until a user clicks on the add-on.
4. Any time a new *major* news item is added to the test pilot site, the icon should be badged for two weeks or until the user clicks on the add-on.

I would also like to add the following metrics pings to the add-on:
1. A daily GA ping that sends us a list of installed Test Pilot add-ons.

As we move to slow down test pilot add-on development is there anything else we'd like to see? Is there anything I'm missing from this list? @chuckharmston @lmorchard @fzzzy @meandavejustice @clouserw

**Comment by johngruen** [comment]
unassigned dave since this is a discussion bug and @meandavejustice is out for awhile. we can discuss this in our next sprint planning

**Comment by jaredhirsch** [comment]
> 1. A daily GA ping that sends us a list of installed Test Pilot add-ons.

GA ping or Telemetry ping?

**Comment by lmorchard** [comment]
I think we've been thinking GA ping, not thinking [bug 1280234](https://bugzilla.mozilla.org/show_bug.cgi?id=1280234) would be resolved. Maybe that will be too pessimistic?

**Comment by SoftVision-PaulOiegas** [comment]
@meandavejustice This clearly removed the need of the `extensions.legacy.enabled` pref. But what about the `extensions.install.requireBuiltInCerts` one? 
I've just tried on Dev edition and the website loads and TxP add-on can be installed just with `extensions.webapitesting` on `true` and `xpinstall.signatures.required` on `false`.

**Comment by lmorchard** [comment]
I might be mistaken, but off the top of my head I think these remaining prefs are more about *installing* the add-on and not related to the implementation of the add-on itself...

* `extensions.install.requireBuiltInCerts` needs to be `false` - otherwise Firefox restricts installing add-ons to sites whose SSL certificates are explicitly shipped in the binary as a security measure. That set excludes our local, dev, and staging servers. If you *can* install it from dev or stage without that set to false, something may have changed. (I can't remember if this completely *blocks* add-on installation or throws up more warnings)

* `xpinstall.signatures.required` is mainly for local env, where we don't usually sign the add-on. It *is* signed on dev, stage, and prod - so that shouldn't matter there, but I think we specify setting it since we often try things on local env.

* `extensions.webapi.testing` enables `mozAddonManager` for non-whitelisted sites (like dev, stage, and local) - and `mozAddonManager` is used for installing and detecting add-ons from the Test Pilot site. I don't think the add-on changing to a webextension removes the need for that

My memory is fuzzy on this, but there *might* be some relaxing of rules for each of the above while using Firefox Developer Edition.
