### ISSUE TITLE
News feed page

### ISSUE THREAD

**Issue by Pekochen** [mozilla/testpilot#3398]
<img width="1302" alt="screen shot 2018-03-05 at 10 45 00" src="https://user-images.githubusercontent.com/8252151/36955269-6543179c-2062-11e8-962d-60a1b5f70d99.png">
There are two things need to be modified.
Please see the attached image.
1.test pilot image. please remove black outstroke.
2.There should not be a divider between each segment.

**Comment by SoftVision-PaulOiegas** [comment]
@Pekochen just one question regarding 1. Since all the articles for experiments have a round logo, shouldn't Test Pilot have one also to be consistent? Unless you want to clearly differentiate the platform from experiments.
That's why we haven't logged this as an issue in the first place, thinking it's intended.

**Comment by Pekochen** [comment]
![image 1](https://user-images.githubusercontent.com/8252151/37017713-93d8e312-214c-11e8-957a-47a53d3f8ddb.png)
how about using this simple test pilot icon with a circle? It may look more consistent with others.

**Comment by ghost** [comment]
Closing in favor #3512
