### ISSUE TITLE
[Featured experiment] You are not redirected to /experiments page if page refresh is performed on the Notes tour after installation

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#3402]
**[Notes]:**
- If Test Pilot is already installed and you navigate to "https://testpilot.dev.mozaws.net" page, you are automatically redirected to the "/experiments" page. 

**[Affected versions]:**
- Firefox Nightly 60.0a1 

**[Affected Platforms]:**
- Windows
- Mac OS
- Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Start Firefox browser with the profile from prerequisite and navigate to https://testpilot.dev.mozaws.net page.
2. Click on "Install test Pilot & Enable Notes" big green button on top.
3. Confirm the doorhanger and click on the "Add" button on the next one displayed.
4. Confirm again by clicking "OK" on the 3rd one.
5. While the Notes tour is displayed refresh the page and observe the behavior.

**[Expected result]:**
- You are redirected to the "/experiments" page; Test Pilot and Notes are correctly installed.

**[Actual result]:**
- You are not redirected to the "/experiments" page even if Test Pilot is already installed.

**[Additional Notes]:**
- Here is a screen recording of the issue: 
![refreshing the page](https://user-images.githubusercontent.com/19226534/36985121-1965da7a-209f-11e8-92ce-9f7f99561bba.gif)

**Comment by dannycoates** [comment]
On master it doesn't redirect to /experiments but it does show the enabled state correctly

**Comment by SoftVision-PaulOiegas** [comment]
It does for the top part, but this is still an issue when it comes to the bottom of the page. The "Install the Test Pilot Add-on" green button is still displayed because of the no-redirect.

![screen shot 2018-03-26 at 18 58 53](https://user-images.githubusercontent.com/17258026/37919550-d6a60df6-312c-11e8-9961-67d7d383527c.png)

**Comment by dannycoates** [comment]
This is going to require some legit **work**

**Comment by dannycoates** [comment]
@johngruen what do you think about a popup flow that puts the email form first after a one click install? like so:

![popups](https://user-images.githubusercontent.com/87619/38069556-d5d6caf0-32cb-11e8-912f-57a059914c30.gif)

**Comment by SoftVision-PaulOiegas** [comment]
@dannycoates that was the initial desired behavior, but it had some issues where the pop ups overlapped or dismissed each other and it was simplified. 
However, since than we returned to react-router. If there is a better way to implement this flow now, without previous issues to be generated, I think it seems more appropriate. Of course, it's up to John to confirm. 

We had an issue that the newsletter pop up was only displayed for less than a second and after replaced by the Tour one on the Featured Experiment section.

**Comment by fzzzy** [comment]
The actual desired behavior is to have it integrated as the last slide of the tour.

**Comment by SoftVision-PaulOiegas** [comment]
> The actual desired behavior is to have it integrated as the last slide of the tour.

Wasn't that idea ditched? I think Chuck closed a bug (#2066) about this mentioning it will never happen. 😄

**Comment by fzzzy** [comment]
But if time is going to be scheduled to work on the email dialog, I think it would be good to do it the right way rather than yet another hack...

**Comment by SoftVision-PaulOiegas** [comment]
I agree, but I was under the impression that adding new stuff to the website was not a priority.

**Comment by SoftVision-PaulOiegas** [comment]
Seems ok, at least on Mac OS, where I can verify on local.
