### ISSUE TITLE
"Something is wrong" when visiting Firefox Test Pilot

### ISSUE THREAD

**Issue by lovexxx** [mozilla/testpilot#3442]
It says "something is wrong" when I try to visit testpilot.firefox.com using Firefox even if in safe mode, but the same page displays normally in my Microsoft Edge. Below is my application profile:

名称: Firefox
版本: 59.0.1
版本 ID: 20180315233128
更新通道: release
用户代理: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0
操作系统: Windows_NT 10.0
多进程窗口: 1/1（默认启用）
网页内容处理进程: 5/4
Stylo: content = true (默认启用), chrome = false (默认禁用)
Google 密钥: 存在
Mozilla 位置服务密钥: 存在
安全模式: true

I am wodering how to fix this bug and I'll appreciate it for your reply. Thanks a lot.

**Comment by SoftVision-PaulOiegas** [comment]
Hi @lovexxx and thanks for your report! Just tried to reproduce this on latest Firefox 59.0.1 build and I haven't managed to. Even downloaded the [zh-CN] localized build to check this and still no luck in reproducing it. 

This might be something related to your setup. Can you please navigate to about:config page and verify if the `privacy.resistFingerprinting.block_mozAddonManager` pref is somehow set to `true`? If yes, please change it to `false` and refresh the Test Pilot page afterwards.
The Test Pilot website uses "mozAddonManager" and this pref blocks it. Probably it was modified along the way with some changes on your machine since it's default value should be false.

**Comment by lovexxx** [comment]
@SoftVision-PaulOiegas Thank you. The issue is settled according to your suggestion.
