### ISSUE TITLE
review update-version script

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#3459]
This script is causing problems with web-ext. Do we still need it?

**Comment by lmorchard** [comment]
> This script is causing problems with web-ext. 

What are the problems?

> Do we still need it?

Yes, if we want a signed build of the add-on deployed to dev with every master commit without having to change the version number every time. (But, it's possible we *stop* caring about that at some point.)

**Comment by marniepw** [comment]
@meandavejustice can you expand on details here?

**Comment by meandavejustice** [comment]
> What are the problems?

@lmorchard The issue is with `web-ext lint`. It doesn't allow the version format that is generated by `update-version`

**Comment by fzzzy** [comment]
We had a similar problem in side view:

https://github.com/mozilla/side-view/pull/138

Each portion of the version number must be less than 32767. We worked around this by using the following to get a unique version number for every hour of the year:

`Math.floor((Date.now() - new Date(new Date().getFullYear().toString()).getTime()) / 3600000)`

This only produces unique version numbers down to a resolution of an hour, so it might not be good enough for test pilot.

**Comment by lmorchard** [comment]
FWIW, this might also be something to consider an upstream issue, if we consider this to be a valid version format for our own self-hosted add-on. (We basically do consider it valid, since we've been doing it this way for a very long time. But we could change our thinking on that.)

<strike>Also, I haven't seen what the exact error is yet - is it an *error* that fails the build? a noisy *warning* we can ignore / filter? something we can configure `web-ext lint` to ignore?</strike>

Okay, looks like this is exactly what we get from `npm run lint:extension`:
```
C:\Users\lmorchard\devel\testpilot\addon [3111-more-webpack +5 ~1 -0 !]
λ  npm run lint:extension

> testpilot-addon@3.0.0-dev-c4ce10c lint:extension C:\Users\lmorchard\devel\testpilot\addon
> web-ext lint --self-hosted

Applying config file: .\package.json
Validation Summary:

errors          1
notices         0
warnings        2

ERRORS:

Code           Message             Description                           File   Line   Column
JSON_INVALID   "/version" should   Your JSON file could not be parsed.
               match format
               "versionString"
WARNINGS:

Code             Message                Description                                  File                     Line   Column
DANGEROUS_EVAL   The Function           Evaluation of strings as code can lead to    build/webextension/ba…   727    11

                 constructor is eval.   security vulnerabilities and performance     ckground.js

                                        issues, even in the most innocuous of

                                        circumstances. Please avoid using `eval`

                                        and the `Function` constructor when at all

                                        possible.'

DANGEROUS_EVAL   eval can be harmful.   Evaluation of strings as code can lead to    build/webextension/ba…   727    43

                                        security vulnerabilities and performance     ckground.js

                                        issues, even in the most innocuous of

                                        circumstances. Please avoid using `eval`

                                        and the `Function` constructor when at all

                                        possible.'

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testpilot-addon@3.0.0-dev-c4ce10c lint:extension: `web-ext lint --self-hosted`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the testpilot-addon@3.0.0-dev-c4ce10c lint:extension script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lmorchard\AppData\Roaming\npm-cache\_logs\2018-04-12T16_44_23_418Z-debug.log
```

**Comment by lmorchard** [comment]
TL;DR: We could use build time like side-view, though what I really wanted from the version was a stable value tied to the git commit or release tag.

If we *really* want to hack this, we could find a hashing function that converts a git commit hash into a decimal numeral (< 32767) for a version like `1.2.3dev18675` - and hope that that numeral doesn't collide between updates to the rest of the version string. Of course, that doesn't get us any sequential numbers in the part after `dev` because the hash will be practically random.

* * * 

Did a little more research and [looked up the validation code](https://github.com/mozilla/addons-linter/blob/280fe4d4712b16d4393dd9a08e9312b56b223d2e/src/schema/formats.js#L5).  It supports [the toolkit version format](https://developer.mozilla.org/en-US/docs/Mozilla/Toolkit_version_format):
```
const TOOLKIT_VERSION_REGEX = /^(\d+\.?){1,3}\.(\d+([A-z]+(-?\d+)?))$/;
```

That gets us stuff like `1.2.3`, `1.2.3foo4` - but not 1.2.10c4ce10c because [the toolkit version format](https://developer.mozilla.org/en-US/docs/Mozilla/Toolkit_version_format) lets us use `{base10}.{base10}.{base10}{word}{base10}` and never a mixed-letter-and-number hexadecimal hash.

**Comment by dannycoates** [comment]
`gitHash.split('').sort().reverse().join('')` 😂

**Comment by fzzzy** [comment]
@lmorchard The limiter on the format is Google Chrome. web-ext lint just enforces what Google Chrome requires. It's not possible to turn it off with a directive. I think finding a hashing function that can generate < 32767 is a great idea!

**Comment by dannycoates** [comment]
Using my joke "hash" produces a version like `3.0.0devdba99510` which warn about it being Firefox specific, but passes.

```
> testpilot-addon@3.0.0-devdba99510 lint:extension /Users/dcoates/code/testpilot/addon
> web-ext lint --self-hosted

Applying config file: ./package.json
Validation Summary:

errors          0
notices         1
warnings        0

NOTICES:

Code                        Message                         Description                                                  File            Line   Column
PROP_VERSION_TOOLKIT_ONLY   The "version" property uses a   See http://mzl.la/1kXIADa (MDN Docs) for more information.   manifest.json
                            Firefox-specific format.

> testpilot-addon@3.0.0-devdba99510 package /Users/dcoates/code/testpilot/addon
> shx rm -rf web-ext-artifacts && cross-env web-ext build --overwrite-dest && shx mv web-ext-artifacts/test_pilot-*.zip ./addon.xpi

Applying config file: ./package.json
Building web extension from /Users/dcoates/code/testpilot/addon
Your web extension is ready: /Users/dcoates/code/testpilot/addon/web-ext-artifacts/test_pilot-3.0.0devdba99510.zip
```

@fzzzy im curious why chrome matters?

> I think finding a hashing function that can generate < 32767 is a great idea!

wouldn't taking the upper (or lower) 15bits of the git hash be just as effective? ala:
```
childProcess.execSync('git rev-parse --short HEAD').readUInt16BE(0) & 0x7FFF
```

**Comment by fzzzy** [comment]
@dannycoates Chrome doesn't matter to us, but that's why web-ext enforces the format it does.
