### ISSUE TITLE
Move Experiment Controls to Sidebar

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#3503]
In order to simplify the layout of experiment detail pages and accommodate a wider variety of buttons, we should move the experiment controls to the sidebar per the below spec:

https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Mobile_experiment_integration/#artboard8

https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Mobile_experiment_integration/#artboard5

Please note the experiment platform details will now sit where the experiment controls used to be

**Comment by SoftVision-PaulOiegas** [comment]
@johngruen Since designs are based on Send which is the only experiment that is different from the default add-on ones, I have a few questions in mind for the add-on type experiments that will be launched next:
1. Will the "Enable/Disable experiment" button also be moved on the left for the Firefox add-on experiments?
2. Since we are loosing the top promo part on the details page, the "Install Test Pilot + Enable experiment" button will be on the same sidebar?
3. I don't see a "Launch Tour" button. Will this be removed or added on the stack with the "Changelog", "Contribute" etc?
4. Right now we have a overflow banner that keeps the buttons like "Your Privacy", "Feedback", "Enable/Disable experiment" and enable/error notification bar displayed when user scrolls down. How we'll adapt all these if the buttons are moving on the left side?
5. If we remove the top promo part of the page, and TxP add-on is not installed, how we'll separate the TxP Privacy and terms from the experiment Privacy?

These are the first questions that came into my mind, I'll add more if I see other things unclear.

**Comment by johngruen** [comment]
> 1. Will the "Enable/Disable experiment" button also be moved on the left for the Firefox add-on experiments?

Yes

> 2. Since we are loosing the top promo part on the details page, the "Install Test Pilot + Enable experiment" button will be on the same sidebar?

Yes, see #3504 

> 3. I don't see a "Launch Tour" button. Will this be removed or added on the stack with the "Changelog", "Contribute" etc?

That looks like it was left out of the spec...note for @dannycoates or @meandavejustice or whoever implements, don't worry about other sidebar sections right now.

> 4. Right now we have a overflow banner that keeps the buttons like "Your Privacy", "Feedback", "Enable/Disable experiment" and enable/error notification bar displayed when user scrolls down. How we'll adapt all these if the buttons are moving on the left side?

No, we can rip that sticky scrollbar out too

> 5. If we remove the top promo part of the page, and TxP add-on is not installed, how we'll separate the TxP Privacy and terms from the experiment Privacy?

See #3504

**Comment by SoftVision-PaulOiegas** [comment]
@johngruen Thanks for clarifications, haven't properly understood the #3504 description when I first read it. Makes more sense now.
