### ISSUE TITLE
[release] 2018-04-26 on stage

### ISSUE THREAD

**Issue by dannycoates** [mozilla/testpilot#3522]

**Comment by SoftVision-CosminMuntean** [comment]
Hi guys,

We have finalized running our Full Functional test suite on the Staging server and here are the testing results:

### **Legend** ###
&#x1F4D5; - major issue
&#x1F4D9; - normal issue
&#x1F4D2; - minor issue

## New Issues ##
1. #3523 - &#x1F4D9; Barberpole animation along with "Installing" text are no longer displayed for Test Pilot installation 

## Known Issues ##
1. #3390 - &#x1F4D9; [Newsletter] Old Firefox logo is displayed on the Newsletter confirmation email 
2. #1935 - &#x1F4D9; Footer is wrongly displayed in [en] on non localized pages, while it's correctly localized on the ones that are

## Based on testing results we would suggest the next course of actions: ##
We don't consider issue #3523 as blocker, but we suggest fixing it if possible before releasing to production since it's a regression.
