### ISSUE TITLE
Fix for Stage/Prod Issue

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#3580]
here's what we should do:

1. Land a patch on production that looks for the stage add-on and uninstalls it silently
2. Redirect all stage traffic with param `utm_source=testpilot-addon` to production

This is a simple solution for end users.  There is no UI involved, and clicking install on an experiment without Test Pilot installed will install it automatically anyway.

@SoftVision-PaulOiegas @SoftVision-CiprianMuresan for staging testing for the time being this will mean that you should access stage through the url bar and not by clicking on the add-on

**Comment by SoftVision-CosminMuntean** [comment]
@meandavejustice, @fzzzy, @clouserw, @johngruen I have verified this fix and the staging addon is correctly uninstalled. 
In order to verify the issue I have used the following steps:

1. Download the Test Pilot add-on from: https://testpilot.firefox.com/files/@testpilot-addon/latest
2. Extract the "@testpilot-addon.xpi" file that is placed in the Firefox profile folder.
3. Open "manifest.json" file and change the "id" to "@testpilot-addon-stage".
4. Open "package.json" file and change the "id" to "@testpilot-addon-stage".
5. Create a new Firefox Profile and from "about:debugging" page load the "manifest.json" file.
6. Open browser console then in a new tab navigate to "https://testpilot.dev.mozaws.net/experiments" page.
7. Observe the behavior.

[Actual Results]:
- The "checkForStagingAndUninstalled called" message is displayed in browser console and the Test Pilot add-on is successfully uninstalled.
- Here is a screen recording with the described STR: https://goo.gl/hkzVYg

Just to be sure, all the affected users that have the stage add-on installed, the add-on will be completely uninstalled and the users have to install it again manually?
Also, I have observed that the "checkForStagingAndUninstalled called" message is displayed every time when the Test Pilot dev page is reloaded even after the stage add-on was uninstalled. Is this the intended behavior?

I am not sure if this is the right way to verify this issue, please let me know if I'm doing something wrong.

**Comment by ghost** [comment]
> Just to be sure, all the affected users that have the stage add-on installed, the add-on will be completely uninstalled and the users have to install it again manually?

Yes

> Also, I have observed that the "checkForStagingAndUninstalled called" message is displayed every time when the Test Pilot dev page is reloaded even after the stage add-on was uninstalled. Is this the intended behavior?

That's the behavior in the code, but it is noisy.  I filed https://github.com/mozilla/testpilot/issues/3589
