### ISSUE TITLE
[Mobile] Experiment launch / expiration date no longer displayed on mobile view

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3696]
**[Notes]:**
- @sevaan Neither me or John are sure if this was as designed or we forgot to add it in the new mobile design. Can you please clarify this?

**[Affected versions]:**
- Firefox 61.0 and above

**[Affected Platforms]:**
- Android 7.0 - 8.0
- iOS 11.0.1

**[Prerequisites]:**
- [Android] The "extensions.webapi.testing = true" Boolean pref was added on a new profile.

**[Steps to reproduce]:**
1. Open Firefox mobile browser and navigate to `https://testpilot.dev.mozaws.net page.
2. Scroll down to the available experiments and tap one of the cards.
3. Search for the experiment launch date on the page.
4. Return to the homepage and tap the "View Past Experiments" button under last card.
5. Tap one one of the graduated experiments.
6. Search for the experiment expiration date on the page.
 
**[Expected result]:**
- The experiment launch / expiration date is displayed on the top part of the page under the experiment logo / name.

**[Actual result]:**
- There is no experiment launch / expiration date displayed on mobile view.

**[Additional Notes]:**
- Here is a screenshot of the issue:

![1530720236023](https://user-images.githubusercontent.com/17258026/42287283-6779e5c0-7fbe-11e8-96ec-d8dee0a178d7.JPEG)

**Comment by sevaan** [comment]
The start/end date for experiments is part of the same level of hierarchy as the side navigation elements visible on desktop browsers:

<img width="382" alt="image" src="https://user-images.githubusercontent.com/473531/43292052-cd9d2f02-9101-11e8-86a0-5bdbb1c069ab.png">

Since those are not displayed on mobile the start date is not displayed either.

@johngruen Is the start/end date of an experiment something you feel is important enough to surface on a mobile device? I'd argue it's less valuable than some of the other items in the sidebar. Maybe we should consider putting them in a mobile view too. I wasn't part of the original discussions where they disappeared, so maybe there is a reason they were removed.

If we were to put them back in, let's slow them above Your Privacy at the bottom of the page in the mobile view:

<img width="444" alt="image" src="https://user-images.githubusercontent.com/473531/43292157-2c74a690-9102-11e8-96e7-4489e56ab961.png">

**Comment by KhushilMistry** [comment]
Hey, I want to work on this issue. Can I ? I will make a PR in a day.

**Comment by fzzzy** [comment]
@KhushilMistry please do.

**Comment by SoftVision-PaulOiegas** [comment]
Looks good on both Desktop (Windows and MacOS) and on Mobile (Android and iOS). Thnaks for the fix @KhushilMistry! 👍
