### ISSUE TITLE
Featured experiment button is wonky ATM

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#3713]

**Comment by lmorchard** [comment]
What's wonky about it? Not sure what to look for when checking out #3714

**Comment by SoftVision-PaulOiegas** [comment]
Finally got what "wonky" was about. You are killing us John with these titles and no descriptions. 🤣 

I asked John yesterday about what color should the "Get the App" featured experiment button be, since dev was green and stage was blue. The #3714 PR was fixing the button color also to green.
Had to modify the file locally to find out what was wonky. 😄

Anyway, seems ok now. 👍
