### ISSUE TITLE
Use local copy of pontoon.js

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#373]
PR #372 included a line in index.html that sources pontoon.js from mozilla.org, while all other third-party scripts are served by Django.

Correct this by either moving pontoon.js into the correct static directory, or just removing that line from index.html altogether. It's not needed until pontoon integration happens.

**Comment by lmorchard** [comment]
Actually started working on Pontoon integration today, insofar as I started pinging folks in #pontoon on IRC. Kind of a catch-22, since I think we need to have that line there first in advance of getting the project added to the Pontoon service. 

Also, a little leery of rolling pontoon.js into our app bundle, because then we won't be tracking changes as they deploy updates to the service. Not sure how often that thing changes, and it's not released as a separate library. It's less an third-party app dependency, more a service integration.

**Comment by meandavejustice** [comment]
closing for same reason stated in #376
