### ISSUE TITLE
Disabling testpilot so I could investigate some Nightly behaviour wiped my containers

### ISSUE THREAD

**Issue by Pomax** [mozilla/testpilot#3743]
I'm subscribed to the "containers" test pilot extension, and I had to disable test pilot to track down a weird input bug in Nightly. When I reenabled test pilot, all my custom containers were gone, and the only containers I get to pick from are the default set.

I'm sure that's at most "unexpected" to you, but to me personally: in this moment, that's infuriating. I needed to do some banking. Where the <censored> did my banking container go, with all my saved logins, active sessions, and cache for my banks and credit card services?

Not cool.

**Comment by fzzzy** [comment]
Sorry about that. The Containers Test Pilot experiment graduated 10 months ago, and the containers functionality has been present in firefox without the test pilot addon since then. You should be aware when you are using test pilot that the experiments run anywhere from 3 months to a year, and are experiments so they may be buggy. If you don't want to risk losing data, you can just wait until the experiment has graduated before using it.

**Comment by Pomax** [comment]
That part makes sense, but then why did it not turn itself off once this got put into FF proper? "This experiment has graduated and has landed in Firefox. We have migrated your testpilot container data to your regular Firefox profile so you don't lose any of the containers you've set up using the test pilot version, and turned off the experiment for you. Enjoy containers in Firefox!" would have been the decent thing to do here.
