### ISSUE TITLE
Sync for Firefox Notes is not working

### ISSUE THREAD

**Issue by AngusEdward** [mozilla/testpilot#3787]
Bottom of notes window indicates that I need to log in to sync (although I already am), and when I log in it says it is connecting, then shows an error icon at the bottom of the notes window and essentially loops back saying that I need to log in.  I have updated to the latest version of Firefox on the Mac (61.0.2 (64-bit)) and relaunched Firefox, to no avail.

**Comment by Softvision-MariusComan** [comment]
Hi @AngusEdward, thanks for reporting this issue, however considering that this is a "Firefox Notes" issue, I've moved this to its appropriate repo (issue [1348](https://github.com/mozilla/notes/issues/1348)).
Also in that issue, you will find some questions for you in order to help us try to reproduce this.
