### ISSUE TITLE
Most of the website icons and logos are no longer displayed on Dev server

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3798]
**[Affected versions]:**
- Firefox 61.0.2 and above

**[Affected Platforms]:**
- All Windows
- All MacOS
- All Linux

**[Prerequisites]:**
- Boolean `extensions.webapi.testing` new pref was added as `true` on a new Firefox profile.

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.dev.mozaws.net page.
2. Observe how the Homepage UI elements are rendered.

**[Expected result]:**
- All the UI elements are correctly displayed with no rendering issue.

**[Actual result]:**
- Most of the website icons and logos are not longer displayed.

**[Notes]:**
- It seems that we are hitting 403 error code for most of them

![get errors](https://user-images.githubusercontent.com/17258026/44213926-981cbb00-a177-11e8-8f3d-6bac0e780070.png)

- Here is a screenshot of the issue:

![screenshot_2018-08-16 firefox test pilot](https://user-images.githubusercontent.com/17258026/44213644-d36aba00-a176-11e8-9f5d-2de562d6520a.png)

**Comment by lmorchard** [comment]
Been banging on this most of today. Weird thing is I haven't been able to reproduce the issue on my local machine - neither under Windows PowerShell nor under the Windows Subystem for Linux. I also haven't been able to reproduce it on an Ubuntu VM in AWS EC2.

Other folks say they can reproduce this on their local machines, so I'm a bit baffled.

The only place I *can* reproduce is on CircleCI. And, clearing all the dependency caches there had no effect. Still poking at a build with ssh enabled, but have not yet figured out what's up.

What would be super helpful is if someone who *can* reproduce this can maybe check out an earlier commit of the site - say, maybe the last one we deployed to prod - and see if this issue happens there. If not, then maybe we can do a `git bisect` to narrow down which commit started showing this issue?

**Comment by lmorchard** [comment]
I did just realize something interesting from my working build vs the non-working on CircleCI.

My machine has this path to one of the images:

![capture](https://user-images.githubusercontent.com/21687/44234055-98b35280-a173-11e8-895e-15e4493c936a.PNG)

Meanwhile, dev has this path to that same image:

![capture](https://user-images.githubusercontent.com/21687/44234084-acf74f80-a173-11e8-8249-abc5e91a1e18.PNG)

It appears that dev is missing the `/static/app/images/` part of the path. When I look in the `dist/static/app/images` directory on CircleCI, that image does exist and with the correct hash in the name. So, it seems like it's not a matter of bad hashing - somehow the directory path to the image is being left out. And this only seems to be happening for images included via webpack in React components - not any of them included with experiment content.

Having said all that, I don't know what might cause this yet

**Comment by devinreams** [comment]
I may be mistaken but think this has to do with the `package-lock.json` disappearing at #3797 and so not everything is quite getting installed and in place by webpack (and therefore Circle CI)?

Steps I took to reproduce "missing" images locally: ❌ 

```
git clone https://github.com/mozilla/testpilot.git
npm install
npm run start
```

Steps to take to "get the images back" locally: ✅ 

```
rm package-lock.json
git revert f7fec6e2f6dd7eca7c936577efff0375c16420d0
npm install
npm run start
```

**Comment by SoftVision-PaulOiegas** [comment]
![tenor](https://user-images.githubusercontent.com/17258026/44268344-e1354380-a239-11e8-8396-3313857e488a.gif)

Works like a charm! Merge it 👍

**Comment by devinreams** [comment]
[Static deploy](https://circleci.com/gh/mozilla/testpilot/13551?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) to https://testpilot.dev.mozaws.net/ is complete and assets appear to be loading for me.

I think this issue is safe to close if someone else confirms things are back to normal. 😅

**Comment by SoftVision-PaulOiegas** [comment]
![200w](https://user-images.githubusercontent.com/17258026/44270731-ffeb0880-a240-11e8-897b-1874296b349c.gif)

**Comment by lmorchard** [comment]
That restoring `package-lock.json` appears to have fixed this leaves me really confused. Also, have we updated any dependencies in `package.json` since f7fec6e2f6dd7eca7c936577efff0375c16420d0? (Edit: No changes to `package.json` since almost 2 months ago, so that's not it.)

The `package-lock.json` file should ultimately be derived from installations based on `package.json`. Doing an `npm install` without a `package-lock.json` *does* install everything - just not the precise locked versions we had in `package-lock.json`. So, if we're now using an old restored version of `package-lock.json` - this issue may return the next time we update it along with a change to `package.json`

Might need to do a little more investigation, since I suspect there might be a newer version of something in our dependencies breaking something that the older version of `package-lock.json` could mask
