### ISSUE TITLE
No href for "our documentation" link on the "unapproved hostname" warning dialog

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#3845]
Setting up a new box and noticed that the documentation link on the config barrier is empty

![capture](https://user-images.githubusercontent.com/21687/45044117-2a103900-b03d-11e8-9ddd-7beb10f2cc51.PNG)

**Comment by fzzzy** [comment]
I think this might be related to the fluent upgrade.

**Comment by clouserw** [comment]
@stasm is this related to the fluent upgrade?

**Comment by stasm** [comment]
I'm back from vacation and I'll look into this tomorrow at the latest.

**Comment by stasm** [comment]
It's somewhat related to the Fluent upgrade :) Before the upgrade the `href` was present in the source JSX. The source is used by Fluent as a fallback if localization is not available. Everything looked OK for en-US users, but the reality was that this page wasn't localized at all. The Fluent upgrade only made this visible.

I opened #3872 to fix the root cause. I've tested it and the warning page is now properly localized.
