### ISSUE TITLE
[release] 2018-10-08 on stage

### ISSUE THREAD

**Issue by devinreams** [mozilla/testpilot#3946]
We have deployed the latest code to stage (no tag yet) and plan to launch Monday morning (7 AM Pacific US time) assuming no blockers found.

**Comment by SoftVision-CosminMuntean** [comment]
Hi guys,

We have finalized running our [Full Functional test suite](https://testrail.stage.mozaws.net/index.php?/runs/view/13533&group_by=cases:section_id&group_order=asc&group_id=94) on the Staging server and here are the testing results:

### **Legend** ###
&#x26D4;   - blocker issue
&#x1F4D5; - major issue
&#x1F4D9; - normal issue
&#x1F4D2; - minor issue
&#x1F4D7; - enhancement

### **New Issues:**
#3949 - &#x26D4; The "terms", "privacy" and "this experiment's privacy policy" strings are not linked to their respective pages for the "Email Tabs" experiment
#3948 - &#x1F4D5; Price Wise is wrongly installed on unsupported Firefox version - major
#3947 - &#x1F4D9; The "Firefox experiment" tag is misplaced if the"unsupported browser version" warning is displayed - normal

### **Known Issues:**
#3742 -  &#x1F4D5; Only the website dark blue background is displayed for any experiment bookmarked page shown in Highlights section
#3719 - &#x1F4D9; Experiments images are not displayed on Facebook and Twitter posts

### **Based on testing results we would suggest the next course of actions:**
We strongly recommend fixing the new issues found (#3949, #3948, #3947) before deploying to production since all three issues are related with the new experiments that will be launched on this release.
We don't consider issues #3948  and #3947 blockers, but considering the fact that Firefox 63 version has been released recently, we may still have multiple users who have not updated their browser and they will encounter both issues.

**Comment by devinreams** [comment]
Thank you for the speedy review! We have closed all the new issues in preparation for launch on Monday. 😀
