### ISSUE TITLE
Rename Price Wise to Price Tracker

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#4045]
We need to rename Price Wise to Price Tracker: https://github.com/mozilla/price-tracker/pull/308

**Comment by pdehaan** [comment]
Price Tracker is now live on AMO at https://addons.mozilla.org/firefox/addon/price-tracker/

Not sure the best way to fix this, as it could potentially invalidate a lot of localized strings:

https://github.com/mozilla/testpilot/blob/e705308cdd09dbd211a12ecf55542f3c95cf34c4/locales/en-US/app.ftl#L285

https://github.com/mozilla/testpilot/blob/e705308cdd09dbd211a12ecf55542f3c95cf34c4/locales/en-US/app.ftl#L299-L306

Not sure if it'd be "good enough"(tm) to change just the `-exp-price-wise` string _value_ in each of the locales:

```ini
-exp-price-wise = Price Tracker
```

Versus having to add keys for `-exp-price-tracker` and then update `eolMessageFour` to reference newer `-exp-price-tracker` key instead of older `-exp-price-wise`:

```html
-exp-price-tracker = Price Tracker

eolMessageFour = 
    ...
    <a data-l10n-name="priceTrackerLink" title={-exp-price-tracker}>{-exp-price-tracker}</a>, and
    ...
```

/cc @flodolo @lmorchard @meandavejustice @chuckharmston @clouserw

**Comment by flodolo** [comment]
Updating the term's value in all FTL files sounds like a reasonable approach to me.

Still open question: how long is that page going to remain online?

**Comment by lmorchard** [comment]
> Still open question: how long is that page going to remain online?

Basically, indefinitely. There are no current plans to take the page down. It's on a static AWS S3 bucket, so it'll ultimately be up to IT / ops to take it down some day. We *are* planning to take down infrastructure surrounding Test Pilot in June, probably including deployment infra - so this page will get harder to update at that point.

**Comment by lmorchard** [comment]
This should be changed in production now
