### ISSUE TITLE
FxA sign in redirects to ideatown.dev on current local build

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#408]
I'm on b35b72c921fca...

I've changed my /etc/hosts file for test pilot, but FxA still redirects to ideatown.dev

**Comment by lmorchard** [comment]
Hmm, yeah, the redirect URL is part of the FxA registration and not a setting on our side. So, we need to register new FxA credentials for local dev and [update the env vars in docker-compose](https://github.com/mozilla/idea-town/blob/master/docker-compose-base.yml#L34-L35). I'd just keep using ideatown.dev rather than testpilot.dev until this issue gets resolved.
