### ISSUE TITLE
Create a public details page for tests

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#419]
This bug is about allowing users who have not signed in or installed the add-on to view experiment detail pages (e.g. https://testpilot.firefox.com/experiments/activity-stream).

/edit removing the original opening, as it was incorrect.

**Comment by ghost** [comment]
The body of this bug seems different than the title.  I think this bug is about being able to send https://testpilot.firefox.com/experiments/activity-stream to my friend who has never used Test Pilot and them seeing something about how great activity stream is instead of being redirected to the home page.  

More precisely, removing the redirect to the home page and altering detail pages for users who aren't logged in to showcase an experiment and encourage signing up.

I'll remove the discussion label and add needs ux, since I think that's what we're talking about here, but let me know if I'm wrong.

**Comment by johngruen** [comment]
@wresuolc yeah i think @ckprice may have pasted in the worng copy here...I am getting rolling on the UX here though

**Comment by pdehaan** [comment]
**NOTE:** Once we tweak this UX flow, we need to make sure we verify the [newly created] [FAQ](https://github.com/mozilla/testpilot/blob/master/docs/FAQs.md) is still accurate.

**Comment by rtanglao** [comment]
from: https://twitter.com/derspiny/status/736039687647809536
"I’d love it if testpilot did something sensible, like show screens, for non-Firefox users."

**Comment by lmorchard** [comment]
FWIW, I reopened #761 and stuck it into TXP-9. Adding social sharing metadata can (& probably should) be untangled from this public pages issue.

<strike>Something hacky / simple we could do here so we have proper social sharing metadata (#761) along with public pages via Ampersand: 
- Check for experiment URL patterns in [the catch-all frontend view](https://github.com/mozilla/testpilot/blob/master/testpilot/frontend/views.py)
- Fetch the Experiment model & pass it to the template.
- Render the appropriate per-experiment meta-tags in `<head>` in [the frontend template](https://github.com/mozilla/testpilot/blob/master/testpilot/frontend/templates/testpilot/frontend/index.html#L3) instead of the site-generic info

That way, we don't necessarily need to render complete pages for experiments on the server-side, or add all the server-side URL routes to accommodate them. (I think @chuckharmston mentioned this in the flat files meeting, but it can work here too.)</strike>

**Comment by johngruen** [comment]
@6a68 @lmorchard this is now spec'ed ux-wise. 

The sharable add-on pages can be seen by following the "test Pilot Funnel" link, then the "Secondary Funnel" link here: https://mozilla.invisionapp.com/share/Q77S1H6ZC

**Comment by jaredhirsch** [comment]
@johngruen Great, thanks. Followup UX question / suggestion:

On the details page, what if put a big green install button in the _left_ column, just below the participant count and just above the description paragraph? If you have test pilot, it can say "install experiment". Otherwise it could say "install test pilot" or "install firefox". This ensures that the button is always in the same place, regardless of what you've installed, and it's always easy to find (clear single CTA on left side of page). Would also make the engineering simpler.

**Comment by jaredhirsch** [comment]
Resizing to medium, now that #761 splits out the social sharing bit. @lmorchard If I'm wrong, feel free to ratchet it back up.
