### ISSUE TITLE
Evaluate flow for e10s release plan

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#437]
Current e10s plan of record:
- BETA 46: 50% of `46population`
- GA 46: 100% of `46population`

`46population` users who have no add-ons or a11y tools installed, or non RTL locales.

Per an update from relman and co:

> When rolling out to release channel:
> Users who have ZERO addons: e10s ON
> Users who have ONE or more addons, a11y tools installed, or RTL locales: e10s OFF
> **Users who move from ZERO addons to ONE or more addons** will trigger e10s to go from ON to OFF, in which a restart will be requested.  We should evaluate the UX and flow for this use case.

Every one of our users who install Test Pilot and previously did not have an addon installed, is subjected to the above condition. We should discuss.

/cc @edmoz @johngruen

**Comment by edwindotcom** [comment]
it would be good to get a feel for numbers affected. I'd guess that most test pilot users will have one or more addons. So ball park: 10% test pilot users would have to restart upon install?  Installing test pilot experiments would require no install (since test pilot was the first addon).  

We should confirm that other system addons like Hello and Pocket are not counted as that would make the `46population` really small.

**Comment by ghost** [comment]
What is the expected outcome of this issue?
