### ISSUE TITLE
Switch from Node 0.12 to Node 4.x?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#442]
Re: [#436 (comment)](https://github.com/mozilla/testpilot/pull/436/files#r54643575) thread about Node 0.12 usage (in Dockerfile and Travis-CI),

Not sure if it's worth it to just switch to Node 4.x now since it has a much friendlier LTS+maintenance window (see the handy table and chart at the bottom of https://github.com/nodejs/LTS#lts_schedule), and I'm sure it will be a lot easier to bump minor Node 4.x versions in the future versus trying to jump from Node 0.12 to Node 4 while trying to solve future SSL exploits.
1. [/.travis.yml:13](https://github.com/mozilla/testpilot/blob/1425cf9b5b68a7f06b69c0cb8708d0c86635bc6a/.travis.yml#L13) &mdash; `nvm install 0.12`
2. [/Dockerfile-frontend-build:1](https://github.com/mozilla/testpilot/blob/1425cf9b5b68a7f06b69c0cb8708d0c86635bc6a/Dockerfile-frontend-build#L1) &mdash; `FROM node:0.12.7`

(Plus I can't find Node 0.12 listed on the [nodejs homepage](https://nodejs.org/en/))

**Comment by lmorchard** [comment]
Also CircleCI, since we're probably going to be dropping Travis in favor of that.

This is worth doing because this version of node is basically ancient, but not super high-priority IMO. We don't serve anything using node, we just build frontend assets and (soon) the addon in local dev & on CircleCI. So, we don't have any services up & running with an outdated node.

**Comment by lmorchard** [comment]
Also relevant:
![node 4.4.0 LTS](https://www.dropbox.com/s/jgcjqoj8avehyje/Screenshot%202016-03-09%2015.33.48.png?dl=1)
