### ISSUE TITLE
Find a thumbnail / resize app in Django for uploaded images

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#46]
There are a few options like [sorl-thumbnail](https://github.com/mariocesar/sorl-thumbnail). Look into it, pick one, try using it.

**Comment by meandavejustice** [comment]
- [discussion of thumbnail projects](https://code.djangoproject.com/wiki/ThumbNails)
- [package comparison](https://www.djangopackages.com/grids/g/thumbnails/)

**Comment by pdehaan** [comment]
I "assume" this also applies to profile images. (If not, let me know and I can file a separate bug instead of hijacking this one).

<img width="1440" alt="fullscreen_12_9_15__2_51_pm" src="https://cloud.githubusercontent.com/assets/557895/11696939/061a26c2-9e85-11e5-9b98-6b19b64d7c66.png">

I notice that jgruen and I both had images served from gravatar, whereas Les had a non-resized headshot from a CDN that was 100-130KB (compared to 3-4KB for the images served from gravatar).

**Comment by lmorchard** [comment]
> I "assume" this also applies to profile images.

This issue should apply to any uploaded images, including profile images. There's absolutely no processing right now at all, not thumbnails, etc. So, all images are full size and scaled in the browser. The only exception are gravatars, which is the fallback used when an uploaded image is missing (right now the majority case). 

That avatar image of mine you called out, I uploaded just to test S3 and the avatar image upload code that doesn't actually have a user interface beyond the admin pages in Django. (i.e. we have no user profile management page for general users)

**Comment by chuckharmston** [comment]
We should use the [`<picture>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture) for this.

**Comment by meandavejustice** [comment]
no safari support :( https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture#Browser_compatibility

**Comment by meandavejustice** [comment]
_bump_ do we still need this issue? @lmorchard

**Comment by lmorchard** [comment]
Yes, at some point we really should have one

**Comment by ghost** [comment]
I'm marking this as a good-first-bug because this should be doable by just integrating a 3rd party plug-in.  To solve this:

1) Choose a django resizer plugin
2) Write a patch to integrate it (including tests)

If you're interested in working on this, please let us know what plugin you're looking at before you write a patch to integrate it.  Thanks!
