### ISSUE TITLE
Enable locale-specific experiments

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#468]
_Bug migrated from universal search repo, was originally https://github.com/mozilla/universal-search/issues/76_

Description, from @nchapman in the original bug:

> Due to various contractual requirements, we should make sure we can limit recommendations to specific markets rather than only specific languages. There are previous examples of doing this for other search experiments so we should look into how those were done.

The goal here seems to be allowing restricting experiment participation to specific countries. The earlier search experiments mentioned must have used country-specific locales (for example, `en-US` vs `en-GB`), as that's the only thing available to telemetry experiments.

I hesitate to suggest using something stronger, like IP geolocation, because that seems like a questionable bit of data to store for a given user, and because tools like TOR make that easy enough to spoof (netflix IP spoofing is pretty common).

**Comment by lmorchard** [comment]
Two things: 

1) Locale restriction in particular seems like something experiments should enforce for themselves. That should be data that's accessible from Firefox to an experiment add-on.

2) But, if we want central control of things like that, we need to record a user's locale in their profile and possibly tell experiment add-ons whether or not to activate by way of something similar to feature flags (see also #364)

**Comment by pdehaan** [comment]
Why would you record a users locale in their profile versus just grabbing it from the browser/user each time? I usually switch browsers regularly and one of my profiles happens to be in a German locale, so if you somehow store my locale in your DB, not sure how I'd change it if I wanted to change from German back to English or French, etc.

**Comment by lmorchard** [comment]
> Why would you record a users locale in their profile versus just grabbing it from the browser/user each time?

See #478.

As of right now, feature flipping logic happens on the server, so the server needs all the data. If the client does it, it needs the conditions and their implementations.

For example, we might want to apply a feature condition like: For all German users on Windows, put half in feature bucket A and half in feature bucket B. If the server resolves that condition, it needs the data (because it has the conditions). If the client resolves that condition, it needs the condition (because it has the data).

For the sake of access control, a feature bucket could also be a signal to the experiment not to activate at all. (So, for all RTL language users, do not activate this experiment)

As for changing locale, maybe we can clear the user's feature flags and re-calculate from conditions when that happens. That, or we only calculate the first time and assume locale is normally a stable thing.

As for grabbing each time... each what time? :) Browser startup? Page load? API response? We probably don't want to vary feature flags that often. Currently, it only happens if the experiment installation doesn't have flags set yet.

**Comment by lmorchard** [comment]
You know what, actually, ignore half of what I just wrote up there. [Maybe we should just send client-side data needed by server-side conditionals as parameters in the request to fetch feature flags](https://github.com/mozilla/testpilot/issues/478#issuecomment-196508370). No need to store them, use them in server-side calculations as needed.

**Comment by mconnormoz** [comment]
To echo what I wrote in #478 I think what you want to do is use %REGION% in the URL, run that through nsURLFormatter, and be done with it.  The browser already has a concept of region, let's not diverge this for Test Pilot.  Especially for search experiments.

FWIW, we do this server-side in absearch, it seems to scale pretty well because it's just another value to filter on (like release, language, channel, etc).  No need for persistent storage (except for cohort capping when we're running tests), no lookups, so request latency is minimal, and you can basically do it all in memory.

**Comment by ghost** [comment]
We'll address access control in #364 (which is currently waiting for input from Product)
