### ISSUE TITLE
Provide variant testing framework to experiments.

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#477]
Issue #366 introduced data models and server-side APIs for feature flipping flags & conditions. This needs to be passed along to experiments, so let's do that.

Probably the easiest way is to do this via messaging using nsIObserver. But, investigating that should be a part of this issue.

**Comment by lmorchard** [comment]
Getting add-ons to cooperate close to startup time is proving a bit of a challenge. Going to swap this one to 4/8 and see if I can't get #479 done instead

**Comment by lmorchard** [comment]
Just as a note about where I left off with this: As of #422, feature flags should be appearing in the data from `/api/me`, found in the `features` property in each entry of the `installed` set. (Though, FWIW, there's an issue with the format of this data - #742 - it should probably be an object indexed by add-on ID instead of an array.)

Anyway, the goal of this issue is to get that `features` data from `/api/me` into the main Test PIlot add-on. Then, relay it to individual experiments. I was trying to set up nsIObserver messaging to make that happen, but ran into a chicken-and-egg problem: 

Add-ons load in random order. Sometimes experiments come in before the main add-on, sometimes after. So, that means, if an experiment wants to ask the main add-on for those feature flags at start up - sometimes the main add-on isn't available yet. If the main add-on wants to push the data to experiments, sometimes _they're_ not available yet.

So, this issue probably needs a clever way to handle that and ensure all experiments and the main add-on are initialized and loaded before messages go around. Maybe experiments can check whether the main add-on is there, somehow, before pinging? Also need to be careful not to break existing experiments, e.g. by requiring some kind of messaging on startup

**Comment by chuckharmston** [comment]
Current proposal: https://gist.github.com/chuckharmston/b8b728844c44fa931ace881e92286b4d

**Comment by ianb** [comment]
Some feedback on the [proposal](https://gist.github.com/chuckharmston/b8b728844c44fa931ace881e92286b4d):
- In many cases we want a statistically significant number of people to get B, rather than an A/B ratio.  I think SHIELD tries to be clever about this, there might be something to take from that.
- The proposal seems to have the add-on giving information to Test Pilot, including weights.  This means that changing weights would require an add-on update.  Remote control of this would seem better.  But then that means people might move between buckets if you twiddle the knobs... which should be accounted for anyway, I suppose, as part of starting and stopping experiments.
- Maybe overdesign, but I can imagine a situation where you launch movieCards, but then change the experiment and launch movieCards2; in stats you want to segment these two (because you think movieCards2 engages better), but you want everyone with movieCards to get movieCards2.
- Some people might be vetoed from a cohort, e.g., because a feature isn't localized.  If this isn't built into the system then some people might be identified to metrics as being in a cohort when the feature remains suppressed for them.

**Comment by ianb** [comment]
Also, could this communication channel be done with prefs?  (Though I'm not sure how easy it is to access arbitrary prefs from a Web Extension.)  Prefs are also tweakable for testing.

**Comment by chuckharmston** [comment]
This landed last week and the issue didn't get closed; thanks everyone!
