### ISSUE TITLE
Add an "introduction" content area before ExperimentDetails list

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#504]
It would be nice to have a field in the admin which we can use to add arbitrary information to the experiment details view.

@johngruen to confirm where this information would live.

/edit adding steps from Les to the bug opening
- [ ]  Add an introduction MarkupField to the Experiment model.
- [ ]  Expose the field in the REST API.
- [ ]  Display the field in the frontend view.

**Comment by lmorchard** [comment]
Can you explain a little more about what arbitrary information & where? We can add blocks of image-headline-text to each experiment in the "Experiment Details" section that makes up the bulk of the page. I'm guessing this is different than that?

**Comment by ckprice** [comment]
> Can you explain a little more about what arbitrary information & where? We can add blocks of image-headline-text to each experiment in the "Experiment Details" section that makes up the bulk of the page. I'm guessing this is different than that?

Ah. That seems like it should be enough as far as I understand the ask. I'll let @johngruen provide more details.

**Comment by clouserw** [comment]
We chatted about this in the triage meeting.  In the long term, I think having a single markdown/html field would be the best thing.  Then if you wanted a paragraph at the top, you just do it, if you want inline images, go for it.  It would give us more flexibility for layout as well as inlining videos or bulleted lists or whatever.  So, longterm, I think that's what we should do.

However, this is marked as a blocker for launch and doing the one giant textarea would mean ripping out what we have and I don't want to put us through that.  So, to launch, this is just asking for a markdown paragraph above where the screenshots start.  I think @ckprice has a screenshot.

If it's easy to do the former, let's do it, otherwise lets do the latter and file another issue for the former.  Thanks!

**Comment by lmorchard** [comment]
This should be pretty easy to do. The "Measurements" area in the sidebar is just [a MarkupField that accepts Markdown](https://github.com/mozilla/testpilot/blob/master/testpilot/experiments/models.py#L37) (and also straight up arbitrary HTML). 

So, maybe we add an "introduction" field of the same type and display it before laying out ExperimentDetail entries. And if no ExperimentDetail entries are specified, the introduction is all that shows up. 

If that ExperimentDetails scheme turns out to be not helpful, we can clean it out later.

**Comment by lmorchard** [comment]
Tweaked the issue title to reflect my last comment, hopefully that makes more sense in issue lists

**Comment by ckprice** [comment]
Thanks @lmorchard for changing the title. Aforementioned screenshot:

![intro markdown](https://s3.amazonaws.com/f.cl.ly/items/3L2A203436142y1c3u3R/Image%202016-03-24%20at%2011.48.17%20AM.png?v=dce4609b)

**Comment by lmorchard** [comment]
Yeah, that should be totally doable:
- [ ] Add an `introduction` MarkupField to the Experiment model.
- [ ] Expose the field in the REST API.
- [ ] Display the field in the frontend view.
