### ISSUE TITLE
Non logged-in homepage lacks background on Chrome

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#509]
Found in https://testpilot.firefox.com/__version__ (b2f03ce74366e7c4eae1b53c4d24a5a9c0ac083b):

``` json
{
    "commit": "b2f03ce74366e7c4eae1b53c4d24a5a9c0ac083b",
    "source": "https://github.com/mozilla/testpilot",
    "version": "2016-03-16"
}
```

---

I noticed this afternoon that we're lacking all the background color/gradients on the homepage on Google Chrome when you're not logged in. I selected the text so you can see that it is there, just "invisible".

![screenshot_3_18_16__5_11_pm](https://cloud.githubusercontent.com/assets/557895/13895116/a53caff4-ed2c-11e5-8487-6a7f41746716.png)
**Figure 1:** Google Chrome (left). Mozilla Firefox Beta (right).

**Comment by meandavejustice** [comment]
@Rhapsody-Girl It looks like @johngruen fixed this as a part of their "define behavior for non-firefox" fix. turns out it was just a missing comma [here](https://github.com/mozilla/testpilot/blob/non-firefox-ux/testpilot/frontend/static-src/styles/_theme.scss#L12)

We'll have to find you a new bug. You can just leave a comment on an issue you'd like to work on, or ping me on irc(JSON_voorhees)
