### ISSUE TITLE
Docker instance doesn't respond to 0.0.0.0:8000

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#54]
I was testing the Docker flow (worked well!) and noticed this one bit of confusion:

``` sh
bash-3.2$ docker-compose up
Pulling db (postgres:9.3)...
9.3: Pulling from library/postgres
...
server_1 | Django version 1.8.4, using settings 'idea_town.settings'
server_1 | Starting development server at http://0.0.0.0:8000/
server_1 | Quit the server with CONTROL-C.
```

I wasn't able to get the server to respond on http://0.0.0.0:8000/ or http://localhost:8000/, but it did respond on http://ideatown.dev:8000/ with the following piece of HTML wizardry:

<img width="326" alt="home___idea_town" src="https://cloud.githubusercontent.com/assets/557895/9620353/39f5ec2e-50ce-11e5-8a26-27cfd2e72402.png">

FWIW, I'm currently sporting Docker 1.8.1.

``` sh
bash-3.2$ docker images
REPOSITORY               TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
ideatownserver_server    latest              6bf9322c97fa        11 minutes ago      623.1 MB

bash-3.2$ docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by pdehaan** [comment]
Not sure if it is something with my config, or if we need to tweak this bit: [/bin/run-dev.sh:8](https://github.com/mozilla/idea-town-server/blob/50059ab99dda857c123cd9d8da84d50a63833845/bin/run-dev.sh#L8) to point to http://ideatown.dev:8000:

``` sh
while [ 1 ]; do
    ./manage.py runserver 0.0.0.0:8000
    sleep 1
done
```

**Comment by lmorchard** [comment]
The server will never respond from 0.0.0.0:8000 - that's localhost for your host computer.

The way the Docker dev arrangement works is that there's a virtual machine running. You get the VM IP with `docker-machine ip default`. [That IP is where you should point `ideatown.dev` in your local `/etc/hosts`](https://github.com/mozilla/idea-town-server#hacking-tldr) file. On my machine, that tends to be 192.168.99.100.

The Docker machine VM itself hosts one or more containers. Each container has a private IP within the VM, unreachable from the host computer. The Django server container is one of them, and within that container is where `/bin/run-dev.sh` runs.

So, it goes something like this ([Inception BWAM](http://inception.davepedu.com/noflash.php)):
`host -> docker-machine(192.168.99.100) -> idea-town-server(172.17.0.8)` 

Thus, the server log message is confusing, because 0.0.0.0 is actually localhost for the Django container.  [But, the Docker machine VM forwards a port to the Django container.](https://github.com/mozilla/idea-town-server/blob/master/docker-compose.yml#L6) And, so you are able to access it via 192.168.99.100:8000 (or whatever IP `docker-machine ip default` reports).

But, there is no port forward from host:8000 to docker-machine:8000, so 0.0.0.0:8000 doesn't respond

**Comment by jaredhirsch** [comment]
Hey @pdehaan, sorry docker caused you some stress, but technically it's behaving correctly. https://en.wikipedia.org/wiki/0.0.0.0 (er, les's explanation is way better, just go by that)

If you go by the steps in this repo's README, it should hopefully just work for you.

I'm going to close this; I'm not sure we need to do anything here.
