### ISSUE TITLE
Implement new SurveyGizmo-based experiment feedback flow

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#568]
Here's the UX https://people.mozilla.org/~jgruen/test-pilot/activity-stream.html (enable the experiment then click the feedback link)

Here's the state diagram: https://www.lucidchart.com/documents/view/bc257f5b-d2f9-4e23-8c60-fdb91b274bc6

**Comment by meandavejustice** [comment]
Do we have the process for Survey Gizmo integration documented anywhere?

**Comment by johngruen** [comment]
#430 provides some documentation

**Comment by pdehaan** [comment]
FWIW, checking the UX flow on jgruen's people.moz link ... the popup doesn't open in Firefox or Chrome (blocked by popup blockers).

**Comment by javaun** [comment]
In Matt's comments on #430, he ID's 3 scenarios. 

> These are the interaction points for individual experiments:
> 1. Unsolicited feedback from the experiment page
> 2. Prompt for feedback from users opting out of a study
> 3. Prompt for feedback from a random population of users AFTER giving the experiment a star rating

These all pertain to individual experiment feedback. There are two more scenarios:
1. Unsolicited feedback about Test Pilot in General (Test Pilot main page)
2. Prompt for feedback after retiring/totally uninstalling Test Pilot. 

no. 3 above is interesting. I'm not sure how we'd achieve this one or where we'd put it in priority order.

**Comment by meandavejustice** [comment]
Waiting on Survey Gizmo URLS

**Comment by lmorchard** [comment]
I [commented](https://github.com/mozilla/testpilot/pull/611#discussion_r60438629) on #611 about the SurveyGizmo URLs. I don't think we're going to get one-shot URLs for all experiments to unblock this - I think they'll be created per-experiment.

Sounds like at least [3 per experiment](https://github.com/mozilla/testpilot/issues/568#issuecomment-208466591) for different feedback points, so I think we need to add those as fields on the Experiment model and fill them in when experiments are introduced and their associated surveys are created.

But, I'm commenting here, too, because I'm not sure. We should probably get confirmation that this is the case.

**Comment by ckprice** [comment]
Met with Matt_G today:
1. Survey links for each experiment sent via email. These will be stored in the DB.
2. Intervals for when to show the surveys are already set up (2 days, 1 week, 3 weeks, 1.5 months). Polls everyone every 5 minutes.
3. Query parameters will be sent to SurveyGizmo to communicate touchpoint (@meandavejustice has something mocked up already).
