### ISSUE TITLE
Test Pilot could not be verified

### ISSUE THREAD

**Issue by Dapid** [mozilla/testpilot#634]
Just now, Firefox has informed that Test Pilot could not be verified and it has been disabled.

I am using Firefox 45.0.2 on Fedora Linux 64 bits.

**Comment by meandavejustice** [comment]
Hello @Dapid,

Would you mind providing a little more info? What instance of Test Pilot are you accessing? Is this the local copy? If so, how are you building the addon?

**Comment by Dapid** [comment]
Sorry for the lack of information.

I am using Test Pilot 1.2.3.1-signed from addons.mozilla.org. Is this perhaps not the right place to report it?

**Comment by johngruen** [comment]
Hey @Dapid thanks for responding. We're currently in the process rebuilding Test Pilot for Firefox. We suspended the old addons.mozilla.org download link for the time being while we prepare to relaunch, but I'm not sure why this caused the current Test Pilot add-on to become disabled. Flagging @clouserw who is is more familar with the AMO signing process than I am. Thanks!

**Comment by ghost** [comment]
I'm guessing the disabling had nothing to do with it.  Unless @Dapid noticed when it was disabled, it could have been that way for a long time.  The add-on is dormant these days.  All that said, I also couldn't reproduce the problem:

![tp](https://cloud.githubusercontent.com/assets/16946141/14825252/f7e42474-0b8d-11e6-8255-d3f0e621cd88.png)

@dapid are any other add-ons disabled?  Worst case scenario you can just remove the add-on -- we're launching a new one in a few weeks and you can install the new copy then.

**Comment by ghost** [comment]
Turns out this is some combination of https://bugzilla.mozilla.org/show_bug.cgi?id=1267318 and https://bugzilla.mozilla.org/show_bug.cgi?id=1267642 .  Basically the certs are expiring and depending on the date on your computer you'll start hitting this.

I've reenabled the add-on and bumped the version so it will get resigned.  Everything should be back to normal once the add-on goes through the review process.

Thanks for letting us know!
