### ISSUE TITLE
Doorhanger allows me to give feedback on non-installed experiments

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#649]
I don't have the activity stream add-on installed, so it seems like I shouldn't have the feedback button when I mouse over its entry in the doorhanger:

<img width="400" alt="screen shot 2016-04-27 at 10 59 18 am" src="https://cloud.githubusercontent.com/assets/96396/14862696/6a99f316-0c67-11e6-8f2a-10a8ed801e10.png">

**Comment by pdehaan** [comment]
Is... do you have an old testpilot addon?
This is what it looks like for me:

![firefox_test_pilot_and_2__ff_-c_nightly__python2_7__and_irccloud](https://cloud.githubusercontent.com/assets/557895/14862773/c54a6b56-0c67-11e6-88e3-555a153a19cb.png)

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/14862811/eb8f0d8a-0c67-11e6-9d9f-a76a3b942e9a.png)

**Comment by pdehaan** [comment]
If i install the add-on via testpilot.stage (instead of my previous one which i got from testpilot.dev.mozaws), then my config looks like this [and I can see I'm using the 2016-04-26 tag/build]:

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/14862932/6ddbe632-0c68-11e6-99d2-fbd874a8cb07.png)

**Comment by jaredhirsch** [comment]
Yup, I was on old, old prod. :blush: Closing
