### ISSUE TITLE
other endpoint cleanup

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#65]
Remove templated views other than accounts/, replace (if we need them) with django-rest-framework APIs

**Comment by jaredhirsch** [comment]
We should also make 404s work correctly: if assets are missing, just return a 404 and not the index page (django handles this). if a page doesn't exist, show a 404 page (ampersand handles this).

**Comment by lmorchard** [comment]
FWIW, in dev / debug mode, I think Django will serve up 200 OK with an HTML error message wherever things are not found - even for static resources, since we're serving those up from Django right now. If you switch off `DEBUG` in `idea_town/settings.py` or `docker-compose.yml`, you should see normal 404s.

But yeah, there is a `frontend` app catch-all route for things outside the `static` path. So, that might complicate things too.
