### ISSUE TITLE
Follow up with addon install UI (double `Let's go` buttons)

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#659]
We are _still_ having some inconsistency with showing the dialog when the addon is installed.
When this happens I'm not seeing anything in either the browser toolbox or browser console.
This means one of two things:
1. I am overlooking a race condition/hazard
2. There is a serious bug in [unsafeWindow](https://developer.mozilla.org/en-US/Add-ons/SDK/Guides/Content_Scripts/Interacting_with_page_scripts).    ([our usage](https://github.com/mozilla/testpilot/blob/9f323963554d2267de4dc0e84b84ce58a9b75e7b/addon/data/message-bridge.js))

Going ahead with @johngruen 's fix in #656 for the time being, Until I get some extra time to take a look at this.

Since users can get into site with #656 without a refresh. The priority is low.

**Comment by ckprice** [comment]
The priority is lower, yes, but it does result in some unsavory UI.
![LETS GO LETS GO](https://s3.amazonaws.com/f.cl.ly/items/1P0s3q333z0s0v320m2Q/Image%202016-04-27%20at%207.06.11%20PM.png?v=25dc9f61)
I think we should fix this before launch.

**Comment by meandavejustice** [comment]
I'm :+1: to before public launch as well

**Comment by jaredhirsch** [comment]
@meandavejustice Let me know if you want a hand investigating this

**Comment by meandavejustice** [comment]
This doesn't really seem that bad to me. And it ensures that users always get into the site. cc/ @johngruen I've been looking at this pretty much all day and still haven't figured out quite why this is occasionally happening.

**Comment by lmorchard** [comment]
If we really, really don't want both buttons, we could have the doorhanger code send a message to the site telling it to hide the in-content button. That way, if the doorhanger never appears for whatever reason, the in-content button stays visible because the message was never sent.

It's still strange that the doorhanger fails intermittently though

**Comment by pdehaan** [comment]
Random and unsolicited proposals:
1. Remove "Let's go" from the doorhanger and just always show it on the main page. That way if the doorhanger disappears (or never appears) the user always has a way forward.
2. Instead of having a page saying "Test Pilot installed! [Let's go]", just redirect me to the /experiments page automatically, because a page with one button is boring and has no benefit to me as a user. It's just an extra [mildly annoying] click. Bonus points if we can make the doorhanger persist across the pageload.

**Comment by johngruen** [comment]
@meandavejustice I'm really not opposed to @pdehaan's first proposal

**Comment by meandavejustice** [comment]
@johngruen me neither. I'll get a pull request ready.
