### ISSUE TITLE
Finalize all survey content

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#667]
Survey content for experiments is currently just filler data. Final content will come before launch.

We'll also need content for the retire survey.

**Comment by ckprice** [comment]
Assigning this to myself as a proxy for Matt_G

**Comment by ckprice** [comment]
Met with @mattgrimes and @rayborn yesterday ([2016-05-04 notes](https://public.etherpad-mozilla.org/p/test-pilot-epm))

@meandavejustice can you please confirm these. All of these are up to our discretion, but Matt's team needs to know what they are.

**Confirm URL name and values for _survey source_.**

Reference [430#issuecomment-204534763](https://github.com/mozilla/testpilot/issues/430#issuecomment-204534763)

> 1. Unsolicited feedback from the experiment page
> 2. Prompt for feedback from users opting out of a study
> 3. Prompt for feedback from a random population of users AFTER giving the experiment a star rating

Example: `&source={feedback,optout,heartbeat}`.

See Matt's original comment for more context.

These are up to our discretion, but Matt's team needs to know what they are.

**Confirm URL name and values for _duration_.**

Example: `&duration={twoDaysSent,oneWeekSent, threeWeeksSent,monthAndAHalfSent}`.

I believe some of these values are already [here](https://github.com/mozilla/testpilot/blob/66b5c96bc0ac3bb1230a1d8066406a6602fd6c4b/addon/lib/survey.js#L25), but can you confirm the names.

**Confirm URL name and values for _Heartbeat score_**

When `&source=heartbeat` (or whatever), we'll want to send the star rating.

Example: `&score={1,2,3,4,5}`.

Let me or Matt_G know if you have any questions.

**Comment by meandavejustice** [comment]
The current data being sent is as follows:
- duration is `&interval={2,7,21,46}`
- score is `&rating={1,2,3,4,5}`
- heartbeat does not currently send a source, since we have rating.
- source is `&ref={'disable', '~~giveFeedback~~givefeedback'}
- the heartbeat additionally sends `&id={addonId}` ex: `@universal-search@mozilla.com`
- both `disable` and `giveFeedback` also send `&experiment={experiment.title}` ex: `tab-center`

I'm happy to make the changes needed, though I feel we need to always send the experiment/addonId so the survey template has that context.

/edit updating case on `givefeedback`

**Comment by MattGrimes** [comment]
It would be great if we could add a source for heartbeat. That'll make the
logic easier on our end since we'll only have to look at one variable for
source. If that can't get done before launch, we'll figure something out.
Don't block on that.

Are we sending the other experiments that the user is enrolled in as well?
This will help us to understand if there are collisions within Test Pilot.
For example, we'd be able to tell if users that have both Tab Center &
Activity Stream report issues with slowness more frequently than users that
have only Activity Stream. Don't block on this either. It will be valuable
though.

**Comment by meandavejustice** [comment]
We aren't currently sending that, but can very easily. @MattGrimes Is there anything else you would like added? I can get them in this afternoon no problem. Are you okay with the current naming/data being passed above? It is a quick change to match the keys/values from @ckprice s comment above.

**Comment by MattGrimes** [comment]
We've updated all the existing surveys to conform to the values you posted above. I think we are good. Don't worry about passing a Heartbeat ref either. We've made changes to address that already and can plan on that for future experiments. If you could pass in any additional experiments that the user is enrolled in that would be really useful. I know @nchapman was curious about that as well.

**Comment by meandavejustice** [comment]
Cool @MattGrimes I will ping you on the pr.

**Comment by ckprice** [comment]
@mattgrimes had some next steps here (promote text box for surveys to the top, and remove % progress especially for one pagers). Please let us know when complete.

**Comment by ghost** [comment]
Complete:
- We've removed the progress bars from the first page of each survey (many flows are just the first page which is the issue)
- We've promoted the text box for the surveys

Open Questions:
- Did we reach agreement on sending folks to GitHub issues if they have bugs?  Is this only for "givefeedback" (I assume yes)?
- We need clarifications from Javaun on the types of answers he'd  like to see for "Why do you use multiple tabs?"
- **[EDIT] We need clarification on whether/where we should redirect the user somewhere post-survey.  SG has delayed redirects, so we could do something like: "Thanks for helping us make Firefox better!" -> 2s -> redirect to TODO**

Thanks

**Comment by pdehaan** [comment]
> [EDIT] We need clarification on whether/where we should redirect the user somewhere post-survey. SG has delayed redirects, so we could do something like: "Thanks for helping us make Firefox better!" -> 2s -> redirect to TODO

I imagine that we'd want to redirect back to testpilot homepage after the user finishes a survey (not sure how, since we'd need to know to redirect back to dev, stage, or prod).

Currently (as of like 9:30am this morning), this is what I was seeing after I did a survey:
<img width="479" alt="activity_stream" src="https://cloud.githubusercontent.com/assets/557895/15085250/f85aa9ca-138d-11e6-9fd4-7f7a1ce4aee5.png">

So it felt like a dead end, and I would need to manually type "testpilot.firefox.com" into the address bar [like some sort of animal] to get back to the  experiments/tests.

All that said, I'm just a very small cog in a much bigger machine, so this really needs feedback/approval from one/all of @nchapman @ckprice @clouserw

**Comment by ghost** [comment]
I could easily redirect to testpilot.firefox.com.  I could also redirect to dev/stage accordingly if there were url params for me to detect which one you're using.  I'll just wait for a response from the others.

**Comment by ckprice** [comment]
I'm going to close this as we have what we need for launch. Carrying pending questions over to #737.

Thanks @rayborn @MattGrimes!
