### ISSUE TITLE
Uninstalling Test Pilot doesn't uninstall active experiments

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#668]
STR:

1) Install Test Pilot
2) Install all the experiments
3) go to about:addons and uninstall Test Pilot
4) Restart if you want to, but either way, all the experiments are still installed

Using Nightly on Linux

/cc @meandavejustice

**Comment by lmorchard** [comment]
[We have code that _should_ be uninstalling experiments when the main add-on is uninstalled](https://github.com/mozilla/testpilot/blob/master/addon/index.js#L535).

But, it's consulting `store.installedAddons` to get the list to uninstall. That gets updated by [`updateExperiments()`](https://github.com/mozilla/testpilot/blob/master/addon/index.js#L306), which gets called by [`setupApp()`](https://github.com/mozilla/testpilot/blob/master/addon/index.js#L152) every time the browser starts or the add-on is switched to a different server environment.

Trying to think what would get things our of sync... If you enabled an experiment from one server, then switched to an environment without that experiment, it would disappear from the `store.installedAddons` list because we're careful not to mess with add-ons that aren't listed on the Test Pilot server. Not sure if that's what happened here...

**Comment by lmorchard** [comment]
Oh, huh. Looks like there are some errors happening somewhere in the `onUnload` hook that prevent the uninstall from running. Looking into it...

**Comment by meandavejustice** [comment]
@lmorchard Looks like we need to check existence of the pagemods before calling delete

**Comment by meandavejustice** [comment]
we calling `app.send` after deleting the page mod

**Comment by meandavejustice** [comment]
I got a fix coming

**Comment by ghost** [comment]
I never restarted the browser between installing and uninstalling, I think.  If that matters.
