### ISSUE TITLE
audit package.json and remove unused deps

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#669]
just realized we still have some unused deps in our `package.json`.

Two that I noticed were `coverify` should be in dev-deps and `request` should be removed all together.

**Comment by pdehaan** [comment]
According to [**depcheck**](npm.im/depcheck), here's a probably semi-inaccurate list:

``` bash
$ depcheck

Unused Dependencies
* coverify
* jsonwebtoken
* request

Unused devDependencies
* babel
* babel-eslint
* budo
* doctoc
* faucet
* node-sass
* sass-lint
* require-globify
* tape
* testling
```

Most of the devDeps are probably inaccurate because they're used via npm scripts or babel/browserify, etc.

**Comment by pdehaan** [comment]
And if I run **depcheck** from the addon/ directory, I get these results:

```
➜  addon git:(master) $ depcheck

Unused devDependencies
* babel-eslint
* eslint-config-airbnb
* jsonwebtoken
* request
* watchify-server
```

**Comment by pdehaan** [comment]
I'm a bit confused by **jsonwebtoken**. Looks like we have it as a dependency for both the site and the add-on, and **depcheck** thinks it's unused for both.

I found one reference in [/addon/bin/sign:19](https://github.com/mozilla/testpilot/blob/9f323963554d2267de4dc0e84b84ce58a9b75e7b/addon/bin/sign#L19) which **depcheck** may not have scanned since the file doesn't have a .js extension.

But not sure if we need the package in _both_ package.json files, or if one is extraneous.

**Comment by meandavejustice** [comment]
a complete list of deps that need to be updated would be:
`jsonwebtoken` and `request` are deps for the addon. They only need to be in `addon/package.json`.
`coverify` should be moved to the `devDependencies` section in the top level `package.json`
