### ISSUE TITLE
Signing up for a new Firefox Account leaves you at a deadend

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#717]
This was reported to me:

If you hit Test Pilot as a new user with no Firefox Account, and go through the sign up flow, once you confirm your email address you are shown a dead end page.

I asked rfkelly and he said we should be passing in verification_redirect=always in our oauth request query params.

Not to side-track my own issue, but while I'm here:  it looks like we are using django-allauth,  but then copy/paste the FxA specific code into our code instead of using the version in django-allauth: https://github.com/mozilla/testpilot/tree/master/testpilot/users/providers/fxa .  Why is that?

**Comment by lmorchard** [comment]
> Not to side-track my own issue, but while I'm here: it looks like we are using django-allauth, but then copy/paste the FxA specific code into our code instead of using the version in django-allauth: https://github.com/mozilla/testpilot/tree/master/testpilot/users/providers/fxa . Why is that?

Trying to dig up the history to say for sure, but off the top of my head: FxA in django-allauth didn't work out of the box, and [we needed configurable endpoints](https://github.com/mozilla/testpilot/blob/master/testpilot/users/providers/fxa/views.py#L19) to use non-prod FxA for local/dev/staging. 

Looks like allauth might support those things now ([yup, as of Feb 16](https://github.com/pennersr/django-allauth/commit/80351a2da6aa7c3b7a2e5221453676da6bf68277)), so maybe we can back out this local custom code at some point.

**Comment by pdehaan** [comment]
This feels weird to me, considering I signed up to stage+prod today with a shiny new restmail.net account and don't remember seeing this.
I'll try again.

**Comment by ghost** [comment]
Thanks.  Original report from @ckarlof .

**Comment by pdehaan** [comment]
@ckarlof I'm unable to reproduce this on stage with my shiny new ckarl@restmail FxA account.

---

https://testpilot.stage.mozaws.net/__version__ (ca8af43986ea2e0f8f8ecb08625b26f1aae7a6e5):

``` json
{ "build": "https://circleci.com/gh/mozilla/testpilot/325",
  "commit": "ca8af43986ea2e0f8f8ecb08625b26f1aae7a6e5",
  "source": "https://github.com/mozilla/testpilot",
  "version": "2016-05-04" }
```

**Comment by ckarlof** [comment]
Still feels like a dead end to me. What do I click on to get back to Test Pilot?

<img width="646" alt="screenshot 2016-05-05 15 19 02" src="https://cloud.githubusercontent.com/assets/2365255/15059015/c2776a78-12d4-11e6-9827-80219f98072c.png">

**Comment by pdehaan** [comment]
Ah, I see what you're talking about now. You probably have to just verify your account.
After I did that, my browser redirected me back into Test Pilot.

**Comment by pdehaan** [comment]
More information from the handsome @ckarlof via IRC:
- 3:24 PM **<ckarlof>** pdehaan: I must be special because I still get a dead end
- 3:25 PM **<pdehaan>** THIS IS WHY WE CAN'T HAVE NICE THINGS!
- 3:27 PM **<pdehaan>** ckarlof: yeah, looking at your screenshot, I think we're blocking on un-verified fxa accounts.
- 3:27 PM **<ckarlof>** that page is the landing page after I follow the verification link
- 3:28 PM **<pdehaan>** odd, i verified my restmail account by pasting the x-link into a new tab, and the original tab (like your screenshot) immediately redirected me back to the "install add-on" page.
- 3:29 PM **<ckarlof>** how does the user know to go back to the original tab?
- 3:29 PM **<pdehaan>** anything interesting in Browser consoles? 
- 3:29 PM **<ckarlof>** what if they closed the original tab
- 3:29 PM **<ckarlof>** what if they opened the verification link in the original tab
- 3:30 PM **<pdehaan>** I'd guess they're kind of lost, because they woudnt get the add-on installed, and therefore not have the testpilot icon in the toolbar.
- 3:30 PM **<pdehaan>** so they'd have to go back to testpilot.firefox and restart from almost scratch
- 3:30 PM **<pdehaan>** all good points.
- 3:31 PM **<pdehaan>** i'll copy/pasta this into the bug for fun async reading so @clouserw, @lmorchard, @meandavejustice, @nchapman can diagnose severity and fast track tomorrow.

**Comment by pdehaan** [comment]
Removing "enhancement" label, as this is preventing a real-live user from logging in.

**Comment by pdehaan** [comment]
More IRC updates from @ckarlof:
- 3:37 PM **<ckarlof>** JSON_voorhees: pdehaan as the bug mentions, using `verification_redirect=always` might be helpful
- 3:37 PM **<ckarlof>** if I add that I get redirected back to test pilot automatically
- 3:38 PM **<ckarlof>** but I also see this monster on the original page
- 3:38 PM **<ckarlof>** ![](https://irccloud.mozilla.com/file/VrTXQG3x/Screenshot+2016-05-05+15.37.08.png)

**Comment by pdehaan** [comment]
I can reproduce that lovely error page if I try and hit the /accounts/login/callback/ route directly (on stage):
`https://testpilot.stage.mozaws.net/accounts/login/callback/`

(which looks similar to the error I get when I try https://github.com/mozilla/testpilot/issues/489)

---

@chuckharmston points out in IRC:
- 3:44 PM **<@chuck>** pdehaan: that Django error page is only visible when the DEBUG setting is true.
- 3:44 PM **<@chuck>** Note that that's on stage. Can you repro on prod?

On production, I see this output instead:
![social_network_login_failure___test_pilot_and_signing_up_for_a_new_firefox_account_leaves_you_at_a_deadend_ _issue__717_ _mozilla_testpilot_and_inbox__2_577__-_pdehaan_mozilla_com_-_mozilla_mail](https://cloud.githubusercontent.com/assets/557895/15059623/ab915cde-12d8-11e6-8bdf-ab86c91bf25f.png)

**Comment by pdehaan** [comment]
Interestingly (or not), if I click the [Sign In] link from that "Social Network Login Failure" page above, sign in to my FxA account, I get redirected to a https://testpilot.firefox.com/accounts/profile/ which gives me a nice "Four Oh Four!" page.

![firefox_test_pilot](https://cloud.githubusercontent.com/assets/557895/15059652/e7ab84ec-12d8-11e6-876e-c393806c4214.png)

**Comment by pdehaan** [comment]
@ckprice @clouserw @nchapman Can I get a triage on this? My gut is telling me it might be a blocker.

**Comment by nchapman** [comment]
@ckprice and I observed this in the wild. cgroswird installed Test Pilot by creating a new Firefox account. She had no trouble with the flow, including checking her email to verify, but was then confused by the dead end verification page. We pointed her back to the original tab she was on (which had auto advanced by this point), but she still wasn't clear on what had happened.

I think we're going to lose a lot of people at this stage of the flow if we don't have an easy way to redirect them back to Test Pilot after verifying.

**Comment by ckprice** [comment]
> @ckprice @clouserw @nchapman Can I get a triage on this? My gut is telling me it might be a blocker.

I agree this one is a bit on the gnarly side.

We have our triage at 9pst. If @lmorchard or @meandavejustice get in early and want to start digging into something before we meet, this may be the one to work on.

**Comment by lmorchard** [comment]
Trying to sort my way through all the infodump in this issue...
- Don't visit `/accounts/login/callback/` manually - that's a OAuth callback endpoint and won't do anything helpful for human visitors. Probably should display a better error, since it looks like it's running into an error trying to render the error page.
- There is no `/accounts/profile` page, so that 404 is expected. Another case where we should probably rework that default error page inherited from django-allauth
- You can't add `verification_redirect=always` manually to the OAuth URLs, since the token used in the URL is probably already invalid and the process will fail.

What are you guys trying to do, here? Is the problem as described at the top of the issue still the problem, or is something else happening?

**Comment by lmorchard** [comment]
Got a commit that fixes the error message when trying to render the social network auth failure page, but that doesn't sound like the real issue.

Also tried adding `verification_redirect=always` to the OAuth parameters. That leaves me with Test Pilot open in two tabs: 
1. signed-in Test Pilot after a redirect from the verification page opened from the link in email
2. an error in my original Test Pilot tab because it tried to replay the OAuth sign-in token

Without `verification_redirect=always`, I get:
1. a tab saying my email is verified
2. my original Test Pilot tab reloads & logs in successfully

Is the issue that someone closed the original Test Pilot tab? Or that they can't find a way back to it? Or that it didn't refresh itself after verification?

**Comment by ckarlof** [comment]
> Is the issue that someone closed the original Test Pilot tab? Or that they can't find a way back to it? Or that it didn't refresh itself after verification?

Yep. Users could do many things during the verification process, including:

1) Close the original tab.
2) Open the verification link in the original tab.

These situations create a "dead end".  Adding `verification_redirect=always` should address the "dead end" problem, but as you have found, you get an error replaying the FxA response. I propose that if you get a replayed FxA OAuth response and a user is already logged in, just take the user to the home page (or whatever landing page is appropriate).

**Comment by lmorchard** [comment]
Just submitted PR #732, which might work as some bandaids on this issue. Adds the `verification_redirect=always` param to OAuth flow, fixes the Django error in rendering the OAuth error message page, adds an auto-redirect to the home page when the OAuth error appears.

So, after PR #732, email verification should leave you with Test Pilot opened in 2 tabs, both successfully logged in.
