### ISSUE TITLE
SurveyGizmo post-launch polish

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#737]
Copying over some questions from @rayborn in #667

> We need clarifications from Javaun on the types of answers he'd like to see for "Why do you use multiple tabs?"

Sounds like an @johngruen question.

> Did we reach agreement on sending folks to GitHub issues if they have bugs? Is this only for "givefeedback" (I assume yes)?

I believe we settled on not needing these? Or maybe including this in with the experiment details page. @nchapman @javaun.

> We need clarification on whether/where we should redirect the user somewhere post-survey. SG has delayed redirects, so we could do something like: "Thanks for helping us make Firefox better!" -> 2s -> redirect to TODO

Hmm, maybe. Now that we're opening things in a new tab, it may not be required.

**Comment by johngruen** [comment]
WRT the github link, i'd rather not add it to the survey since it requires an additional acct creation #721 solves for this.

Why do people use multiple tabs (provisional): 
- I don't want to lose the things i find online.
- I'm doing online research
- I'm doing comparison shopping
- I have to manage multiple projects at once
- I just forget to close them
- other, please explain: 

How about we redirect back to the test pilot home page for now...maybe eventually we could add a path concluding the survey on our end.

**Comment by johngruen** [comment]
@ckprice note sure if @rayborn is monitoring issue...can you make sure he sees this.

**Comment by MattGrimes** [comment]
I'll make sure it gets done. Thanks!

**Comment by ghost** [comment]
I see it, thanks!

Edit: Didn't get Matt's update in my inbox and responded via email.  Apologies for the spam.

**Comment by johngruen** [comment]
@rayborn @MattGrimes can i close this?

**Comment by MattGrimes** [comment]
One point of clarification first. Do you still want to redirect back to TxP? Since we are now opening in a new tab you'd end up with two TxP tabs open. I think we just leave it as is, but your call.

**Comment by ckprice** [comment]
> One point of clarification first. Do you still want to redirect back to TxP? Since we are now opening in a new tab you'd end up with two TxP tabs open. I think we just leave it as is, but your call.

I haven't heard any requests for this, and agreed that the new tab addresses this.
