### ISSUE TITLE
Should the production add-on be modifiable to point to non-prod endpoints

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#741]
Since we're likely to break other endpoints and do experiments with them, we might not want to make them discoverable from the add-on. Maybe we could add some kind of flag in the build process on prod to disable the endpoint select list.

**Comment by lmorchard** [comment]
FWIW, there is no build process specifically for prod - the same server image & add-on build gets deployed to all environments.

But, we've got #581 that tries to set the env to the last-visited site after installation. I was thinking as a follow up to that, we might be able to get the add-on to detect & switch automatically to whatever environment you're visiting right then & there - rather than only at startup & installation. Then, the preference drop-down could go away. Maybe have a hidden setting to switch in about:config if you really, really need to lock it to a server for dev purposes

**Comment by ghost** [comment]
Let's make this an about:config pref

**Comment by lmorchard** [comment]
https://github.com/mozilla/testpilot/pull/1201/commits/929dceac5c63f148e1f35dc8016b8fb40ee428dc
