### ISSUE TITLE
audit app.me.installed data

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#742]
https://github.com/mozilla/testpilot/pull/726#issuecomment-217892254

`/api/me` installed key returns addon objects in an array
`sync-installed` event from addon returns objects in the shape of:

``` json
"univeral-search@mozilla.com" {
  "some-data": "for the addon"
}
```

**Comment by lmorchard** [comment]
Probably best to tweak [the server side API](https://github.com/mozilla/testpilot/blob/master/testpilot/users/views.py#L40) to match the add-on data from `sync-installed` - that is, switch from an array to an object containing installed add-on details indexed by add-on ID.

We'll also need to tweak [the landing page GA call & associated tests](https://github.com/mozilla/testpilot/pull/705/files) to reflect this stuff, since it's probably sending bad data right now based on the assumption that the data would look like what the server does vs the add-on

**Comment by lmorchard** [comment]
FWIW, also realized that [`syncAllAddonInstallations()` in the addon](https://github.com/mozilla/testpilot/blob/master/addon/index.js#L349) depends on the current installations array format from the server. So, that will need a tweak - probably more complicated than just an `Object.keys`, because installations need to be filtered for those applicable to the current clientUUID
