### ISSUE TITLE
Add push notifications to Test Pilot for New Experiments

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#753]
So that I can see when a new experiment is released, I would like to receive push notifications in Firefox from Test Pilot.

**Comment by meandavejustice** [comment]
are we talking [push api](https://www.w3.org/TR/push-api/) or updating badge in testpilot addon?

**Comment by johngruen** [comment]
https://wiki.mozilla.org/Firefox/Push_Notifications

It's going to be a minute before i put together a spec for how this should work

**Comment by lmorchard** [comment]
There'll be some infrastructure & logistical things to work through here, such as:
- How do we send the per-user POST requests to the push server(s)? Probably need to work with ops to add an offline work queue (eg. celery) to queue up & process the pings.
- When do we send the notifications? Probably don't want to auto-send every time an Experiment model gets changed or created, because we might make many edits in revising the content before deciding it's notification-worthy. So, that needs to be a manual button to push in the admin page.
- Who do we send notifications to? Maybe only ping users who have an experiment installed for changes, ping everyone for new experiments?

**Comment by lmorchard** [comment]
FWIW, an alternative that might be lighter-weight is to have the add-on poll an API endpoint periodically like an RSS feed that tells it when to show notifications. Push notifications are great for open web content, but we have some bespoke things we can do in the add-on

**Comment by ckarlof** [comment]
> FWIW, an alternative that might be lighter-weight is to have the add-on poll an API endpoint periodically like an RSS feed that tells it when to show notifications.

I'd recommend doing this instead. Push is better suited to delivering time-sensitive user-specific messages. This is likely going to be broadcast, and is not time-sensitive.

**Comment by johngruen** [comment]
For UX, please see: https://mozilla.invisionapp.com/share/Q77S1H6ZC

follow the: "New experiment Notifications flow"

### Important parts
- [ ] It should trigger a push notification to all Test Pilot users when a new experiment is launched
- [ ] It should be able to trigger notifications with different copy to cohorts of Test Pilot users
- [ ] It should measure clicks on the push notification that lead to experiment installs
- [ ] It should measure the different click through rates of notifications with different copy

**Comment by lmorchard** [comment]
How do we define cohorts of Test Pilot users? Just random buckets, or something else?

**Comment by lmorchard** [comment]
Another question: How & where do we want to measure this stuff? Google Analytics? Telemetry? Setting those things up are worth a separate issue of its own.

**Comment by lmorchard** [comment]
Filed issue #1108, because I'm hitting a similar thing in different issues.

**Comment by lmorchard** [comment]
Split the metrics parts out into https://github.com/mozilla/testpilot/issues/1126
