### ISSUE TITLE
Bring users somewhere after they have successfully installed an experiment.

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#759]
Jim Cook had this feedback.

Once a user installs an experiment, and takes (or doesn't take) tour, this is the screen they land on

![after install](https://s3.amazonaws.com/f.cl.ly/items/0A1T0q0y0k1f0c3w1b0I/Image%202016-05-10%20at%2012.46.33%20PM.png?v=f2ad7b73)

Should we bring them to someplace else?
- Maybe back to the front page to allow them to choose another experiment?
- Maybe each experiment wants a `redir_url` field?

@javaun for discussion.

**Comment by javaun** [comment]
Interesting feedback. This is the first we've heard so let's note it and see if it surfaces more.  The nice thing about going right back to experiment page is that you can read the details in case you didn't (and just clicked "Enable"). If we see concerns, we can do more user testing and potentially test some alternatives.

**Comment by chuckharmston** [comment]
>  The nice thing about going right back to experiment page is that you can read the details in case you didn't (and just clicked "Enable").

We could prospectively show a slightly rejiggered version of the page with an emphasis on onboarding-related things. "What now? [Learn more about the add-on]() | [Give feedback]() | [File a bug]() | [Take the tour again]() | [Check out our other experiments]"

**Comment by jcook123** [comment]
There are at least 2 "User Journey's" here.

1)  The User Journey I was expecting.  Loved the fact there were 3 experiments.  Wanted to try all three.  But after enabling just one, there was no trail back to the page to enable the other 2 Experiments.  Felt very frustrating trying to figure out "Where I could find the other User Experiments"

2)  The User Journey as noted by Javaun for those that want to continue to read the details for those just clicking "Enable".

Even in User Journey #2 I would argue there should be Chuck's suggestion of "Interested in Enabling Other Experiements?"  that resides on the Details page.  At minimum, a Button or a Clear Path to satisfy User Journey #1 

It's interesting that in Both User Journey's the "Fast Clicking of the Enable" button is a typical path.  

In any case, the Data of # of Users should suggest whether Users are getting Stuck or Lost and not being able to Enable Experiments #2 and #2 (Tabs and Search).  Primary Assumption is a vast majority will Start at the first offer (Activity Stream) and if I'm right, there  will be significant  "drop off" and not be able to Enable the other 2 Experiments...due to not being able to find the main/original Landing Page.

**Comment by jcook123** [comment]
1 other comment.   There is still a "dead zone" of "What Do You Want a User to Do Next" if we leave them on this page.  It's not that obvious (other than a grey'd out button) and a green "Active" text that are both easily missed.

I'd recommend both a Confirmation pop (thanking them for "climbing in the Test Pilot Cockpit with Mozilla") and/or  "Try Activity Stream Now" prompt to get the User to Engage.   If a user has come this far, there's no better time to engage them with a Try It Now prompt.

**Comment by ghost** [comment]
We chatted about things we could do here, and might explore some options with our User Testing, but it's definitely a case-by-case basis (some experiments wouldn't have anywhere else to redirect).

We're going to close this issue for now as the tour is our current one-size-fits-all option.

There are also some marketing options where someone installs an experiment and we redirect to another experiment they might like.
