### ISSUE TITLE
Test Pilot should have a simple <noscript> experience.

### ISSUE THREAD

**Issue by wchristian** [mozilla/testpilot#774]
I can understand using Javascript for complicated web apps that need to do a lot of things, but in this case you're using JS-only, with no fallback whatsoever, to display what's at heart a completely static site with a gif.

**Comment by johngruen** [comment]
Hi @wchristian we have JS dependencies like Firefox Accounts, so I'm not sure switching to server side templating would make much of a difference since you'd still be blocked on auth...

Nevertheless, I'd like to keep this bug open since we should implement some sort of friendly messaging in our UX for users who disable JS in Firefox. 

FWIW, you can directly access all of the test pilot add-ons through their respective repos and file bugs directly!

**Comment by wchristian** [comment]
Sorry for not mentioning the url, maybe this was a little unclear. :D

I'm talking about https://testpilot.firefox.com/

That page doesn't seem to have any login features in my browser.

**Comment by wchristian** [comment]
Oh, i was looking at the page in Chrome, where it simply does not show the login button, so that may be another bug.

**Comment by johngruen** [comment]
@wchristian yep, Test Pilot only works in Firefox (since it's an add-on). Logging in on Chrome would be a dead end, that's why we surface a Firefox download link.

**Comment by wchristian** [comment]
I understand that, to be more clear: The bug is that there's no hint at anyone being able to log in if viewing the page in FF.

**Comment by chuckharmston** [comment]
A fair action item in that bug is that Test Pilot should have a decent `<noscript>`-type experience. I'll update the title appropriately.

**Comment by johngruen** [comment]
Okay, working on this now.
