### ISSUE TITLE
Unable to Customize Firefox top navigation bar with Testpilot Installed

### ISSUE THREAD

**Issue by Salamafet** [mozilla/testpilot#803]
I have installed Testpilot addon and want to move the button of the addon in the menu section.

But when I switch Firefox in the customize mode the top navigation bar disappear. When I remove Testpilot I can customize the navigation bar again.

![capture du 2016-05-12 12 12 48](https://cloud.githubusercontent.com/assets/783351/15211417/56bee380-183b-11e6-93ba-bc681d026038.png)

I use Elementary OS

Sorry for my bad English.

**Comment by leewalsh** [comment]
I also have this issue, but only when _Tab Center_ is activated. _Test Pilot_ itself has no effect.

I have _Test Pilot_ installed with _Activity Stream_ and _Tab Center_ activated, and cannot move icons to or from the menu bar. I also do not have the option to hide the title bar (this may be intentional, but I would like to keep the option).
I can only move icons between the drop-down menu and the "Additional tools and features" section ("Outil et fonctionnalités supplémentaires" in @Salamafet's screenshot).

Keeping _Test Pilot_ installed but deactivating _Tab Center_ returns the behavior to normal.

FF 46.0.1
OS X 10.11

**Comment by pdehaan** [comment]
Thanks @Salamafet and @leewalsh for the feedback!
I've moved this to the upstream **Tab Center** repo for tracking: https://github.com/bwinton/VerticalTabs/issues/195
