### ISSUE TITLE
Failed to enable the addons

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/testpilot#963]
- Unknown
- Firefox build (most recent release)

A couple of users [#811](https://github.com/mozilla/activity-stream/issues/811), [#803](https://github.com/mozilla/activity-stream/issues/811) have reported that they couldn't enable the addon via TestPilot. According to the issue report, this issue affected both Activity Stream and Universal Search.

**Comment by edwindotcom** [comment]
I repro'd this last night.  I was on a slow connection and the 'enabled' button with just animating.  Eventually it did install, but took a long time but there was no visual cues on the install.

**Comment by ghost** [comment]
Were there any other add-ons installed?  Were there any errors in the console?  Did you get the regular add-on install toolbar popup?  Was it before or after the long wait?  @edmoz - you were on fx 47 also?

**Comment by edwindotcom** [comment]
Wife's machine: 
- few addons installed (last pass),
- tracking protection off,
- i saw 'sync not functioning' or something in the console, but nothing else.
- i installed test pilot addon as expected and got install door hanger
- no addon install pop up for activity stream
- I waited at least 30-60sec
- I was on Fx Beta (fx48) i think

**Comment by ghost** [comment]
https://addons.mozilla.org/en-US/firefox/addon/firebug is a 2.6MB add-on.  If you try to install it, do you get a similar experience?  If not, what is AMO doing that makes it better (do they have a spinner or something)?

I'm trying to determine if this is a UI issue because the add-on is slow to download or if there is a problem installing it.  Thanks!

**Comment by pdehaan** [comment]
Ref: #843

**Comment by ghost** [comment]
Ah, that was marked as being fixed by https://github.com/mozilla/testpilot/issues/660 . Sounds like this is a dupe as well then.

**Comment by pdehaan** [comment]
I don't think I agree with "fixed by". I think #660 just adds a "something went wrong" message, but isn't solving the core issue of several people being unable to install any experiments. We should probably keep this open (and leave CRITICAL label) and see if @meandavejustice and @lmorchard can dig in and find the root cause. Or maybe the Sentry fix (#684) will give us pointers to any potential front/back end errors being thrown but not handled.

**Comment by ghost** [comment]
We tried to reproduce this on the conference internet and were unable to - everything worked fine.  We have #660 for messaging and #684 for sentry.  Do you have any other ideas to reproduce this?
