### ISSUE TITLE
Cannot login with firefox account

### ISSUE THREAD

**Issue by wilbert-vb** [mozilla/testpilot#985]
OS: Windows 10 Insider Preview Build 14361
Browser: Firefox 47.0 Release

---

For an unknown reason my firefox sync account was no longer available and I had to signup again.
I used the same account information and I was able to restore the sync settings and bookmarks from another computer.

However, when I try to login with this renewed firefox account to testpilot, I get either "create login name for this new account", or login fails without a message and I'm back to the main screen.

This issue report is created on a second computer where test pilot was already working and I already was signed in.

I worry that when I sign out, I will have the same problem on this second computer.
How do I attach the test pilot to my recreated firefox account?

Thank you very much,
Wilbert van Bakel

**Comment by johngruen** [comment]
Hey @wilbert-vb ...Not sure I can help you directly with the immediate issue, but here's some helpful info.
1. Flagging @shane-tomlinson from the accounts team to help triage the immediate problem. 
2. You can always create an another Firefox account for Test Pilot using a different email address.
3. We are going to back out the accounts requirement for Test Pilot in the next few months (Q3). The short story here is that the legal and product requirements for the account are no longer valid, so we want to take the opportunity to smooth the user experience for Test Pilot. I realize this does not solve your immediate problem, but we're pretty excited to make Test Pilot easier to use.

Hope this helps!

**Comment by shane-tomlinson** [comment]
@wilbert-vb - Hi, my name is Shane, I work on Firefox Accounts. I have a couple of questions.

1) When did you last try to create a Sync account? When you created your Sync account, did you use Firefox Accounts? In the not-so-distant-past, users were able to sign up for Sync without using Firefox Accounts. I'm wondering if you went through the upgrade path, because it sounds like your former credentials were not initially recognized by Firefox Accounts.
2) I'm trying to understand which component is giving you grief when you refer to: `"create login name for this new account", or login fails without a message and I'm back to the main screen.` There are two components to the Test Pilot login flow, 1) Firefox Accounts, and 2) Test Pilot. It seems to be that at this point, you _are_ able to sign in to Firefox Accounts, then you are sent to Test Pilot which asks for a login name?

Thanks for the report @wilbert-vb - hopefully we can get to the bottom of this.

cc @rfk

**Comment by wilbert-vb** [comment]
Thank you very much for your time, @shane-tomlinson,

My test pilot login worked well until a week ago.

A week ago I could no longer log into my firefox sync account. I don't remember deleting the account myself, but who knows.
What I did to solve this issue is signing up with the same credentials for the firefox sync account. That worked and then I went to a computer with the most recent bookmarks/settings/add-ons and I synced that back to the just (re-)created account, because there was no synced data in the cloud.

1) When did you last try to create a Sync account?
That must have been last week then.

2) I'm trying to understand which component is giving you grief
On the https://testpilot.firefox.com/ page I notice two options: "sign in" and "Get started with a Firefox account".
Both options take me to:

## 

https://accounts.firefox.com/oauth/signin?verification_redirect=always&scope=profile&redirect_uri=http%3A%2F%2Ftestpilot.firefox.com%2Faccounts%2Flogin%2Fcallback%2F&response_type=code&client_id=4636d485f6f0c761&state=0cqeyLWOb4Dv

## 

and when I click the sign in button (profile picture and email address are correct) I return to https://testpilot.firefox.com/ while I expect to be able to select the feature that I want to install.

The test pilot page shows "Get started in 3 easy steps" and I cannot get past step 1.

Perhaps the test pilot system has the old ID from over a week ago and that no longer matches the new Firefox account?

Thank you very much,
Wilbert

**Comment by ghost** [comment]
Firefox Accounts is going away in #994 so I'm going to close this.  Thanks.
