### ISSUE TITLE
omg flat files

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#988]
Keeping our experiment meta-data in the database is easy and quick and lets us update it whenever we want, but it makes our L10n story more complex (not just doing L10n, but we'll also need an interface for localizers).

What if we followed a model more like [jekyll](https://jekyllrb.com/) where we have the site logic and templates separate from the content and we put the experiment metadata in flat files instead of the database.  We could have a script that builds the site from those flat files.

0) Lets us solve our localization story by using L20n for everything on the site all in one place: Site UI and experiment meta-data.  When we run the build script, it would build all the localized files in a logical hierarchy.  (Question: when a string changes, how are localizers notified? -- need an extraction script to email the list?)

1) With a site that has strong separation of content and logic, we would be able to deploy content as often as we'd like meaning way less work for everyone involved in a deploy (wouldn't have to bug ops).

Off the top of my head:
- [ ] Determine and agree on the filesystem structure
- [ ] Write a script to read the l20n files, mush them into our templates, and generate the flat files
- [ ] Adjust the site's routes so requests hit the flat files
- [ ] Copy the current database content into the l20n files
- [ ] Let's _not_ remove the database tables in the same commit so we can rollback, eh?

I'm filing this on 5 hours of sleep while sitting in a presentation so I'm sure I'm forgetting some details, but what's the general reaction? 🌜 

/cc @mostlygeek @lmorchard for comments

**Comment by lmorchard** [comment]
Thinking of poking at this today if I have time. Some things that come to mind: 

We could build all this stuff as part of `/static/` via gulp, and call that our "content" part. Then, `/static/` could be updated & deployed independently from anything related to the Django server code. Could we package that up as a Docker volume, or maybe just a tarball? Alternatively, we could move this `/static/` content to Amazon S3 for lighter-weight updates (ala #141) and only do full-on deployments when server stuff changes (ideally rarely). 

@mostlygeek - is this a feasible thing to auto-deploy from a branch via Circle CI? S3 would probably be way simpler than full Docker deployments.

What should we use to produce the flat content files? JSON, YAML, etc? Store images alongside those files, rather than uploading to S3?

Are there objections / concerns / wishlist items about editing the flat file content via pull requests? Folks like @ckprice & @johngruen have used the Django admin a bunch to tweak content - is there anything that would make editing files more comfortable than using the Django admin? We should probably have an easy way to locally preview content edits, at least.

How would the L20N integration work? Tag each field in the flat file with an l10n-id and extract them all as strings? We've got #551 for following up on Pontoon integration - hoping that can be our one-stop interface for localizing both the "chrome" and the "content" on the site.

Should we consider #497 along with this to upgrade l20n.js to the latest & greatest (& totally new file format)?

**Comment by lmorchard** [comment]
As a side note, this also makes me think maybe we don't even need Ampersand _or_ [React](https://github.com/mozilla/testpilot/issues/865), if we're generating static pages.

**Comment by lmorchard** [comment]
An interim step that occurred to me: Rather than fully switch over to the jekyll-style static page generation right now, we could dump the database content to flat YAML files and have the Experiment models in Django read from those instead of the DB and the API used by the frontend would serve up the same data as usual.

**Comment by mostlygeek** [comment]
How will the app serve the static content?
How will the app know if the content has been updated? 

Some ideas: 
- Keep routing and serving logic in the app
- App should be configurable to load static content from the file system or over HTTP 
  - filesystem makes local dev much easier
- HTTP lets us: 
  - put the content anywhere. S3 being first choice. 
  - decouple static content from app logic.
  - add in transparent caching layers to make loading faster.
- There's still a DB of content. It just accessed over HTTP instead of SQL now.

**Comment by lmorchard** [comment]
It occurs to me the flat files notion is kind of tangled up with the localization goal, and we might want to untangle them. Another interim step that I'm poking at today and next week: 
- Don't switch to flat files, yet. 
- Mark up the experiment pages with `data-l10n-id`s for content fields named for experiments - e.g. `{experiment slug}-{DB field name}`, something like `activity-stream-description` and `tab-center-title`
- Extract en-US L20N strings from the database & check it into git
- When [bug 1280410](https://bugzilla.mozilla.org/show_bug.cgi?id=1280410) is resolved, we should have Pontoon localization enabled which supports the L20N strings

So, we can get localization without moving to flat files, yet. It will mean that changes to experiment content needs some kind of deployment, though

**Comment by lmorchard** [comment]
> There's still a DB of content. It just accessed over HTTP instead of SQL now.

FWIW, the front end app already accesses everything via an HTTP API. With respect to the content we want to localize, that could be all static JSON in S3 as far as the app cares. Though, as I'm thinking it through, flat files don't necessarily get us directly to localization

**Comment by lmorchard** [comment]
> How will the app serve the static content?
> How will the app know if the content has been updated?

Also, I think what we've been thinking in this issue is that there wouldn't necessarily _be_ an app anymore, as such. Just static HTML generated from JSON / YAML / whatever. [We're considering dropping the Firefox Accounts requirement](https://github.com/mozilla/testpilot/issues/994), and we can do most everything over in the client add-on and through other services (e.g. Telemetry), so there's less & less reason to actually have a frontend app or a Django server. Things to think through, here, though

**Comment by lmorchard** [comment]
I have a cunning new plan:
1. Let's export & maintain experiment content directly in [L20N's new `.ftl` format](http://l20n.org/learn/working-with-text-multiline-interpolation) and call that the `en-US` locale. Forget JSON or YAML - FTL is expressive enough for any content we'd want to put into pages, IMO. No string extraction, because our content lives in FTL to begin with.
2. Generate static HTML pages from the `.ftl` files by way of some magical Gulp scripting and React templates.
3. Concatenate all the experiment content `.ftl` files into a single `en-US/content.ftl` and put that in `<link rel="localization" href="..."/>` so L20N can use it.
4. Hook up with Pontoon (#551) to get our base en-US content localized into other locales. I'm told it supports the `.ftl` format already.
5. (bonus points) Generate new static HTML for new locales, if we want. Otherwise, L20N can do the work of magically replacing en-US strings in the original static content with the user's preferred locale.

**Comment by lmorchard** [comment]
So, I'm kind of hacking my way through #497 to get us on an up-to-date version of L20N - which gets us the `.ftl` format. I think I can count that as progress toward this issue, too, given the above plan.

**Comment by jaredhirsch** [comment]
I think this sounds good. It'll make life a lot easier, especially for ops and security folks.

**Comment by chuckharmston** [comment]
We're having a meeting Wednesday to talk about the approach. In anticipation, some notes:

https://public.etherpad-mozilla.org/p/test-pilot-omg-flatfiles

With links to code and deployments.

**Comment by lmorchard** [comment]
Been thinking about this stuff for the past month and tinkering. Have thoughts, so I did a brain dump of things into the etherpad - because I realize this stuff has been broken up between various meetings & chats at London and other contexts. Don't want to reinvent wheels or duplicate work

**Comment by bwinton** [comment]
As a Test Pilot Experiment author, I think the idea of me not changing a database when I update the version of my add-on is a good one, but I wonder what the new process would be.  Would I need to wait for the next push to prod before the changes I made went live?  How often does that happen?

**Comment by lmorchard** [comment]
> As a Test Pilot Experiment author, I think the idea of me not changing a database when I update the version of my add-on is a good one, but I wonder what the new process would be. Would I need to wait for the next push to prod before the changes I made went live? How often does that happen?

I don't think static generation dictates this one way or another. We've got issue #547 to work toward auto-extracting these details directly from the experiment .xpi's or update.rdf. The tools that do that could update a database today and then auto-commit changes to github tomorrow. 

As for release cadence, we're talking a lot about how we could accelerate that up to on-demand deployment if that's just uploading a new static version of the site with no active server-side parts. (In other words, not entirely unlike Github Pages)

**Comment by lmorchard** [comment]
Another weird transitional thought, since we're talking about flat files in a meeting - since FxA is gone now, Django only really does 3 things for the site:
1. Serves up the Ampersand frontend app
2. Serves up read-only experiment content via the JSON API that we edit in /admin/
3. Accept PUT & DELETE requests to track experiment enable / disable

If we resolve #1039 to get usage counts from telemetry, we don't need thing 3. 

Then, we could generate the JSON from the API in thing 2 with a script and practically get rid of all the Django & database infra. 

We wouldn't need to change thing 1 at all, at first. This could reduce the scope of our first chunk of work.

**Comment by lmorchard** [comment]
For reference: https://public.etherpad-mozilla.org/p/test-pilot-omg-flatfiles

**Comment by lmorchard** [comment]
I'm going to call this issue closed, since it's being / been pretty well exploded into separate issues for TXP-32. This issue itself doesn't really have specific action items beyond that, IMO
