### ISSUE TITLE
Back out Firefox Accounts

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#994]
One of the Key Results for Q3. Will add more details soon.

**Comment by pdehaan** [comment]
Spotted this while kvetching in a different bug, but we also have FxA references in the [/legal-copy/terms-of-use.md#termination](https://github.com/mozilla/testpilot/blob/8d481518f501d3a9197cfe02ba6af3403b40db24/legal-copy/terms-of-use.md#termination) docs:

> _"If at any time, you decide you no longer wish to participate in Test Pilot, you may deactivate your Test Pilot account by visiting https://testpilot.firefox.com, **signing in using your Firefox Account,** clicking the "Settings" button, and clicking "Leave Test Pilot"."_

Also, [/legal-copy/terms-of-use.md#account](https://github.com/mozilla/testpilot/blob/8d481518f501d3a9197cfe02ba6af3403b40db24/legal-copy/terms-of-use.md#account):

> _"You'll need to have a Firefox Account to participate in Test Pilot. If you sign up for a Firefox Account, you agree to its Terms of Service and Privacy Notice."_

And the [/docs/FAQs.md#why-does-test-pilot-require-a-firefox-account](https://github.com/mozilla/testpilot/blob/master/docs/FAQs.md#why-does-test-pilot-require-a-firefox-account) FAQ.

**Comment by lmorchard** [comment]
One of the few things we actually use an identity for is counting unique users for the displays of social proof. To replace the source for those counts, we have some options off the top of my head:
1. Find a way to get a MAU count out of Telemetry, say in some JSON API form we can query from the frontend (or cache on the backend). Concerns here would be freshness of the number vs how frequently we can query Telemetry - also, the number would change based on usage.
   
   Of course, if we embrace the changing number, it might be nifty to put a quick little line graph or sparkline on there.
2. Have the main bootstrap add-on ping the server with the `clientUUID` generated on install (instead of using FxA identity) on experiment enable/disable. Concerns here would be that anyone could spoof / toll / spam counts by sending bogus pings. This number would change like it does right now - i.e. only reflecting explicit manual enable / disable and not decaying with inattention

**Comment by pdehaan** [comment]
Ref: https://github.com/mozilla/testpilot/issues/583#issuecomment-215143250

> "If that's too confusing, maybe we should change that model property to just count installations instead of distinct users?"

Maybe this is the easiest solution. This is possibly more "expected" because it'd count me twice if I install the add-on on two separate machines/profiles. That solves the weird case where I install the add-on for a second time, the count increments and then quickly decrements back to the original number. But also means that our install counts will potentially rise quicker than in the past (assuming people install Test Pilot and add-ons on more than one machine).

**Comment by johngruen** [comment]
WRT @pdehaan's legal note above, we'll need a redraft from Brian and Marshall before (or, more likely, as) we take these changes live. Seems like we're making the privacy story significantly better here. @ckprice and I can can coordinate on these changes.

**Comment by johngruen** [comment]
Okay, there's a UX spec for this...now i need to put on my product hat and work that angle as well.

**Comment by johngruen** [comment]
https://invis.io/Q77S1H6ZC

**Comment by ghost** [comment]
> Ref: #583 (comment)
> 
> >   "If that's too confusing, maybe we should change that model property to just count installations instead of distinct users?"
> 
> Maybe this is the easiest solution. This is possibly more "expected" because it'd count me twice if I install the add-on on two separate machines/profiles. That solves the weird case where I install the add-on for a second time, the count increments and then quickly decrements back to the original number. But also means that our install counts will potentially rise quicker than in the past (assuming people install Test Pilot and add-ons on more than one machine).

This is straight forward and makes sense to me.

**Comment by ghost** [comment]
"it's going to be hella dope" --jgruen

**Comment by ckprice** [comment]
Going to close this in favor of #1035.
