### ISSUE TITLE
Add whimisical micro-interaction when install count updates

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#996]
We should do something interesting/eye-catching with the install count number when users install and uninstalls and experiment.

Also, working on adding more buzzwords to my issue titles.

**Comment by johngruen** [comment]
Here's how this should work...Right now, we increment or decrement when the user clicks the enable/disable button. In the new flow we should not do this...Instead the flow proceeds as follows:
1. User clicks enable or disable.
2. In both cases, there's a modal. The user count should ONLY INCREMENT OR DECREMENT AFTER THE MODAL IS DISMISSED.
3. When the count increments or decrements, the span containing the user count should be incremented and decremented and the following animation/class should be applied:

```
@keyframes counter-tick {
  0% {
    color: $black;
    transform: scale(1);
  }

  5% {
    color: $default;
    transform: scale(1.2);
  }
  100% {
    color: $black;
    transform: scale(1);
  }
}

.counter-tick {
  display: inline-block;
  animation: counter-tick 1000ms;
}
```
1. After 1000 ms, remove the `counter-tick` class from the count span.

**Comment by pdehaan** [comment]
Ref #970, where we were discussing what "increment" means (or should mean).

**Comment by lmorchard** [comment]
Not sure where to drop this possibly bad idea except here, but:

Say our counts only update once a day from metrics reports. So, what if we track 2 counts for each experiment: 1) yesterday's count, 2) today's count. 

Then, we display a count interpolated between the two that counts up in "real time" - i.e. it goes up (or down eek!) a point every so often. So, if we had 20000 new users over the last day, we'd see the number tick up every 4 seconds or so (86400 / 20000). And the initial display could be yesterday's count plus the difference to reach today's in proportion to how many hours have passed.

It's a a lie, since we're holding back the count to make it look live - but we're not _inflating_ the number, at least. Might make it seem less odd for the user to see the count go up with their particular installation, and then not change again for 24 hours. Or worse, go back down when they reload the page because we haven't actually counted them yet

**Comment by chuckharmston** [comment]
If we go with @lmorchard's suggestion, we could also do a bit of logic to make the numbers closer to accurate.

The current time is `1476895351`. The data we get from telemetry says:

``` json
"min-vid": {
  "install_count": 80000,
  "install_rate": 4300,
  "last_updated": 1476835200
}
```

86400 seconds in a day (this is turning into a song from Rent), so we are getting a new install every 20.1 seconds or so. There have been 60151 seconds so far today, so we can guess that we've gotten 2994 (`60151*4300/86400`) new installs since the last time that data was updated, and display 82994.

Since that number is "live" (or can be displayed as such), it might give this whimsical microinteraction a little more meaning.

**Comment by chuckharmston** [comment]
Oh, I now that I re-read Les' comment, I see that I'm suggesting the same thing he did. `:facepalm:`

I'm not even sure what my initial read of this was.

`/me coffees`

**Comment by lmorchard** [comment]
> Oh, I now that I re-read Les' comment, I see that I'm suggesting the same thing he did. :facepalm:

I'll take that as a :+1: and great minds think alike :)
